// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Who controls a smart account controller credential.
 * - `custodial`: platform holds the key on behalf of the user.
 * - `self-custodial`: user holds the controller key or passkey.
 * - `mpc`: key is split between user and platform via MPC.
 * 
 * @export
 */
export const AccountCustody = {
    Custodial: 'custodial',
    SelfCustodial: 'self-custodial',
    Mpc: 'mpc',
} as const;
export type AccountCustody = typeof AccountCustody[keyof typeof AccountCustody];


export function instanceOfAccountCustody(value: any): boolean {
    for (const key in AccountCustody) {
        if (Object.prototype.hasOwnProperty.call(AccountCustody, key)) {
            if (AccountCustody[key as keyof typeof AccountCustody] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AccountCustodyFromJSON(json: any): AccountCustody {
    return AccountCustodyFromJSONTyped(json, false);
}

export function AccountCustodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountCustody {
    return json as AccountCustody;
}

export function AccountCustodyToJSON(value?: AccountCustody | null): any {
    return value as any;
}

export function AccountCustodyToJSONTyped(value: any, ignoreDiscriminator: boolean): AccountCustody {
    return value as AccountCustody;
}

