// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SmartAccount } from './SmartAccount';
import {
    SmartAccountFromJSON,
    SmartAccountFromJSONTyped,
    SmartAccountToJSON,
    SmartAccountToJSONTyped,
} from './SmartAccount';
import type { AccountController } from './AccountController';
import {
    AccountControllerFromJSON,
    AccountControllerFromJSONTyped,
    AccountControllerToJSON,
    AccountControllerToJSONTyped,
} from './AccountController';

/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * The canonical Kernel smart-account execution address.
     * @type {string}
     * @memberof Account
     */
    address: string;
    /**
     * The execution account type. All platform accounts execute through a smart wallet.
     * @type {AccountTypeEnum}
     * @memberof Account
     */
    type: AccountTypeEnum;
    /**
     * The credential or key authorized to control the smart account.
     * @type {AccountController}
     * @memberof Account
     */
    controller: AccountController;
    /**
     * Counterfactual Kernel deployment metadata for the execution account.
     * @type {SmartAccount}
     * @memberof Account
     */
    smartAccount: SmartAccount;
}


/**
 * @export
 */
export const AccountTypeEnum = {
    SmartWallet: 'SMART_WALLET'
} as const;
export type AccountTypeEnum = typeof AccountTypeEnum[keyof typeof AccountTypeEnum];


/**
 * Check if a given object implements the Account interface.
 */
export function instanceOfAccount(value: object): value is Account {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'SMART_WALLET') return false;
    
    if (!('controller' in value) || value['controller'] === undefined) return false;
    if ((!('smartAccount' in value) && !('smart_account' in value)) || (value['smartAccount'] === undefined && value['smart_account'] === undefined)) return false;
    return true;
}

export function AccountFromJSON(json: any): Account {
    return AccountFromJSONTyped(json, false);
}

export function AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Account {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'type': json['type'],
        'controller': AccountControllerFromJSON(json['controller']),
        'smartAccount': SmartAccountFromJSON(json['smart_account']),
    };
}

export function AccountToJSON(json: any): Account {
    return AccountToJSONTyped(json, false);
}

export function AccountToJSONTyped(value?: Account | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'type': value['type'],
        'controller': AccountControllerToJSON(value['controller']),
        'smart_account': SmartAccountToJSON(value['smartAccount']),
    };
}

