// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pickup } from './Pickup';
import {
    PickupFromJSON,
    PickupFromJSONTyped,
    PickupToJSON,
    PickupToJSONTyped,
} from './Pickup';
import type { Mint } from './Mint';
import {
    MintFromJSON,
    MintFromJSONTyped,
    MintToJSON,
    MintToJSONTyped,
} from './Mint';
import type { Connect } from './Connect';
import {
    ConnectFromJSON,
    ConnectFromJSONTyped,
    ConnectToJSON,
    ConnectToJSONTyped,
} from './Connect';
import type { SetAttributes } from './SetAttributes';
import {
    SetAttributesFromJSON,
    SetAttributesFromJSONTyped,
    SetAttributesToJSON,
    SetAttributesToJSONTyped,
} from './SetAttributes';
import type { DeleteAttributes } from './DeleteAttributes';
import {
    DeleteAttributesFromJSON,
    DeleteAttributesFromJSONTyped,
    DeleteAttributesToJSON,
    DeleteAttributesToJSONTyped,
} from './DeleteAttributes';
import type { Remote } from './Remote';
import {
    RemoteFromJSON,
    RemoteFromJSONTyped,
    RemoteToJSON,
    RemoteToJSONTyped,
} from './Remote';
import type { Update } from './Update';
import {
    UpdateFromJSON,
    UpdateFromJSONTyped,
    UpdateToJSON,
    UpdateToJSONTyped,
} from './Update';
import type { Drop } from './Drop';
import {
    DropFromJSON,
    DropFromJSONTyped,
    DropToJSON,
    DropToJSONTyped,
} from './Drop';
import type { Burn } from './Burn';
import {
    BurnFromJSON,
    BurnFromJSONTyped,
    BurnToJSON,
    BurnToJSONTyped,
} from './Burn';
import type { ClaimOwnership } from './ClaimOwnership';
import {
    ClaimOwnershipFromJSON,
    ClaimOwnershipFromJSONTyped,
    ClaimOwnershipToJSON,
    ClaimOwnershipToJSONTyped,
} from './ClaimOwnership';
import type { Disconnect } from './Disconnect';
import {
    DisconnectFromJSON,
    DisconnectFromJSONTyped,
    DisconnectToJSON,
    DisconnectToJSONTyped,
} from './Disconnect';
import type { Permit } from './Permit';
import {
    PermitFromJSON,
    PermitFromJSONTyped,
    PermitToJSON,
    PermitToJSONTyped,
} from './Permit';
import type { Redeem } from './Redeem';
import {
    RedeemFromJSON,
    RedeemFromJSONTyped,
    RedeemToJSON,
    RedeemToJSONTyped,
} from './Redeem';
import type { Transfer } from './Transfer';
import {
    TransferFromJSON,
    TransferFromJSONTyped,
    TransferToJSON,
    TransferToJSONTyped,
} from './Transfer';

/**
 * 
 * @export
 * @interface ActionsRequest
 */
export interface ActionsRequest {
    /**
     * 
     */
    alias?: string;
    /**
     * Optional secret for permit-based authorization.
     * 
     */
    permitSecret?: string;
    /**
     * 
     */
    mint?: Mint;
    /**
     * 
     */
    transfer?: Transfer;
    /**
     * 
     */
    drop?: Drop;
    /**
     * 
     */
    pickup?: Pickup;
    /**
     * 
     */
    redeem?: Redeem;
    /**
     * 
     */
    burn?: Burn;
    /**
     * 
     */
    update?: Update;
    /**
     * 
     */
    claimOwnership?: ClaimOwnership;
    /**
     * 
     */
    connect?: Connect;
    /**
     * 
     */
    disconnect?: Disconnect;
    /**
     * 
     */
    remote?: Remote;
    /**
     * 
     */
    permit?: Permit;
    /**
     * 
     */
    setAttributes?: SetAttributes;
    /**
     * 
     */
    deleteAttributes?: DeleteAttributes;
}

/**
 * Check if a given object implements the ActionsRequest interface.
 */
export function instanceOfActionsRequest(value: object): value is ActionsRequest {
    return true;
}

export function ActionsRequestFromJSON(json: any): ActionsRequest {
    return ActionsRequestFromJSONTyped(json, false);
}

export function ActionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'] == null ? undefined : json['alias'],
        'permitSecret': json['permit_secret'] == null ? undefined : json['permit_secret'],
        'mint': json['mint'] == null ? undefined : MintFromJSON(json['mint']),
        'transfer': json['transfer'] == null ? undefined : TransferFromJSON(json['transfer']),
        'drop': json['drop'] == null ? undefined : DropFromJSON(json['drop']),
        'pickup': json['pickup'] == null ? undefined : PickupFromJSON(json['pickup']),
        'redeem': json['redeem'] == null ? undefined : RedeemFromJSON(json['redeem']),
        'burn': json['burn'] == null ? undefined : BurnFromJSON(json['burn']),
        'update': json['update'] == null ? undefined : UpdateFromJSON(json['update']),
        'claimOwnership': json['claim_ownership'] == null ? undefined : ClaimOwnershipFromJSON(json['claim_ownership']),
        'connect': json['connect'] == null ? undefined : ConnectFromJSON(json['connect']),
        'disconnect': json['disconnect'] == null ? undefined : DisconnectFromJSON(json['disconnect']),
        'remote': json['remote'] == null ? undefined : RemoteFromJSON(json['remote']),
        'permit': json['permit'] == null ? undefined : PermitFromJSON(json['permit']),
        'setAttributes': json['set_attributes'] == null ? undefined : SetAttributesFromJSON(json['set_attributes']),
        'deleteAttributes': json['delete_attributes'] == null ? undefined : DeleteAttributesFromJSON(json['delete_attributes']),
    };
}

export function ActionsRequestToJSON(json: any): ActionsRequest {
    return ActionsRequestToJSONTyped(json, false);
}

export function ActionsRequestToJSONTyped(value?: ActionsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias': value['alias'],
        'permit_secret': value['permitSecret'],
        'mint': MintToJSON(value['mint']),
        'transfer': TransferToJSON(value['transfer']),
        'drop': DropToJSON(value['drop']),
        'pickup': PickupToJSON(value['pickup']),
        'redeem': RedeemToJSON(value['redeem']),
        'burn': BurnToJSON(value['burn']),
        'update': UpdateToJSON(value['update']),
        'claim_ownership': ClaimOwnershipToJSON(value['claimOwnership']),
        'connect': ConnectToJSON(value['connect']),
        'disconnect': DisconnectToJSON(value['disconnect']),
        'remote': RemoteToJSON(value['remote']),
        'permit': PermitToJSON(value['permit']),
        'set_attributes': SetAttributesToJSON(value['setAttributes']),
        'delete_attributes': DeleteAttributesToJSON(value['deleteAttributes']),
    };
}

