// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeSeriesDataPoint } from './TimeSeriesDataPoint';
import {
    TimeSeriesDataPointFromJSON,
    TimeSeriesDataPointFromJSONTyped,
    TimeSeriesDataPointToJSON,
    TimeSeriesDataPointToJSONTyped,
} from './TimeSeriesDataPoint';

/**
 * 
 * @export
 * @interface ActionsExecutionStatsOut
 */
export interface ActionsExecutionStatsOut {
    /**
     * List of action execution statistics over time
     * @type {Array<TimeSeriesDataPoint>}
     * @memberof ActionsExecutionStatsOut
     */
    data: Array<TimeSeriesDataPoint>;
}

/**
 * Check if a given object implements the ActionsExecutionStatsOut interface.
 */
export function instanceOfActionsExecutionStatsOut(value: object): value is ActionsExecutionStatsOut {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ActionsExecutionStatsOutFromJSON(json: any): ActionsExecutionStatsOut {
    return ActionsExecutionStatsOutFromJSONTyped(json, false);
}

export function ActionsExecutionStatsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionsExecutionStatsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(TimeSeriesDataPointFromJSON)),
    };
}

export function ActionsExecutionStatsOutToJSON(json: any): ActionsExecutionStatsOut {
    return ActionsExecutionStatsOutToJSONTyped(json, false);
}

export function ActionsExecutionStatsOutToJSONTyped(value?: ActionsExecutionStatsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(TimeSeriesDataPointToJSON)),
    };
}

