// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AffectedObject
 */
export interface AffectedObject {
    /**
     * 
     * @type {string}
     * @memberof AffectedObject
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AffectedObject
     */
    templateId: string;
    /**
     * 
     * @type {string}
     * @memberof AffectedObject
     */
    prevStateHash: string;
    /**
     * 
     * @type {string}
     * @memberof AffectedObject
     */
    nextStateHash: string;
    /**
     * 
     * @type {string}
     * @memberof AffectedObject
     */
    prevIntegrityHash: string;
    /**
     * 
     * @type {string}
     * @memberof AffectedObject
     */
    integrityHash: string;
    /**
     * 
     * @type {string}
     * @memberof AffectedObject
     */
    stateChangeId: string;
    /**
     * Type of change applied to the object
     * @type {string}
     * @memberof AffectedObject
     */
    changeType: string;
}

/**
 * Check if a given object implements the AffectedObject interface.
 */
export function instanceOfAffectedObject(value: object): value is AffectedObject {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('templateId' in value) && !('template_id' in value)) || (value['templateId'] === undefined && value['template_id'] === undefined)) return false;
    if ((!('prevStateHash' in value) && !('prev_state_hash' in value)) || (value['prevStateHash'] === undefined && value['prev_state_hash'] === undefined)) return false;
    if ((!('nextStateHash' in value) && !('next_state_hash' in value)) || (value['nextStateHash'] === undefined && value['next_state_hash'] === undefined)) return false;
    if ((!('prevIntegrityHash' in value) && !('prev_integrity_hash' in value)) || (value['prevIntegrityHash'] === undefined && value['prev_integrity_hash'] === undefined)) return false;
    if ((!('integrityHash' in value) && !('integrity_hash' in value)) || (value['integrityHash'] === undefined && value['integrity_hash'] === undefined)) return false;
    if ((!('stateChangeId' in value) && !('state_change_id' in value)) || (value['stateChangeId'] === undefined && value['state_change_id'] === undefined)) return false;
    if ((!('changeType' in value) && !('change_type' in value)) || (value['changeType'] === undefined && value['change_type'] === undefined)) return false;
    return true;
}

export function AffectedObjectFromJSON(json: any): AffectedObject {
    return AffectedObjectFromJSONTyped(json, false);
}

export function AffectedObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffectedObject {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'templateId': json['template_id'],
        'prevStateHash': json['prev_state_hash'],
        'nextStateHash': json['next_state_hash'],
        'prevIntegrityHash': json['prev_integrity_hash'],
        'integrityHash': json['integrity_hash'],
        'stateChangeId': json['state_change_id'],
        'changeType': json['change_type'],
    };
}

export function AffectedObjectToJSON(json: any): AffectedObject {
    return AffectedObjectToJSONTyped(json, false);
}

export function AffectedObjectToJSONTyped(value?: AffectedObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'template_id': value['templateId'],
        'prev_state_hash': value['prevStateHash'],
        'next_state_hash': value['nextStateHash'],
        'prev_integrity_hash': value['prevIntegrityHash'],
        'integrity_hash': value['integrityHash'],
        'state_change_id': value['stateChangeId'],
        'change_type': value['changeType'],
    };
}

