// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AffectedObject
 */
export interface AffectedObject {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    templateId: string;
    /**
     * 
     */
    prevStateHash: string;
    /**
     * 
     */
    nextStateHash: string;
    /**
     * 
     */
    prevIntegrityHash: string;
    /**
     * 
     */
    integrityHash: string;
    /**
     * 
     */
    stateChangeId: string;
    /**
     * Type of change applied to the object
     */
    changeType: string;
}

/**
 * Check if a given object implements the AffectedObject interface.
 */
export function instanceOfAffectedObject(value: object): value is AffectedObject {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('templateId' in (value as Record<string, any>)) && !('template_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['templateId'] === undefined && (value as Record<string, any>)['template_id'] === undefined)) return false;
    if ((!('prevStateHash' in (value as Record<string, any>)) && !('prev_state_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['prevStateHash'] === undefined && (value as Record<string, any>)['prev_state_hash'] === undefined)) return false;
    if ((!('nextStateHash' in (value as Record<string, any>)) && !('next_state_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextStateHash'] === undefined && (value as Record<string, any>)['next_state_hash'] === undefined)) return false;
    if ((!('prevIntegrityHash' in (value as Record<string, any>)) && !('prev_integrity_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['prevIntegrityHash'] === undefined && (value as Record<string, any>)['prev_integrity_hash'] === undefined)) return false;
    if ((!('integrityHash' in (value as Record<string, any>)) && !('integrity_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['integrityHash'] === undefined && (value as Record<string, any>)['integrity_hash'] === undefined)) return false;
    if ((!('stateChangeId' in (value as Record<string, any>)) && !('state_change_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['stateChangeId'] === undefined && (value as Record<string, any>)['state_change_id'] === undefined)) return false;
    if ((!('changeType' in (value as Record<string, any>)) && !('change_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['changeType'] === undefined && (value as Record<string, any>)['change_type'] === undefined)) return false;
    return true;
}

export function AffectedObjectFromJSON(json: any): AffectedObject {
    return AffectedObjectFromJSONTyped(json, false);
}

export function AffectedObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffectedObject {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'templateId': json['template_id'],
        'prevStateHash': json['prev_state_hash'],
        'nextStateHash': json['next_state_hash'],
        'prevIntegrityHash': json['prev_integrity_hash'],
        'integrityHash': json['integrity_hash'],
        'stateChangeId': json['state_change_id'],
        'changeType': json['change_type'],
    };
}

export function AffectedObjectToJSON(json: any): AffectedObject {
    return AffectedObjectToJSONTyped(json, false);
}

export function AffectedObjectToJSONTyped(value?: AffectedObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'template_id': value['templateId'],
        'prev_state_hash': value['prevStateHash'],
        'next_state_hash': value['nextStateHash'],
        'prev_integrity_hash': value['prevIntegrityHash'],
        'integrity_hash': value['integrityHash'],
        'state_change_id': value['stateChangeId'],
        'change_type': value['changeType'],
    };
}

