// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a file or media asset stored in the platform
 * @export
 * @interface Asset
 */
export interface Asset {
    /**
     * Unique identifier for the asset
     * @type {string}
     * @memberof Asset
     */
    id: string;
    /**
     * Human-readable name of the asset
     * @type {string}
     * @memberof Asset
     */
    name?: string;
    /**
     * unique key for the asset
     * @type {string}
     * @memberof Asset
     */
    key?: string;
    /**
     * MIME type of the asset (e.g., image/jpeg, application/pdf)
     * @type {string}
     * @memberof Asset
     */
    type?: string;
    /**
     * Public URL where the asset can be accessed
     * @type {string}
     * @memberof Asset
     */
    url: string;
    /**
     * Cryptographic hash of the asset content for integrity verification
     * @type {string}
     * @memberof Asset
     */
    hash?: string;
    /**
     * Whether the asset is publicly accessible without authentication
     * @type {boolean}
     * @memberof Asset
     */
    isPublic?: boolean;
    /**
     * Timestamp when the asset was uploaded
     * @type {Date}
     * @memberof Asset
     */
    whenCreated?: Date;
}

/**
 * Check if a given object implements the Asset interface.
 */
export function instanceOfAsset(value: object): value is Asset {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function AssetFromJSON(json: any): Asset {
    return AssetFromJSONTyped(json, false);
}

export function AssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Asset {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'key': json['key'] == null ? undefined : json['key'],
        'type': json['type'] == null ? undefined : json['type'],
        'url': json['url'],
        'hash': json['hash'] == null ? undefined : json['hash'],
        'isPublic': json['is_public'] == null ? undefined : json['is_public'],
        'whenCreated': json['when_created'] == null ? undefined : (new Date(json['when_created'])),
    };
}

export function AssetToJSON(json: any): Asset {
    return AssetToJSONTyped(json, false);
}

export function AssetToJSONTyped(value?: Asset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'key': value['key'],
        'type': value['type'],
        'url': value['url'],
        'hash': value['hash'],
        'is_public': value['isPublic'],
        'when_created': value['whenCreated'] == null ? value['whenCreated'] : value['whenCreated'].toISOString(),
    };
}

