// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Format of an object attribute value.
 * @export
 */
export const AttributeContentType = {
    AttributeContentTypeText: 'text',
    AttributeContentTypeJSON: 'json',
} as const;
export type AttributeContentType = typeof AttributeContentType[keyof typeof AttributeContentType];


export function instanceOfAttributeContentType(value: any): boolean {
    for (const key in AttributeContentType) {
        if (Object.prototype.hasOwnProperty.call(AttributeContentType, key)) {
            if (AttributeContentType[key as keyof typeof AttributeContentType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AttributeContentTypeFromJSON(json: any): AttributeContentType {
    return AttributeContentTypeFromJSONTyped(json, false);
}

export function AttributeContentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeContentType {
    return json as AttributeContentType;
}

export function AttributeContentTypeToJSON(value?: AttributeContentType | null): any {
    return value as any;
}

export function AttributeContentTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AttributeContentType {
    return value as AttributeContentType;
}

