// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthBundle
 */
export interface AuthBundle {
    /**
     * Signature scheme discriminator.
     * - eoa: existing EOA path (MetaMask, hardware wallet, KMS-backed service keys)
     * - webauthn:  passkey path (P-256 / WebAuthn assertion over EIP-712 hash)
     * - session_key: session-token path
     * - personal_sign: personal sign path (Ethereum personal_sign)
     * 
     * @type {AuthBundleTypeEnum}
     * @memberof AuthBundle
     */
    type: AuthBundleTypeEnum;
    /**
     * base64url-encoded challenge fetched from GET /auth/challenge immediately
     * before signing. The server consumes (deletes) this challenge after a single
     * successful use to prevent replay attacks.
     * 
     * [type=eoa] the challenge string is the message passed to eth_personal_sign.
     * 
     * [type=webauthn] the challenge string was passed to navigator.credentials.get()
     * as the challenge bytes. The server independently verifies that
     * clientDataJSON.challenge (at challenge_index) equals this value — proving the
     * WebAuthn assertion was made over this specific challenge and not replayed
     * from a different session.
     * 
     * @type {string}
     * @memberof AuthBundle
     */
    challenge?: string;
    /**
     * [type=secp256k1] hex-encoded 65-byte secp256k1 signature (r || s || v)
     * over the EIP-712 hash of the action.
     * This is the existing signature field — same format, just moved under auth.
     * 
     * @type {string}
     * @memberof AuthBundle
     */
    signature?: string;
    /**
     * base64url-encoded credential ID returned by navigator.credentials.get().
     * Used to look up the stored (pubkey_x, pubkey_y) for verification.
     * 
     * @type {string}
     * @memberof AuthBundle
     */
    credentialId?: string;
    /**
     * [type=passkey, REGISTER] Hex-encoded X coordinate of the P-256 public key
     * extracted from the COSE-encoded attestationObject.
     * Required only on first connect (registration). Omit on subsequent connects.
     * 
     * @type {string}
     * @memberof AuthBundle
     */
    pubkeyX?: string;
    /**
     * [type=passkey, REGISTER] Hex-encoded Y coordinate of the P-256 public key.
     * Required only on first connect (registration). Omit on subsequent connects.
     * 
     * @type {string}
     * @memberof AuthBundle
     */
    pubkeyY?: string;
    /**
     * base64url-encoded authenticatorData from the WebAuthn assertion.
     * Server checks: rpIdHash == sha256("pay.dual.network"), UP flag set, UV flag set.
     * 
     * @type {string}
     * @memberof AuthBundle
     */
    authenticatorData?: string;
    /**
     * base64url-encoded clientDataJSON from the WebAuthn assertion.
     * Server checks: type == "webauthn.get", origin == "https://pay.dual.network",
     * challenge field (at challenge_index) base64url-decodes to the expected value.
     * 
     * @type {string}
     * @memberof AuthBundle
     */
    clientDataJson?: string;
    /**
     * hex-encoded r component of the P-256 (ES256) signature.
     * messageHash = sha256(authenticatorData || sha256(clientDataJSON))
     * signature = (r, s) over messageHash
     * 
     * @type {string}
     * @memberof AuthBundle
     */
    signatureR?: string;
    /**
     * hex-encoded s component of the P-256 signature.
     * @type {string}
     * @memberof AuthBundle
     */
    signatureS?: string;
}


/**
 * @export
 */
export const AuthBundleTypeEnum = {
    Eoa: 'eoa',
    Webauthn: 'webauthn',
    SessionKey: 'session_key',
    PersonalSign: 'personal_sign'
} as const;
export type AuthBundleTypeEnum = typeof AuthBundleTypeEnum[keyof typeof AuthBundleTypeEnum];


/**
 * Check if a given object implements the AuthBundle interface.
 */
export function instanceOfAuthBundle(value: object): value is AuthBundle {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AuthBundleFromJSON(json: any): AuthBundle {
    return AuthBundleFromJSONTyped(json, false);
}

export function AuthBundleFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthBundle {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'challenge': json['challenge'] == null ? undefined : json['challenge'],
        'signature': json['signature'] == null ? undefined : json['signature'],
        'credentialId': json['credential_id'] == null ? undefined : json['credential_id'],
        'pubkeyX': json['pubkey_x'] == null ? undefined : json['pubkey_x'],
        'pubkeyY': json['pubkey_y'] == null ? undefined : json['pubkey_y'],
        'authenticatorData': json['authenticator_data'] == null ? undefined : json['authenticator_data'],
        'clientDataJson': json['client_data_json'] == null ? undefined : json['client_data_json'],
        'signatureR': json['signature_r'] == null ? undefined : json['signature_r'],
        'signatureS': json['signature_s'] == null ? undefined : json['signature_s'],
    };
}

export function AuthBundleToJSON(json: any): AuthBundle {
    return AuthBundleToJSONTyped(json, false);
}

export function AuthBundleToJSONTyped(value?: AuthBundle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'challenge': value['challenge'],
        'signature': value['signature'],
        'credential_id': value['credentialId'],
        'pubkey_x': value['pubkeyX'],
        'pubkey_y': value['pubkeyY'],
        'authenticator_data': value['authenticatorData'],
        'client_data_json': value['clientDataJson'],
        'signature_r': value['signatureR'],
        'signature_s': value['signatureS'],
    };
}

