// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BatchStatus } from './BatchStatus';
import {
    BatchStatusFromJSON,
    BatchStatusFromJSONTyped,
    BatchStatusToJSON,
    BatchStatusToJSONTyped,
} from './BatchStatus';
import type { Proof } from './Proof';
import {
    ProofFromJSON,
    ProofFromJSONTyped,
    ProofToJSON,
    ProofToJSONTyped,
} from './Proof';
import type { AffectedActionLog } from './AffectedActionLog';
import {
    AffectedActionLogFromJSON,
    AffectedActionLogFromJSONTyped,
    AffectedActionLogToJSON,
    AffectedActionLogToJSONTyped,
} from './AffectedActionLog';

/**
 * Batch entity representing a collection of blockchain transactions processed together
 * @export
 * @interface Batch
 */
export interface Batch {
    /**
     * Unique identifier for the batch
     */
    id: string;
    /**
     * Sequence number of the batch in the processing order
     */
    sequence: number;
    /**
     * Cryptographic hash of the batch content
     */
    hash: string;
    /**
     * Hash of the previous batch in the sequence
     */
    prevHash?: string;
    /**
     * SMT integrity root for the batch
     */
    integrityRoot: string;
    /**
     * Previous SMT integrity root for the batch
     */
    prevIntegrityRoot: string;
    /**
     * Blockchain address that submitted the batch
     */
    sender: string;
    /**
     * Transaction hash of the batch on the blockchain
     */
    l2TxHash?: string;
    /**
     * Finalization transaction hash of the batch on the blockchain
     */
    l2FinalizationTxHash?: string;
    /**
     * Commitment hash for the batch
     */
    commitment: string;
    /**
     * Hash of all actions included in the batch
     */
    actionsHash: string;
    /**
     * List of action identifiers included in this batch
     */
    affectedActions: Array<AffectedActionLog>;
    /**
     * Total number of actions processed in this batch
     */
    actionsCount: number;
    /**
     * 
     */
    totalFee?: string;
    /**
     * 
     */
    totalFeeWei?: string;
    /**
     * Version number of the batch format
     */
    version: number;
    /**
     * IPFS URL where the batch data is stored
     */
    ipfsUrl?: string;
    /**
     * Current processing status of the batch
     */
    status: BatchStatus;
    /**
     * 
     */
    proof?: Proof;
    /**
     * Identifier of the proof for this batch
     */
    proofId?: string;
    /**
     * Error message if batch processing failed
     */
    error?: string;
    /**
     * Timestamp when the challenge window ends for this batch
     */
    challengeWindowEnd?: Date;
    /**
     * Timestamp when the batch processing was completed
     */
    whenCompleted?: Date;
    /**
     * Timestamp when the batch was last modified
     */
    whenModified?: Date;
    /**
     * Timestamp when the batch was created
     */
    whenCreated: Date;
    /**
     * Creation time in Unix seconds, as committed to by the batch commitment. Written once when the batch is built and never updated; the commitment preimage reads this rather than when_created, so that re-rendering or re-importing the human-facing timestamp cannot change a committed hash.
     */
    whenCreatedUnix?: number;
}



/**
 * Check if a given object implements the Batch interface.
 */
export function instanceOfBatch(value: object): value is Batch {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('sequence' in value) || value['sequence'] === undefined) return false;
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if ((!('integrityRoot' in (value as Record<string, any>)) && !('integrity_root' in (value as Record<string, any>))) || ((value as Record<string, any>)['integrityRoot'] === undefined && (value as Record<string, any>)['integrity_root'] === undefined)) return false;
    if ((!('prevIntegrityRoot' in (value as Record<string, any>)) && !('prev_integrity_root' in (value as Record<string, any>))) || ((value as Record<string, any>)['prevIntegrityRoot'] === undefined && (value as Record<string, any>)['prev_integrity_root'] === undefined)) return false;
    if (!('sender' in value) || value['sender'] === undefined) return false;
    if (!('commitment' in value) || value['commitment'] === undefined) return false;
    if ((!('actionsHash' in (value as Record<string, any>)) && !('actions_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['actionsHash'] === undefined && (value as Record<string, any>)['actions_hash'] === undefined)) return false;
    if ((!('affectedActions' in (value as Record<string, any>)) && !('affected_actions' in (value as Record<string, any>))) || ((value as Record<string, any>)['affectedActions'] === undefined && (value as Record<string, any>)['affected_actions'] === undefined)) return false;
    if ((!('actionsCount' in (value as Record<string, any>)) && !('actions_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['actionsCount'] === undefined && (value as Record<string, any>)['actions_count'] === undefined)) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('whenCreated' in (value as Record<string, any>)) && !('when_created' in (value as Record<string, any>))) || ((value as Record<string, any>)['whenCreated'] === undefined && (value as Record<string, any>)['when_created'] === undefined)) return false;
    return true;
}

export function BatchFromJSON(json: any): Batch {
    return BatchFromJSONTyped(json, false);
}

export function BatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): Batch {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'sequence': json['sequence'],
        'hash': json['hash'],
        'prevHash': json['prev_hash'] == null ? undefined : json['prev_hash'],
        'integrityRoot': json['integrity_root'],
        'prevIntegrityRoot': json['prev_integrity_root'],
        'sender': json['sender'],
        'l2TxHash': json['l2_tx_hash'] == null ? undefined : json['l2_tx_hash'],
        'l2FinalizationTxHash': json['l2_finalization_tx_hash'] == null ? undefined : json['l2_finalization_tx_hash'],
        'commitment': json['commitment'],
        'actionsHash': json['actions_hash'],
        'affectedActions': ((json['affected_actions'] as Array<any>).map(AffectedActionLogFromJSON)),
        'actionsCount': json['actions_count'],
        'totalFee': json['total_fee'] == null ? undefined : json['total_fee'],
        'totalFeeWei': json['total_fee_wei'] == null ? undefined : json['total_fee_wei'],
        'version': json['version'],
        'ipfsUrl': json['ipfs_url'] == null ? undefined : json['ipfs_url'],
        'status': BatchStatusFromJSON(json['status']),
        'proof': json['proof'] == null ? undefined : ProofFromJSON(json['proof']),
        'proofId': json['proof_id'] == null ? undefined : json['proof_id'],
        'error': json['error'] == null ? undefined : json['error'],
        'challengeWindowEnd': json['challenge_window_end'] == null ? undefined : (new Date(json['challenge_window_end'])),
        'whenCompleted': json['when_completed'] == null ? undefined : (new Date(json['when_completed'])),
        'whenModified': json['when_modified'] == null ? undefined : (new Date(json['when_modified'])),
        'whenCreated': (json['when_created'] == null ? json['when_created'] : new Date(json['when_created'])),
        'whenCreatedUnix': json['when_created_unix'] == null ? undefined : json['when_created_unix'],
    };
}

export function BatchToJSON(json: any): Batch {
    return BatchToJSONTyped(json, false);
}

export function BatchToJSONTyped(value?: Batch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'sequence': value['sequence'],
        'hash': value['hash'],
        'prev_hash': value['prevHash'],
        'integrity_root': value['integrityRoot'],
        'prev_integrity_root': value['prevIntegrityRoot'],
        'sender': value['sender'],
        'l2_tx_hash': value['l2TxHash'],
        'l2_finalization_tx_hash': value['l2FinalizationTxHash'],
        'commitment': value['commitment'],
        'actions_hash': value['actionsHash'],
        'affected_actions': ((value['affectedActions'] as Array<any>).map(AffectedActionLogToJSON)),
        'actions_count': value['actionsCount'],
        'total_fee': value['totalFee'],
        'total_fee_wei': value['totalFeeWei'],
        'version': value['version'],
        'ipfs_url': value['ipfsUrl'],
        'status': BatchStatusToJSON(value['status']),
        'proof': ProofToJSON(value['proof']),
        'proof_id': value['proofId'],
        'error': value['error'],
        'challenge_window_end': value['challengeWindowEnd'] == null ? value['challengeWindowEnd'] : value['challengeWindowEnd'].toISOString(),
        'when_completed': value['whenCompleted'] == null ? value['whenCompleted'] : value['whenCompleted'].toISOString(),
        'when_modified': value['whenModified'] == null ? value['whenModified'] : value['whenModified'].toISOString(),
        'when_created': value['whenCreated'] == null ? value['whenCreated'] : value['whenCreated'].toISOString(),
        'when_created_unix': value['whenCreatedUnix'],
    };
}

