// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Burn
 */
export interface Burn {
    /**
     * 
     * @type {string}
     * @memberof Burn
     */
    id: string;
}

/**
 * Check if a given object implements the Burn interface.
 */
export function instanceOfBurn(value: object): value is Burn {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function BurnFromJSON(json: any): Burn {
    return BurnFromJSONTyped(json, false);
}

export function BurnFromJSONTyped(json: any, ignoreDiscriminator: boolean): Burn {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function BurnToJSON(json: any): Burn {
    return BurnToJSONTyped(json, false);
}

export function BurnToJSONTyped(value?: Burn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

