// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckpointStatus } from './CheckpointStatus';
import {
    CheckpointStatusFromJSON,
    CheckpointStatusFromJSONTyped,
    CheckpointStatusToJSON,
    CheckpointStatusToJSONTyped,
} from './CheckpointStatus';
import type { AffectedBatch } from './AffectedBatch';
import {
    AffectedBatchFromJSON,
    AffectedBatchFromJSONTyped,
    AffectedBatchToJSON,
    AffectedBatchToJSONTyped,
} from './AffectedBatch';
import type { Proof } from './Proof';
import {
    ProofFromJSON,
    ProofFromJSONTyped,
    ProofToJSON,
    ProofToJSONTyped,
} from './Proof';

/**
 * Checkpoint entity representing a verified state of the sequencer at a specific point in time
 * @export
 * @interface Checkpoint
 */
export interface Checkpoint {
    /**
     * Unique identifier for the checkpoint
     */
    id: string;
    /**
     * Cryptographic hash of the checkpoint content
     */
    hash: string;
    /**
     * Sequence number of the checkpoint in the processing order
     */
    sequence: number;
    /**
     * Hash of the starting batch in the checkpoint
     */
    startHash: string;
    /**
     * Sequence number of the starting batch in the checkpoint
     */
    startSequence: number;
    /**
     * Sequence number of the ending batch in the checkpoint
     */
    endSequence: number;
    /**
     * Hash of the ending batch in the checkpoint
     */
    endHash: string;
    /**
     * Address of the entity that created the checkpoint
     */
    sender: string;
    /**
     * Hash of the Layer 2 transaction associated with the checkpoint
     */
    l2TxHash?: string;
    /**
     * IPFS URL where the batch data is stored
     */
    ipfsUrl?: string;
    /**
     * Current processing status of the checkpoint
     */
    status: CheckpointStatus;
    /**
     * 
     */
    proof?: Proof;
    /**
     * Identifier of the proof for this batch
     */
    proofId?: string;
    /**
     * Error message if the checkpoint processing failed
     */
    error?: string;
    /**
     * List of affected batches in this checkpoint
     */
    affectedBatches?: Array<AffectedBatch>;
    /**
     * Timestamp when the checkpoint processing was completed
     */
    whenCompleted?: Date;
    /**
     * Timestamp when the checkpoint was last modified
     */
    whenModified?: Date;
    /**
     * Timestamp when the checkpoint was created
     */
    whenCreated: Date;
}



/**
 * Check if a given object implements the Checkpoint interface.
 */
export function instanceOfCheckpoint(value: object): value is Checkpoint {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if (!('sequence' in value) || value['sequence'] === undefined) return false;
    if ((!('startHash' in (value as Record<string, any>)) && !('start_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['startHash'] === undefined && (value as Record<string, any>)['start_hash'] === undefined)) return false;
    if ((!('startSequence' in (value as Record<string, any>)) && !('start_sequence' in (value as Record<string, any>))) || ((value as Record<string, any>)['startSequence'] === undefined && (value as Record<string, any>)['start_sequence'] === undefined)) return false;
    if ((!('endSequence' in (value as Record<string, any>)) && !('end_sequence' in (value as Record<string, any>))) || ((value as Record<string, any>)['endSequence'] === undefined && (value as Record<string, any>)['end_sequence'] === undefined)) return false;
    if ((!('endHash' in (value as Record<string, any>)) && !('end_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['endHash'] === undefined && (value as Record<string, any>)['end_hash'] === undefined)) return false;
    if (!('sender' in value) || value['sender'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('whenCreated' in (value as Record<string, any>)) && !('when_created' in (value as Record<string, any>))) || ((value as Record<string, any>)['whenCreated'] === undefined && (value as Record<string, any>)['when_created'] === undefined)) return false;
    return true;
}

export function CheckpointFromJSON(json: any): Checkpoint {
    return CheckpointFromJSONTyped(json, false);
}

export function CheckpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): Checkpoint {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'hash': json['hash'],
        'sequence': json['sequence'],
        'startHash': json['start_hash'],
        'startSequence': json['start_sequence'],
        'endSequence': json['end_sequence'],
        'endHash': json['end_hash'],
        'sender': json['sender'],
        'l2TxHash': json['l2_tx_hash'] == null ? undefined : json['l2_tx_hash'],
        'ipfsUrl': json['ipfs_url'] == null ? undefined : json['ipfs_url'],
        'status': CheckpointStatusFromJSON(json['status']),
        'proof': json['proof'] == null ? undefined : ProofFromJSON(json['proof']),
        'proofId': json['proof_id'] == null ? undefined : json['proof_id'],
        'error': json['error'] == null ? undefined : json['error'],
        'affectedBatches': json['affected_batches'] == null ? undefined : ((json['affected_batches'] as Array<any>).map(AffectedBatchFromJSON)),
        'whenCompleted': json['when_completed'] == null ? undefined : (new Date(json['when_completed'])),
        'whenModified': json['when_modified'] == null ? undefined : (new Date(json['when_modified'])),
        'whenCreated': (json['when_created'] == null ? json['when_created'] : new Date(json['when_created'])),
    };
}

export function CheckpointToJSON(json: any): Checkpoint {
    return CheckpointToJSONTyped(json, false);
}

export function CheckpointToJSONTyped(value?: Checkpoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'hash': value['hash'],
        'sequence': value['sequence'],
        'start_hash': value['startHash'],
        'start_sequence': value['startSequence'],
        'end_sequence': value['endSequence'],
        'end_hash': value['endHash'],
        'sender': value['sender'],
        'l2_tx_hash': value['l2TxHash'],
        'ipfs_url': value['ipfsUrl'],
        'status': CheckpointStatusToJSON(value['status']),
        'proof': ProofToJSON(value['proof']),
        'proof_id': value['proofId'],
        'error': value['error'],
        'affected_batches': value['affectedBatches'] == null ? undefined : ((value['affectedBatches'] as Array<any>).map(AffectedBatchToJSON)),
        'when_completed': value['whenCompleted'] == null ? value['whenCompleted'] : value['whenCompleted'].toISOString(),
        'when_modified': value['whenModified'] == null ? value['whenModified'] : value['whenModified'].toISOString(),
        'when_created': value['whenCreated'] == null ? value['whenCreated'] : value['whenCreated'].toISOString(),
    };
}

