// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimOwnership
 */
export interface ClaimOwnership {
    /**
     * 
     * @type {string}
     * @memberof ClaimOwnership
     */
    id: string;
}

/**
 * Check if a given object implements the ClaimOwnership interface.
 */
export function instanceOfClaimOwnership(value: object): value is ClaimOwnership {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ClaimOwnershipFromJSON(json: any): ClaimOwnership {
    return ClaimOwnershipFromJSONTyped(json, false);
}

export function ClaimOwnershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimOwnership {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function ClaimOwnershipToJSON(json: any): ClaimOwnership {
    return ClaimOwnershipToJSONTyped(json, false);
}

export function ClaimOwnershipToJSONTyped(value?: ClaimOwnership | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

