// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Crud
 */
export interface Crud {
    /**
     * 
     */
    read: boolean;
    /**
     * 
     */
    create: boolean;
    /**
     * 
     */
    update: boolean;
    /**
     * 
     */
    _delete: boolean;
}

/**
 * Check if a given object implements the Crud interface.
 */
export function instanceOfCrud(value: object): value is Crud {
    if (!('read' in value) || value['read'] === undefined) return false;
    if (!('create' in value) || value['create'] === undefined) return false;
    if (!('update' in value) || value['update'] === undefined) return false;
    if ((!('_delete' in (value as Record<string, any>)) && !('delete' in (value as Record<string, any>))) || ((value as Record<string, any>)['_delete'] === undefined && (value as Record<string, any>)['delete'] === undefined)) return false;
    return true;
}

export function CrudFromJSON(json: any): Crud {
    return CrudFromJSONTyped(json, false);
}

export function CrudFromJSONTyped(json: any, ignoreDiscriminator: boolean): Crud {
    if (json == null) {
        return json;
    }
    return {
        
        'read': json['read'],
        'create': json['create'],
        'update': json['update'],
        '_delete': json['delete'],
    };
}

export function CrudToJSON(json: any): Crud {
    return CrudToJSONTyped(json, false);
}

export function CrudToJSONTyped(value?: Crud | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'read': value['read'],
        'create': value['create'],
        'update': value['update'],
        'delete': value['_delete'],
    };
}

