// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteAttributes
 */
export interface DeleteAttributes {
    /**
     * 
     */
    id: string;
    /**
     * Optional optimistic-concurrency precondition for the target object.
     */
    expectedObjectNonce?: number;
    /**
     * 
     */
    keys: Set<string>;
}

/**
 * Check if a given object implements the DeleteAttributes interface.
 */
export function instanceOfDeleteAttributes(value: object): value is DeleteAttributes {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('keys' in value) || value['keys'] === undefined) return false;
    return true;
}

export function DeleteAttributesFromJSON(json: any): DeleteAttributes {
    return DeleteAttributesFromJSONTyped(json, false);
}

export function DeleteAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'expectedObjectNonce': json['expected_object_nonce'] == null ? undefined : json['expected_object_nonce'],
        'keys': new Set(json['keys']),
    };
}

export function DeleteAttributesToJSON(json: any): DeleteAttributes {
    return DeleteAttributesToJSONTyped(json, false);
}

export function DeleteAttributesToJSONTyped(value?: DeleteAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'expected_object_nonce': value['expectedObjectNonce'],
        'keys': Array.from(value['keys'] as Set<any>),
    };
}

