// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Network } from './Network';
import {
    NetworkFromJSON,
    NetworkFromJSONTyped,
    NetworkToJSON,
    NetworkToJSONTyped,
} from './Network';
import type { DepositToken } from './DepositToken';
import {
    DepositTokenFromJSON,
    DepositTokenFromJSONTyped,
    DepositTokenToJSON,
    DepositTokenToJSONTyped,
} from './DepositToken';
import type { DepositStatus } from './DepositStatus';
import {
    DepositStatusFromJSON,
    DepositStatusFromJSONTyped,
    DepositStatusToJSON,
    DepositStatusToJSONTyped,
} from './DepositStatus';

/**
 * 
 * @export
 * @interface Deposit
 */
export interface Deposit {
    /**
     * Unique identifier for the deposit
     * @type {string}
     * @memberof Deposit
     */
    id: string;
    /**
     * Organization identifier associated with the deposit
     * @type {string}
     * @memberof Deposit
     */
    orgId: string;
    /**
     * Identifier of the user who initiated the deposit.
     * @type {string}
     * @memberof Deposit
     */
    sender: string;
    /**
     * Amount of the deposit.
     * @type {string}
     * @memberof Deposit
     */
    amount: string;
    /**
     * 
     * @type {DepositToken}
     * @memberof Deposit
     */
    token: DepositToken;
    /**
     * Token address for the deposit.
     * @type {string}
     * @memberof Deposit
     */
    tokenAddress: string;
    /**
     * 
     * @type {Network}
     * @memberof Deposit
     */
    network: Network;
    /**
     * Transaction hash for the deposit.
     * @type {string}
     * @memberof Deposit
     */
    txHash: string;
    /**
     * Block number for the deposit.
     * @type {number}
     * @memberof Deposit
     */
    blockNum: number;
    /**
     * 
     * @type {DepositStatus}
     * @memberof Deposit
     */
    status: DepositStatus;
    /**
     * Timestamp of when the deposit was created.
     * @type {Date}
     * @memberof Deposit
     */
    whenCreated: Date;
    /**
     * Timestamp of the last modification to the deposit.
     * @type {Date}
     * @memberof Deposit
     */
    whenModified: Date;
}



/**
 * Check if a given object implements the Deposit interface.
 */
export function instanceOfDeposit(value: object): value is Deposit {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('orgId' in value) && !('org_id' in value)) || (value['orgId'] === undefined && value['org_id'] === undefined)) return false;
    if (!('sender' in value) || value['sender'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if ((!('tokenAddress' in value) && !('token_address' in value)) || (value['tokenAddress'] === undefined && value['token_address'] === undefined)) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if ((!('txHash' in value) && !('tx_hash' in value)) || (value['txHash'] === undefined && value['tx_hash'] === undefined)) return false;
    if ((!('blockNum' in value) && !('block_num' in value)) || (value['blockNum'] === undefined && value['block_num'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('whenCreated' in value) && !('when_created' in value)) || (value['whenCreated'] === undefined && value['when_created'] === undefined)) return false;
    if ((!('whenModified' in value) && !('when_modified' in value)) || (value['whenModified'] === undefined && value['when_modified'] === undefined)) return false;
    return true;
}

export function DepositFromJSON(json: any): Deposit {
    return DepositFromJSONTyped(json, false);
}

export function DepositFromJSONTyped(json: any, ignoreDiscriminator: boolean): Deposit {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'orgId': json['org_id'],
        'sender': json['sender'],
        'amount': json['amount'],
        'token': DepositTokenFromJSON(json['token']),
        'tokenAddress': json['token_address'],
        'network': NetworkFromJSON(json['network']),
        'txHash': json['tx_hash'],
        'blockNum': json['block_num'],
        'status': DepositStatusFromJSON(json['status']),
        'whenCreated': (new Date(json['when_created'])),
        'whenModified': (new Date(json['when_modified'])),
    };
}

export function DepositToJSON(json: any): Deposit {
    return DepositToJSONTyped(json, false);
}

export function DepositToJSONTyped(value?: Deposit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'org_id': value['orgId'],
        'sender': value['sender'],
        'amount': value['amount'],
        'token': DepositTokenToJSON(value['token']),
        'token_address': value['tokenAddress'],
        'network': NetworkToJSON(value['network']),
        'tx_hash': value['txHash'],
        'block_num': value['blockNum'],
        'status': DepositStatusToJSON(value['status']),
        'when_created': value['whenCreated'].toISOString(),
        'when_modified': value['whenModified'].toISOString(),
    };
}

