// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActionsRequest } from './ActionsRequest';
import {
    ActionsRequestFromJSON,
    ActionsRequestFromJSONTyped,
    ActionsRequestToJSON,
    ActionsRequestToJSONTyped,
} from './ActionsRequest';
import type { AuthBundle } from './AuthBundle';
import {
    AuthBundleFromJSON,
    AuthBundleFromJSONTyped,
    AuthBundleToJSON,
    AuthBundleToJSONTyped,
} from './AuthBundle';

/**
 * Request payload for executing blockchain actions through the event bus system
 * @export
 * @interface ExecuteRequest
 */
export interface ExecuteRequest {
    /**
     * The blockchain action to be executed
     * @type {ActionsRequest}
     * @memberof ExecuteRequest
     */
    action: ActionsRequest;
    /**
     * Unique number to prevent replay attacks. Must be the current nonce
     * for the wallet — fetch from the object or wallet state before signing.
     * 
     * @type {number}
     * @memberof ExecuteRequest
     */
    nonce: number;
    /**
     * Tagged authentication bundle. The type field routes to the correct
     * verifier. The auth type is persisted in the action-log and travels
     * with the batch so the sequencer dispatches correctly during fraud
     * proof generation.
     * 
     * The EIP-712 hash of (action + nonce + domain) is what gets signed
     * in all cases — the auth bundle carries the signature over that hash.
     * 
     * For passkey users: the EIP-712 hash IS the WebAuthn challenge.
     * The client passes it directly to navigator.credentials.get() as
     * the challenge bytes.
     * 
     * @type {AuthBundle}
     * @memberof ExecuteRequest
     */
    auth?: AuthBundle;
}

/**
 * Check if a given object implements the ExecuteRequest interface.
 */
export function instanceOfExecuteRequest(value: object): value is ExecuteRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    return true;
}

export function ExecuteRequestFromJSON(json: any): ExecuteRequest {
    return ExecuteRequestFromJSONTyped(json, false);
}

export function ExecuteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecuteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'action': ActionsRequestFromJSON(json['action']),
        'nonce': json['nonce'],
        'auth': json['auth'] == null ? undefined : AuthBundleFromJSON(json['auth']),
    };
}

export function ExecuteRequestToJSON(json: any): ExecuteRequest {
    return ExecuteRequestToJSONTyped(json, false);
}

export function ExecuteRequestToJSONTyped(value?: ExecuteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': ActionsRequestToJSON(value['action']),
        'nonce': value['nonce'],
        'auth': AuthBundleToJSON(value['auth']),
    };
}

