// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authoring definition for one visual representation of a face. Face views are
 * returned only by authenticated face-management endpoints. Object inventory
 * endpoints expose resolved display descriptors instead of this source data.
 * 
 * @export
 * @interface FaceView
 */
export interface FaceView {
    /**
     * Intended display context for the view.
     * @type {FaceViewVariantEnum}
     * @memberof FaceView
     */
    variant: FaceViewVariantEnum;
    /**
     * Media type produced by the view.
     * @type {FaceViewMediaTypeEnum}
     * @memberof FaceView
     */
    mediaType: FaceViewMediaTypeEnum;
    /**
     * Renderer source for this view. For the go-template renderer this is an
     * html/template document whose placeholders are resolved from object data.
     * 
     * @type {string}
     * @memberof FaceView
     */
    content?: string;
    /**
     * External HTTPS representation URL used when the view has no inline source.
     * Resolved object display descriptors preserve existing query parameters and
     * add `object_id` plus the requested `variant` for the remote application.
     * 
     * @type {string}
     * @memberof FaceView
     */
    url?: string;
    /**
     * Recommended width/height ratio for layout reservation.
     * @type {string}
     * @memberof FaceView
     */
    aspectRatio?: string;
    /**
     * Whether the representation is intended to accept user interaction.
     * @type {boolean}
     * @memberof FaceView
     */
    interactive?: boolean;
    /**
     * Public, non-executable application configuration for this view. Resolved
     * object displays may expose this value to the view application and its
     * authenticated bridge context. It must not contain renderer source,
     * credentials, secrets, tokens, or capability grants.
     * 
     * @type {{ [key: string]: any; }}
     * @memberof FaceView
     */
    config?: { [key: string]: any; };
}


/**
 * @export
 */
export const FaceViewVariantEnum = {
    Default: 'default',
    Card: 'card',
    Detail: 'detail',
    Share: 'share'
} as const;
export type FaceViewVariantEnum = typeof FaceViewVariantEnum[keyof typeof FaceViewVariantEnum];

/**
 * @export
 */
export const FaceViewMediaTypeEnum = {
    TextHtml: 'text/html',
    ImageSvgxml: 'image/svg+xml',
    ImagePng: 'image/png',
    ImageJpeg: 'image/jpeg',
    ImageWebp: 'image/webp'
} as const;
export type FaceViewMediaTypeEnum = typeof FaceViewMediaTypeEnum[keyof typeof FaceViewMediaTypeEnum];


/**
 * Check if a given object implements the FaceView interface.
 */
export function instanceOfFaceView(value: object): value is FaceView {
    if (!('variant' in value) || value['variant'] === undefined) return false;
    if ((!('mediaType' in value) && !('media_type' in value)) || (value['mediaType'] === undefined && value['media_type'] === undefined)) return false;
    return true;
}

export function FaceViewFromJSON(json: any): FaceView {
    return FaceViewFromJSONTyped(json, false);
}

export function FaceViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): FaceView {
    if (json == null) {
        return json;
    }
    return {
        
        'variant': json['variant'],
        'mediaType': json['media_type'],
        'content': json['content'] == null ? undefined : json['content'],
        'url': json['url'] == null ? undefined : json['url'],
        'aspectRatio': json['aspect_ratio'] == null ? undefined : json['aspect_ratio'],
        'interactive': json['interactive'] == null ? undefined : json['interactive'],
        'config': json['config'] == null ? undefined : json['config'],
    };
}

export function FaceViewToJSON(json: any): FaceView {
    return FaceViewToJSONTyped(json, false);
}

export function FaceViewToJSONTyped(value?: FaceView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'variant': value['variant'],
        'media_type': value['mediaType'],
        'content': value['content'],
        'url': value['url'],
        'aspect_ratio': value['aspectRatio'],
        'interactive': value['interactive'],
        'config': value['config'],
    };
}

