// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Asset } from './Asset';
import {
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
    AssetToJSONTyped,
} from './Asset';

/**
 * 
 * @export
 * @interface FaceUpdate
 */
export interface FaceUpdate {
    /**
     * Name of the face.
     * @type {string}
     * @memberof FaceUpdate
     */
    name?: string;
    /**
     * URL of the face, typically pointing to an image or resource.
     * @type {string}
     * @memberof FaceUpdate
     */
    url?: string;
    /**
     * Go html/template source used to render public objects. Placeholders use
     * dot notation, for example {{.owner}} or {{.metadata.name}}.
     * 
     * @type {string}
     * @memberof FaceUpdate
     */
    content?: string;
    /**
     * Optional configuration data for customizing the face.
     * @type {{ [key: string]: any; }}
     * @memberof FaceUpdate
     */
    config?: { [key: string]: any; };
    /**
     * List of resources required or utilized by the face.
     * @type {Array<Asset>}
     * @memberof FaceUpdate
     */
    assets?: Array<Asset>;
    /**
     * Timestamp of the last modification to the face.
     * @type {Date}
     * @memberof FaceUpdate
     */
    whenModified?: Date;
}

/**
 * Check if a given object implements the FaceUpdate interface.
 */
export function instanceOfFaceUpdate(value: object): value is FaceUpdate {
    return true;
}

export function FaceUpdateFromJSON(json: any): FaceUpdate {
    return FaceUpdateFromJSONTyped(json, false);
}

export function FaceUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FaceUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'url': json['url'] == null ? undefined : json['url'],
        'content': json['content'] == null ? undefined : json['content'],
        'config': json['config'] == null ? undefined : json['config'],
        'assets': json['assets'] == null ? undefined : ((json['assets'] as Array<any>).map(AssetFromJSON)),
        'whenModified': json['when_modified'] == null ? undefined : (new Date(json['when_modified'])),
    };
}

export function FaceUpdateToJSON(json: any): FaceUpdate {
    return FaceUpdateToJSONTyped(json, false);
}

export function FaceUpdateToJSONTyped(value?: FaceUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'content': value['content'],
        'config': value['config'],
        'assets': value['assets'] == null ? undefined : ((value['assets'] as Array<any>).map(AssetToJSON)),
        'when_modified': value['whenModified'] == null ? value['whenModified'] : value['whenModified'].toISOString(),
    };
}

