// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Object and display context used to render an authenticated face preview.
 * @export
 * @interface FacePreviewIn
 */
export interface FacePreviewIn {
    /**
     * Object whose public projection supplies preview data.
     * @type {string}
     * @memberof FacePreviewIn
     */
    objectId: string;
    /**
     * Face view to preview.
     * @type {FacePreviewInVariantEnum}
     * @memberof FacePreviewIn
     */
    variant?: FacePreviewInVariantEnum;
}


/**
 * @export
 */
export const FacePreviewInVariantEnum = {
    Card: 'card',
    Detail: 'detail',
    Share: 'share'
} as const;
export type FacePreviewInVariantEnum = typeof FacePreviewInVariantEnum[keyof typeof FacePreviewInVariantEnum];


/**
 * Check if a given object implements the FacePreviewIn interface.
 */
export function instanceOfFacePreviewIn(value: object): value is FacePreviewIn {
    if ((!('objectId' in value) && !('object_id' in value)) || (value['objectId'] === undefined && value['object_id'] === undefined)) return false;
    return true;
}

export function FacePreviewInFromJSON(json: any): FacePreviewIn {
    return FacePreviewInFromJSONTyped(json, false);
}

export function FacePreviewInFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacePreviewIn {
    if (json == null) {
        return json;
    }
    return {

        'objectId': json['object_id'],
        'variant': json['variant'] == null ? undefined : json['variant'],
    };
}

export function FacePreviewInToJSON(json: any): FacePreviewIn {
    return FacePreviewInToJSONTyped(json, false);
}

export function FacePreviewInToJSONTyped(value?: FacePreviewIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'object_id': value['objectId'],
        'variant': value['variant'],
    };
}
