// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FactoryUpdate
 */
export interface FactoryUpdate {
    /**
     * 
     * @type {number}
     * @memberof FactoryUpdate
     */
    maxSupply?: number;
    /**
     * 
     * @type {Date}
     * @memberof FactoryUpdate
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof FactoryUpdate
     */
    endTime?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof FactoryUpdate
     */
    whitelist?: Array<string>;
}

/**
 * Check if a given object implements the FactoryUpdate interface.
 */
export function instanceOfFactoryUpdate(value: object): value is FactoryUpdate {
    return true;
}

export function FactoryUpdateFromJSON(json: any): FactoryUpdate {
    return FactoryUpdateFromJSONTyped(json, false);
}

export function FactoryUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FactoryUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'maxSupply': json['max_supply'] == null ? undefined : json['max_supply'],
        'startTime': json['start_time'] == null ? undefined : (new Date(json['start_time'])),
        'endTime': json['end_time'] == null ? undefined : (new Date(json['end_time'])),
        'whitelist': json['whitelist'] == null ? undefined : json['whitelist'],
    };
}

export function FactoryUpdateToJSON(json: any): FactoryUpdate {
    return FactoryUpdateToJSONTyped(json, false);
}

export function FactoryUpdateToJSONTyped(value?: FactoryUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_supply': value['maxSupply'],
        'start_time': value['startTime'] == null ? value['startTime'] : value['startTime'].toISOString(),
        'end_time': value['endTime'] == null ? value['endTime'] : value['endTime'].toISOString(),
        'whitelist': value['whitelist'],
    };
}

