// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Fee statistics broken down by action name
 * @export
 * @interface FeesTimeData
 */
export interface FeesTimeData {
    /**
     * The key for the fee statistic, e.g., action name or time interval.
     * @type {string}
     * @memberof FeesTimeData
     */
    key: string;
    /**
     * Timestamp for this fee statistic
     * @type {Date}
     * @memberof FeesTimeData
     */
    when: Date;
    /**
     * 
     * @type {string}
     * @memberof FeesTimeData
     */
    totalFeeWei: string;
    /**
     * 
     * @type {string}
     * @memberof FeesTimeData
     */
    totalFee: string;
    /**
     * 
     * @type {string}
     * @memberof FeesTimeData
     */
    baseFeeWei: string;
    /**
     * 
     * @type {string}
     * @memberof FeesTimeData
     */
    baseFee: string;
    /**
     * 
     * @type {string}
     * @memberof FeesTimeData
     */
    dynamicFeeWei: string;
    /**
     * 
     * @type {string}
     * @memberof FeesTimeData
     */
    dynamicFee: string;
    /**
     * Count of actions for this fee statistic
     * @type {number}
     * @memberof FeesTimeData
     */
    count: number;
}

/**
 * Check if a given object implements the FeesTimeData interface.
 */
export function instanceOfFeesTimeData(value: object): value is FeesTimeData {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('when' in value) || value['when'] === undefined) return false;
    if ((!('totalFeeWei' in value) && !('total_fee_wei' in value)) || (value['totalFeeWei'] === undefined && value['total_fee_wei'] === undefined)) return false;
    if ((!('totalFee' in value) && !('total_fee' in value)) || (value['totalFee'] === undefined && value['total_fee'] === undefined)) return false;
    if ((!('baseFeeWei' in value) && !('base_fee_wei' in value)) || (value['baseFeeWei'] === undefined && value['base_fee_wei'] === undefined)) return false;
    if ((!('baseFee' in value) && !('base_fee' in value)) || (value['baseFee'] === undefined && value['base_fee'] === undefined)) return false;
    if ((!('dynamicFeeWei' in value) && !('dynamic_fee_wei' in value)) || (value['dynamicFeeWei'] === undefined && value['dynamic_fee_wei'] === undefined)) return false;
    if ((!('dynamicFee' in value) && !('dynamic_fee' in value)) || (value['dynamicFee'] === undefined && value['dynamic_fee'] === undefined)) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function FeesTimeDataFromJSON(json: any): FeesTimeData {
    return FeesTimeDataFromJSONTyped(json, false);
}

export function FeesTimeDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeesTimeData {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'when': (new Date(json['when'])),
        'totalFeeWei': json['total_fee_wei'],
        'totalFee': json['total_fee'],
        'baseFeeWei': json['base_fee_wei'],
        'baseFee': json['base_fee'],
        'dynamicFeeWei': json['dynamic_fee_wei'],
        'dynamicFee': json['dynamic_fee'],
        'count': json['count'],
    };
}

export function FeesTimeDataToJSON(json: any): FeesTimeData {
    return FeesTimeDataToJSONTyped(json, false);
}

export function FeesTimeDataToJSONTyped(value?: FeesTimeData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'when': value['when'].toISOString(),
        'total_fee_wei': value['totalFeeWei'],
        'total_fee': value['totalFee'],
        'base_fee_wei': value['baseFeeWei'],
        'base_fee': value['baseFee'],
        'dynamic_fee_wei': value['dynamicFeeWei'],
        'dynamic_fee': value['dynamicFee'],
        'count': value['count'],
    };
}

