// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeesTimeData } from './FeesTimeData';
import {
    FeesTimeDataFromJSON,
    FeesTimeDataFromJSONTyped,
    FeesTimeDataToJSON,
    FeesTimeDataToJSONTyped,
} from './FeesTimeData';
import type { Interval } from './Interval';
import {
    IntervalFromJSON,
    IntervalFromJSONTyped,
    IntervalToJSON,
    IntervalToJSONTyped,
} from './Interval';

/**
 * A fee aggregate. Fees keep their own response type rather than reusing the
 * count one, because a sum of money is not a count: it needs decimal and wei
 * side by side, and squeezing that into a generic count field loses precision.
 * 
 * @export
 * @interface FeesOut
 */
export interface FeesOut {
    /**
     * Number of actions the sums are taken over
     */
    count: number;
    /**
     * 
     */
    totalFee: string;
    /**
     * 
     */
    totalFeeWei: string;
    /**
     * 
     */
    baseFee: string;
    /**
     * 
     */
    baseFeeWei: string;
    /**
     * 
     */
    dynamicFee: string;
    /**
     * 
     */
    dynamicFeeWei: string;
    /**
     * 
     */
    interval?: Interval;
    /**
     * Fee sums grouped by the group_by dimension. Present with include=breakdown.
     */
    breakdown?: Array<FeesTimeData>;
    /**
     * Fee sums per time bucket. Present with include=series.
     */
    series?: Array<FeesTimeData>;
}



/**
 * Check if a given object implements the FeesOut interface.
 */
export function instanceOfFeesOut(value: object): value is FeesOut {
    if (!('count' in value) || value['count'] === undefined) return false;
    if ((!('totalFee' in (value as Record<string, any>)) && !('total_fee' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalFee'] === undefined && (value as Record<string, any>)['total_fee'] === undefined)) return false;
    if ((!('totalFeeWei' in (value as Record<string, any>)) && !('total_fee_wei' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalFeeWei'] === undefined && (value as Record<string, any>)['total_fee_wei'] === undefined)) return false;
    if ((!('baseFee' in (value as Record<string, any>)) && !('base_fee' in (value as Record<string, any>))) || ((value as Record<string, any>)['baseFee'] === undefined && (value as Record<string, any>)['base_fee'] === undefined)) return false;
    if ((!('baseFeeWei' in (value as Record<string, any>)) && !('base_fee_wei' in (value as Record<string, any>))) || ((value as Record<string, any>)['baseFeeWei'] === undefined && (value as Record<string, any>)['base_fee_wei'] === undefined)) return false;
    if ((!('dynamicFee' in (value as Record<string, any>)) && !('dynamic_fee' in (value as Record<string, any>))) || ((value as Record<string, any>)['dynamicFee'] === undefined && (value as Record<string, any>)['dynamic_fee'] === undefined)) return false;
    if ((!('dynamicFeeWei' in (value as Record<string, any>)) && !('dynamic_fee_wei' in (value as Record<string, any>))) || ((value as Record<string, any>)['dynamicFeeWei'] === undefined && (value as Record<string, any>)['dynamic_fee_wei'] === undefined)) return false;
    return true;
}

export function FeesOutFromJSON(json: any): FeesOut {
    return FeesOutFromJSONTyped(json, false);
}

export function FeesOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeesOut {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'totalFee': json['total_fee'],
        'totalFeeWei': json['total_fee_wei'],
        'baseFee': json['base_fee'],
        'baseFeeWei': json['base_fee_wei'],
        'dynamicFee': json['dynamic_fee'],
        'dynamicFeeWei': json['dynamic_fee_wei'],
        'interval': json['interval'] == null ? undefined : IntervalFromJSON(json['interval']),
        'breakdown': json['breakdown'] == null ? undefined : ((json['breakdown'] as Array<any>).map(FeesTimeDataFromJSON)),
        'series': json['series'] == null ? undefined : ((json['series'] as Array<any>).map(FeesTimeDataFromJSON)),
    };
}

export function FeesOutToJSON(json: any): FeesOut {
    return FeesOutToJSONTyped(json, false);
}

export function FeesOutToJSONTyped(value?: FeesOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'total_fee': value['totalFee'],
        'total_fee_wei': value['totalFeeWei'],
        'base_fee': value['baseFee'],
        'base_fee_wei': value['baseFeeWei'],
        'dynamic_fee': value['dynamicFee'],
        'dynamic_fee_wei': value['dynamicFeeWei'],
        'interval': IntervalToJSON(value['interval']),
        'breakdown': value['breakdown'] == null ? undefined : ((value['breakdown'] as Array<any>).map(FeesTimeDataToJSON)),
        'series': value['series'] == null ? undefined : ((value['series'] as Array<any>).map(FeesTimeDataToJSON)),
    };
}

