// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FolderType = {
    Avatars: 'avatars',
    Assets: 'assets',
    Support: 'support'
} as const;
export type FolderType = typeof FolderType[keyof typeof FolderType];


export function instanceOfFolderType(value: any): boolean {
    for (const key in FolderType) {
        if (Object.prototype.hasOwnProperty.call(FolderType, key)) {
            if (FolderType[key as keyof typeof FolderType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FolderTypeFromJSON(json: any): FolderType {
    return FolderTypeFromJSONTyped(json, false);
}

export function FolderTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderType {
    return json as FolderType;
}

export function FolderTypeToJSON(value?: FolderType | null): any {
    return value as any;
}

export function FolderTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): FolderType {
    return value as FolderType;
}

