// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneralError
 */
export interface GeneralError {
    /**
     * 
     */
    code: number;
    /**
     * 
     */
    message: string;
    /**
     * 
     */
    details?: object;
}

/**
 * Check if a given object implements the GeneralError interface.
 */
export function instanceOfGeneralError(value: object): value is GeneralError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GeneralErrorFromJSON(json: any): GeneralError {
    return GeneralErrorFromJSONTyped(json, false);
}

export function GeneralErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function GeneralErrorToJSON(json: any): GeneralError {
    return GeneralErrorToJSONTyped(json, false);
}

export function GeneralErrorToJSONTyped(value?: GeneralError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'details': value['details'],
    };
}

