// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ObjectFaces } from './ObjectFaces';
import {
    ObjectFacesFromJSON,
    ObjectFacesFromJSONTyped,
    ObjectFacesToJSON,
    ObjectFacesToJSONTyped,
} from './ObjectFaces';
import type { ObjectActions } from './ObjectActions';
import {
    ObjectActionsFromJSON,
    ObjectActionsFromJSONTyped,
    ObjectActionsToJSON,
    ObjectActionsToJSONTyped,
} from './ObjectActions';
import type { SmartObject } from './SmartObject';
import {
    SmartObjectFromJSON,
    SmartObjectFromJSONTyped,
    SmartObjectToJSON,
    SmartObjectToJSONTyped,
} from './SmartObject';

/**
 * 
 * @export
 * @interface ListSmartObjectsOut
 */
export interface ListSmartObjectsOut {
    /**
     * Array of objects.
     * @type {Array<SmartObject>}
     * @memberof ListSmartObjectsOut
     */
    objects: Array<SmartObject>;
    /**
     * Array of object faces.
     * @type {Array<ObjectFaces>}
     * @memberof ListSmartObjectsOut
     */
    faces?: Array<ObjectFaces>;
    /**
     * Array of object actions.
     * @type {Array<ObjectActions>}
     * @memberof ListSmartObjectsOut
     */
    actions?: Array<ObjectActions>;
    /**
     * Pagination token for the next set of results, if any.
     * @type {string}
     * @memberof ListSmartObjectsOut
     */
    next?: string;
}

/**
 * Check if a given object implements the ListSmartObjectsOut interface.
 */
export function instanceOfListSmartObjectsOut(value: object): value is ListSmartObjectsOut {
    if (!('objects' in value) || value['objects'] === undefined) return false;
    return true;
}

export function ListSmartObjectsOutFromJSON(json: any): ListSmartObjectsOut {
    return ListSmartObjectsOutFromJSONTyped(json, false);
}

export function ListSmartObjectsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSmartObjectsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'objects': ((json['objects'] as Array<any>).map(SmartObjectFromJSON)),
        'faces': json['faces'] == null ? undefined : ((json['faces'] as Array<any>).map(ObjectFacesFromJSON)),
        'actions': json['actions'] == null ? undefined : ((json['actions'] as Array<any>).map(ObjectActionsFromJSON)),
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function ListSmartObjectsOutToJSON(json: any): ListSmartObjectsOut {
    return ListSmartObjectsOutToJSONTyped(json, false);
}

export function ListSmartObjectsOutToJSONTyped(value?: ListSmartObjectsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'objects': ((value['objects'] as Array<any>).map(SmartObjectToJSON)),
        'faces': value['faces'] == null ? undefined : ((value['faces'] as Array<any>).map(ObjectFacesToJSON)),
        'actions': value['actions'] == null ? undefined : ((value['actions'] as Array<any>).map(ObjectActionsToJSON)),
        'next': value['next'],
    };
}

