// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicObjectAttribute } from './PublicObjectAttribute';
import {
    PublicObjectAttributeFromJSON,
    PublicObjectAttributeFromJSONTyped,
    PublicObjectAttributeToJSON,
    PublicObjectAttributeToJSONTyped,
} from './PublicObjectAttribute';

/**
 * 
 * @export
 * @interface ListPublicObjectAttributesOut
 */
export interface ListPublicObjectAttributesOut {
    /**
     * Public attributes in normalized key order.
     * @type {Array<PublicObjectAttribute>}
     * @memberof ListPublicObjectAttributesOut
     */
    attributes: Array<PublicObjectAttribute>;
    /**
     * Cursor for the next page, when more public attributes are available.
     * @type {string}
     * @memberof ListPublicObjectAttributesOut
     */
    next?: string;
}

/**
 * Check if a given object implements the ListPublicObjectAttributesOut interface.
 */
export function instanceOfListPublicObjectAttributesOut(value: object): value is ListPublicObjectAttributesOut {
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function ListPublicObjectAttributesOutFromJSON(json: any): ListPublicObjectAttributesOut {
    return ListPublicObjectAttributesOutFromJSONTyped(json, false);
}

export function ListPublicObjectAttributesOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPublicObjectAttributesOut {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': ((json['attributes'] as Array<any>).map(PublicObjectAttributeFromJSON)),
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function ListPublicObjectAttributesOutToJSON(json: any): ListPublicObjectAttributesOut {
    return ListPublicObjectAttributesOutToJSONTyped(json, false);
}

export function ListPublicObjectAttributesOutToJSONTyped(value?: ListPublicObjectAttributesOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': ((value['attributes'] as Array<any>).map(PublicObjectAttributeToJSON)),
        'next': value['next'],
    };
}

