// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemplateMessage } from './TemplateMessage';
import {
    TemplateMessageFromJSON,
    TemplateMessageFromJSONTyped,
    TemplateMessageToJSON,
    TemplateMessageToJSONTyped,
} from './TemplateMessage';

/**
 * 
 * @export
 * @interface ListNotificationTemplatesOut
 */
export interface ListNotificationTemplatesOut {
    /**
     * Array of template objects.
     * @type {Array<TemplateMessage>}
     * @memberof ListNotificationTemplatesOut
     */
    templates: Array<TemplateMessage>;
    /**
     * Pagination token for the next set of results, if any.
     * @type {string}
     * @memberof ListNotificationTemplatesOut
     */
    next?: string;
}

/**
 * Check if a given object implements the ListNotificationTemplatesOut interface.
 */
export function instanceOfListNotificationTemplatesOut(value: object): value is ListNotificationTemplatesOut {
    if (!('templates' in value) || value['templates'] === undefined) return false;
    return true;
}

export function ListNotificationTemplatesOutFromJSON(json: any): ListNotificationTemplatesOut {
    return ListNotificationTemplatesOutFromJSONTyped(json, false);
}

export function ListNotificationTemplatesOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListNotificationTemplatesOut {
    if (json == null) {
        return json;
    }
    return {
        
        'templates': ((json['templates'] as Array<any>).map(TemplateMessageFromJSON)),
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function ListNotificationTemplatesOutToJSON(json: any): ListNotificationTemplatesOut {
    return ListNotificationTemplatesOutToJSONTyped(json, false);
}

export function ListNotificationTemplatesOutToJSONTyped(value?: ListNotificationTemplatesOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templates': ((value['templates'] as Array<any>).map(TemplateMessageToJSON)),
        'next': value['next'],
    };
}

