// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookEvent } from './WebhookEvent';
import {
    WebhookEventFromJSON,
    WebhookEventFromJSONTyped,
    WebhookEventToJSON,
    WebhookEventToJSONTyped,
} from './WebhookEvent';

/**
 * 
 * @export
 * @interface ListWebhookEventsOut
 */
export interface ListWebhookEventsOut {
    /**
     * Array of webhook events showing delivery attempts and status.
     */
    events: Array<WebhookEvent>;
    /**
     * Pagination token for retrieving the next set of webhook events.
     */
    next?: string;
}

/**
 * Check if a given object implements the ListWebhookEventsOut interface.
 */
export function instanceOfListWebhookEventsOut(value: object): value is ListWebhookEventsOut {
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function ListWebhookEventsOutFromJSON(json: any): ListWebhookEventsOut {
    return ListWebhookEventsOutFromJSONTyped(json, false);
}

export function ListWebhookEventsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWebhookEventsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(WebhookEventFromJSON)),
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function ListWebhookEventsOutToJSON(json: any): ListWebhookEventsOut {
    return ListWebhookEventsOutToJSONTyped(json, false);
}

export function ListWebhookEventsOutToJSONTyped(value?: ListWebhookEventsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': ((value['events'] as Array<any>).map(WebhookEventToJSON)),
        'next': value['next'],
    };
}

