// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StorageAsset } from './StorageAsset';
import {
    StorageAssetFromJSON,
    StorageAssetFromJSONTyped,
    StorageAssetToJSON,
    StorageAssetToJSONTyped,
} from './StorageAsset';

/**
 * 
 * @export
 * @interface ListAssetsOut
 */
export interface ListAssetsOut {
    /**
     * 
     * @type {Array<StorageAsset>}
     * @memberof ListAssetsOut
     */
    assets: Array<StorageAsset>;
    /**
     * The next page token. If not present, there are no more pages.
     * @type {string}
     * @memberof ListAssetsOut
     */
    next?: string;
}

/**
 * Check if a given object implements the ListAssetsOut interface.
 */
export function instanceOfListAssetsOut(value: object): value is ListAssetsOut {
    if (!('assets' in value) || value['assets'] === undefined) return false;
    return true;
}

export function ListAssetsOutFromJSON(json: any): ListAssetsOut {
    return ListAssetsOutFromJSONTyped(json, false);
}

export function ListAssetsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAssetsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'assets': ((json['assets'] as Array<any>).map(StorageAssetFromJSON)),
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function ListAssetsOutToJSON(json: any): ListAssetsOut {
    return ListAssetsOutToJSONTyped(json, false);
}

export function ListAssetsOutToJSONTyped(value?: ListAssetsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assets': ((value['assets'] as Array<any>).map(StorageAssetToJSON)),
        'next': value['next'],
    };
}

