// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Member } from './Member';
import {
    MemberFromJSON,
    MemberFromJSONTyped,
    MemberToJSON,
    MemberToJSONTyped,
} from './Member';

/**
 * 
 * @export
 * @interface ListMembersOut
 */
export interface ListMembersOut {
    /**
     * Total number of members in the organization
     */
    count: number;
    /**
     * Pagination token for retrieving the next set of members
     */
    next?: string;
    /**
     * List of organization members returned in the response
     */
    members: Array<Member>;
}

/**
 * Check if a given object implements the ListMembersOut interface.
 */
export function instanceOfListMembersOut(value: object): value is ListMembersOut {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('members' in value) || value['members'] === undefined) return false;
    return true;
}

export function ListMembersOutFromJSON(json: any): ListMembersOut {
    return ListMembersOutFromJSONTyped(json, false);
}

export function ListMembersOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMembersOut {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'members': ((json['members'] as Array<any>).map(MemberFromJSON)),
    };
}

export function ListMembersOutToJSON(json: any): ListMembersOut {
    return ListMembersOutToJSONTyped(json, false);
}

export function ListMembersOutToJSONTyped(value?: ListMembersOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'members': ((value['members'] as Array<any>).map(MemberToJSON)),
    };
}

