// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Checkpoint } from './Checkpoint';
import {
    CheckpointFromJSON,
    CheckpointFromJSONTyped,
    CheckpointToJSON,
    CheckpointToJSONTyped,
} from './Checkpoint';

/**
 * 
 * @export
 * @interface ListCheckpointsOut
 */
export interface ListCheckpointsOut {
    /**
     * 
     * @type {Array<Checkpoint>}
     * @memberof ListCheckpointsOut
     */
    checkpoints: Array<Checkpoint>;
    /**
     * The next page token. This will be empty if there are no more pages.
     * @type {string}
     * @memberof ListCheckpointsOut
     */
    next?: string;
}

/**
 * Check if a given object implements the ListCheckpointsOut interface.
 */
export function instanceOfListCheckpointsOut(value: object): value is ListCheckpointsOut {
    if (!('checkpoints' in value) || value['checkpoints'] === undefined) return false;
    return true;
}

export function ListCheckpointsOutFromJSON(json: any): ListCheckpointsOut {
    return ListCheckpointsOutFromJSONTyped(json, false);
}

export function ListCheckpointsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCheckpointsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'checkpoints': ((json['checkpoints'] as Array<any>).map(CheckpointFromJSON)),
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function ListCheckpointsOutToJSON(json: any): ListCheckpointsOut {
    return ListCheckpointsOutToJSONTyped(json, false);
}

export function ListCheckpointsOutToJSONTyped(value?: ListCheckpointsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checkpoints': ((value['checkpoints'] as Array<any>).map(CheckpointToJSON)),
        'next': value['next'],
    };
}

