// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a geographical location with coordinates and geohash
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * Latitude coordinate in decimal degrees
     * @type {number}
     * @memberof Location
     */
    latitude: number;
    /**
     * Longitude coordinate in decimal degrees
     * @type {number}
     * @memberof Location
     */
    longitude: number;
    /**
     * Geohash string for efficient location-based queries
     * @type {string}
     * @memberof Location
     */
    geoHash: string;
}

/**
 * Check if a given object implements the Location interface.
 */
export function instanceOfLocation(value: object): value is Location {
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if ((!('geoHash' in value) && !('geo_hash' in value)) || (value['geoHash'] === undefined && value['geo_hash'] === undefined)) return false;
    return true;
}

export function LocationFromJSON(json: any): Location {
    return LocationFromJSONTyped(json, false);
}

export function LocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Location {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'geoHash': json['geo_hash'],
    };
}

export function LocationToJSON(json: any): Location {
    return LocationToJSONTyped(json, false);
}

export function LocationToJSONTyped(value?: Location | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'geo_hash': value['geoHash'],
    };
}

