// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginIn
 */
export interface LoginIn {
    /**
     * Optional organization ID for scoping the login request, if applicable
     */
    organizationId?: string;
    /**
     * User's email address for authentication, must be a valid email format
     */
    email?: string;
    /**
     * User's phone number in E.164 international format (e.g., +12125551234) as an alternative authentication identifier
     */
    phoneNumber?: string;
    /**
     * User's account password for standard authentication
     */
    password?: string;
    /**
     * One-time password or verification code for multi-factor authentication or passwordless login
     */
    otp?: string;
}

/**
 * Check if a given object implements the LoginIn interface.
 */
export function instanceOfLoginIn(value: object): value is LoginIn {
    return true;
}

export function LoginInFromJSON(json: any): LoginIn {
    return LoginInFromJSONTyped(json, false);
}

export function LoginInFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginIn {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'password': json['password'] == null ? undefined : json['password'],
        'otp': json['otp'] == null ? undefined : json['otp'],
    };
}

export function LoginInToJSON(json: any): LoginIn {
    return LoginInToJSONTyped(json, false);
}

export function LoginInToJSONTyped(value?: LoginIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_id': value['organizationId'],
        'email': value['email'],
        'phone_number': value['phoneNumber'],
        'password': value['password'],
        'otp': value['otp'],
    };
}

