// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Metadata } from './Metadata';
import {
    MetadataFromJSON,
    MetadataFromJSONTyped,
    MetadataToJSON,
    MetadataToJSONTyped,
} from './Metadata';

/**
 * Initial object state overrides applied at mint time
 * @export
 * @interface MintData
 */
export interface MintData {
    /**
     * Metadata information for the object
     */
    metadata?: Metadata;
    /**
     * Custom properties of the object
     */
    custom?: object;
    /**
     * System properties of the object
     */
    system?: object;
}

/**
 * Check if a given object implements the MintData interface.
 */
export function instanceOfMintData(value: object): value is MintData {
    return true;
}

export function MintDataFromJSON(json: any): MintData {
    return MintDataFromJSONTyped(json, false);
}

export function MintDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MintData {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : MetadataFromJSON(json['metadata']),
        'custom': json['custom'] == null ? undefined : json['custom'],
        'system': json['system'] == null ? undefined : json['system'],
    };
}

export function MintDataToJSON(json: any): MintData {
    return MintDataToJSONTyped(json, false);
}

export function MintDataToJSONTyped(value?: MintData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': MetadataToJSON(value['metadata']),
        'custom': value['custom'],
        'system': value['system'],
    };
}

