// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MintData } from './MintData';
import {
    MintDataFromJSON,
    MintDataFromJSONTyped,
    MintDataToJSON,
    MintDataToJSONTyped,
} from './MintData';

/**
 * 
 * @export
 * @interface Mint
 */
export interface Mint {
    /**
     * 
     */
    templateId: string;
    /**
     * 
     */
    num: number;
    /**
     * 
     */
    to?: string;
    /**
     * 
     */
    data?: MintData;
}

/**
 * Check if a given object implements the Mint interface.
 */
export function instanceOfMint(value: object): value is Mint {
    if ((!('templateId' in (value as Record<string, any>)) && !('template_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['templateId'] === undefined && (value as Record<string, any>)['template_id'] === undefined)) return false;
    if (!('num' in value) || value['num'] === undefined) return false;
    return true;
}

export function MintFromJSON(json: any): Mint {
    return MintFromJSONTyped(json, false);
}

export function MintFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mint {
    if (json == null) {
        return json;
    }
    return {
        
        'templateId': json['template_id'],
        'num': json['num'],
        'to': json['to'] == null ? undefined : json['to'],
        'data': json['data'] == null ? undefined : MintDataFromJSON(json['data']),
    };
}

export function MintToJSON(json: any): Mint {
    return MintToJSONTyped(json, false);
}

export function MintToJSONTyped(value?: Mint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'template_id': value['templateId'],
        'num': value['num'],
        'to': value['to'],
        'data': MintDataToJSON(value['data']),
    };
}

