// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NetworkInfo
 */
export interface NetworkInfo {
    /**
     * The current status of the network (e.g., "operational", "degraded", "maintenance").
     * @type {string}
     * @memberof NetworkInfo
     */
    status: string;
    /**
     * The current version of the network protocol or software.
     * @type {string}
     * @memberof NetworkInfo
     */
    version?: string;
    /**
     * The duration for which the network has been operational without interruption.
     * @type {string}
     * @memberof NetworkInfo
     */
    uptime?: string;
    /**
     * The timestamp of the last update to the network information.
     * @type {Date}
     * @memberof NetworkInfo
     */
    lastUpdated?: Date;
}

/**
 * Check if a given object implements the NetworkInfo interface.
 */
export function instanceOfNetworkInfo(value: object): value is NetworkInfo {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function NetworkInfoFromJSON(json: any): NetworkInfo {
    return NetworkInfoFromJSONTyped(json, false);
}

export function NetworkInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'version': json['version'] == null ? undefined : json['version'],
        'uptime': json['uptime'] == null ? undefined : json['uptime'],
        'lastUpdated': json['last_updated'] == null ? undefined : (new Date(json['last_updated'])),
    };
}

export function NetworkInfoToJSON(json: any): NetworkInfo {
    return NetworkInfoToJSONTyped(json, false);
}

export function NetworkInfoToJSONTyped(value?: NetworkInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'version': value['version'],
        'uptime': value['uptime'],
        'last_updated': value['lastUpdated'] == null ? value['lastUpdated'] : value['lastUpdated'].toISOString(),
    };
}

