// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NetworkConfig
 */
export interface NetworkConfig {
    /**
     * The L2 RPC endpoint URL for the network.
     * @type {string}
     * @memberof NetworkConfig
     */
    l2Rpc: string;
    /**
     * The L2 explorer URL for the network.
     * @type {string}
     * @memberof NetworkConfig
     */
    l2Explorer: string;
    /**
     * The L3 explorer URL for the network.
     * @type {string}
     * @memberof NetworkConfig
     */
    l3Explorer: string;
    /**
     * The staking contract address on the network.
     * @type {string}
     * @memberof NetworkConfig
     */
    staking: string;
    /**
     * The deposits contract address on the network.
     * @type {string}
     * @memberof NetworkConfig
     */
    deposits: string;
    /**
     * The batch registry contract address on the network.
     * @type {string}
     * @memberof NetworkConfig
     */
    batchRegistry: string;
    /**
     * The DAO contract address on the network.
     * @type {string}
     * @memberof NetworkConfig
     */
    dao: string;
    /**
     * The bridged NFTs contract address on the network.
     * @type {string}
     * @memberof NetworkConfig
     */
    bridgedNfts: string;
    /**
     * The fee dispatcher contract address authorized to send fees on the network.
     * @type {string}
     * @memberof NetworkConfig
     */
    feesDispatcher: string;
}

/**
 * Check if a given object implements the NetworkConfig interface.
 */
export function instanceOfNetworkConfig(value: object): value is NetworkConfig {
    if ((!('l2Rpc' in value) && !('l2_rpc' in value)) || (value['l2Rpc'] === undefined && value['l2_rpc'] === undefined)) return false;
    if ((!('l2Explorer' in value) && !('l2_explorer' in value)) || (value['l2Explorer'] === undefined && value['l2_explorer'] === undefined)) return false;
    if ((!('l3Explorer' in value) && !('l3_explorer' in value)) || (value['l3Explorer'] === undefined && value['l3_explorer'] === undefined)) return false;
    if (!('staking' in value) || value['staking'] === undefined) return false;
    if (!('deposits' in value) || value['deposits'] === undefined) return false;
    if ((!('batchRegistry' in value) && !('batch_registry' in value)) || (value['batchRegistry'] === undefined && value['batch_registry'] === undefined)) return false;
    if (!('dao' in value) || value['dao'] === undefined) return false;
    if ((!('bridgedNfts' in value) && !('bridged_nfts' in value)) || (value['bridgedNfts'] === undefined && value['bridged_nfts'] === undefined)) return false;
    if ((!('feesDispatcher' in value) && !('fees_dispatcher' in value)) || (value['feesDispatcher'] === undefined && value['fees_dispatcher'] === undefined)) return false;
    return true;
}

export function NetworkConfigFromJSON(json: any): NetworkConfig {
    return NetworkConfigFromJSONTyped(json, false);
}

export function NetworkConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'l2Rpc': json['l2_rpc'],
        'l2Explorer': json['l2_explorer'],
        'l3Explorer': json['l3_explorer'],
        'staking': json['staking'],
        'deposits': json['deposits'],
        'batchRegistry': json['batch_registry'],
        'dao': json['dao'],
        'bridgedNfts': json['bridged_nfts'],
        'feesDispatcher': json['fees_dispatcher'],
    };
}

export function NetworkConfigToJSON(json: any): NetworkConfig {
    return NetworkConfigToJSONTyped(json, false);
}

export function NetworkConfigToJSONTyped(value?: NetworkConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'l2_rpc': value['l2Rpc'],
        'l2_explorer': value['l2Explorer'],
        'l3_explorer': value['l3Explorer'],
        'staking': value['staking'],
        'deposits': value['deposits'],
        'batch_registry': value['batchRegistry'],
        'dao': value['dao'],
        'bridged_nfts': value['bridgedNfts'],
        'fees_dispatcher': value['feesDispatcher'],
    };
}

