// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NetworkFees
 */
export interface NetworkFees {
    /**
     * Current price of the network token.
     */
    tokenPrice: string;
    /**
     * Base fee for actions in the eBus system.
     */
    baseFee: string;
    /**
     * Base fee for ERC20 token actions in the eBus system.
     */
    baseFeeWei: string;
    /**
     * Dynamic fee component based on current network conditions.
     */
    dynamicFee: string;
    /**
     * Dynamic fee component for ERC20 token actions based on current network conditions.
     */
    dynamicFeeWei: string;
    /**
     * Total fee calculated as the sum of base and dynamic fees.
     */
    totalFee: string;
    /**
     * Total fee for ERC20 token actions calculated as the sum of base and dynamic fees
     */
    totalFeeWei: string;
}

/**
 * Check if a given object implements the NetworkFees interface.
 */
export function instanceOfNetworkFees(value: object): value is NetworkFees {
    if ((!('tokenPrice' in (value as Record<string, any>)) && !('token_price' in (value as Record<string, any>))) || ((value as Record<string, any>)['tokenPrice'] === undefined && (value as Record<string, any>)['token_price'] === undefined)) return false;
    if ((!('baseFee' in (value as Record<string, any>)) && !('base_fee' in (value as Record<string, any>))) || ((value as Record<string, any>)['baseFee'] === undefined && (value as Record<string, any>)['base_fee'] === undefined)) return false;
    if ((!('baseFeeWei' in (value as Record<string, any>)) && !('base_fee_wei' in (value as Record<string, any>))) || ((value as Record<string, any>)['baseFeeWei'] === undefined && (value as Record<string, any>)['base_fee_wei'] === undefined)) return false;
    if ((!('dynamicFee' in (value as Record<string, any>)) && !('dynamic_fee' in (value as Record<string, any>))) || ((value as Record<string, any>)['dynamicFee'] === undefined && (value as Record<string, any>)['dynamic_fee'] === undefined)) return false;
    if ((!('dynamicFeeWei' in (value as Record<string, any>)) && !('dynamic_fee_wei' in (value as Record<string, any>))) || ((value as Record<string, any>)['dynamicFeeWei'] === undefined && (value as Record<string, any>)['dynamic_fee_wei'] === undefined)) return false;
    if ((!('totalFee' in (value as Record<string, any>)) && !('total_fee' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalFee'] === undefined && (value as Record<string, any>)['total_fee'] === undefined)) return false;
    if ((!('totalFeeWei' in (value as Record<string, any>)) && !('total_fee_wei' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalFeeWei'] === undefined && (value as Record<string, any>)['total_fee_wei'] === undefined)) return false;
    return true;
}

export function NetworkFeesFromJSON(json: any): NetworkFees {
    return NetworkFeesFromJSONTyped(json, false);
}

export function NetworkFeesFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkFees {
    if (json == null) {
        return json;
    }
    return {
        
        'tokenPrice': json['token_price'],
        'baseFee': json['base_fee'],
        'baseFeeWei': json['base_fee_wei'],
        'dynamicFee': json['dynamic_fee'],
        'dynamicFeeWei': json['dynamic_fee_wei'],
        'totalFee': json['total_fee'],
        'totalFeeWei': json['total_fee_wei'],
    };
}

export function NetworkFeesToJSON(json: any): NetworkFees {
    return NetworkFeesToJSONTyped(json, false);
}

export function NetworkFeesToJSONTyped(value?: NetworkFees | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token_price': value['tokenPrice'],
        'base_fee': value['baseFee'],
        'base_fee_wei': value['baseFeeWei'],
        'dynamic_fee': value['dynamicFee'],
        'dynamic_fee_wei': value['dynamicFeeWei'],
        'total_fee': value['totalFee'],
        'total_fee_wei': value['totalFeeWei'],
    };
}

