// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ObjectDisplay } from './ObjectDisplay';
import {
    ObjectDisplayFromJSON,
    ObjectDisplayFromJSONTyped,
    ObjectDisplayToJSON,
    ObjectDisplayToJSONTyped,
} from './ObjectDisplay';
import type { SmartObject } from './SmartObject';
import {
    SmartObjectFromJSON,
    SmartObjectFromJSONTyped,
    SmartObjectToJSON,
    SmartObjectToJSONTyped,
} from './SmartObject';

/**
 * Smart-object data together with its optional resolved display descriptor.
 * @export
 * @interface ObjectView
 */
export interface ObjectView {
    /**
     * 
     * @type {SmartObject}
     * @memberof ObjectView
     */
    object: SmartObject;
    /**
     * 
     * @type {ObjectDisplay}
     * @memberof ObjectView
     */
    display?: ObjectDisplay;
}

/**
 * Check if a given object implements the ObjectView interface.
 */
export function instanceOfObjectView(value: object): value is ObjectView {
    if (!('object' in value) || value['object'] === undefined) return false;
    return true;
}

export function ObjectViewFromJSON(json: any): ObjectView {
    return ObjectViewFromJSONTyped(json, false);
}

export function ObjectViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectView {
    if (json == null) {
        return json;
    }
    return {
        
        'object': SmartObjectFromJSON(json['object']),
        'display': json['display'] == null ? undefined : ObjectDisplayFromJSON(json['display']),
    };
}

export function ObjectViewToJSON(json: any): ObjectView {
    return ObjectViewToJSONTyped(json, false);
}

export function ObjectViewToJSONTyped(value?: ObjectView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': SmartObjectToJSON(value['object']),
        'display': ObjectDisplayToJSON(value['display']),
    };
}

