// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectsStatsOut
 */
export interface ObjectsStatsOut {
    /**
     * Total number of objects
     * @type {number}
     * @memberof ObjectsStatsOut
     */
    total: number;
    /**
     * Objects broken down by template
     * @type {{ [key: string]: number; }}
     * @memberof ObjectsStatsOut
     */
    byTemplate: { [key: string]: number; };
}

/**
 * Check if a given object implements the ObjectsStatsOut interface.
 */
export function instanceOfObjectsStatsOut(value: object): value is ObjectsStatsOut {
    if (!('total' in value) || value['total'] === undefined) return false;
    if ((!('byTemplate' in value) && !('by_template' in value)) || (value['byTemplate'] === undefined && value['by_template'] === undefined)) return false;
    return true;
}

export function ObjectsStatsOutFromJSON(json: any): ObjectsStatsOut {
    return ObjectsStatsOutFromJSONTyped(json, false);
}

export function ObjectsStatsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectsStatsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'byTemplate': json['by_template'],
    };
}

export function ObjectsStatsOutToJSON(json: any): ObjectsStatsOut {
    return ObjectsStatsOutToJSONTyped(json, false);
}

export function ObjectsStatsOutToJSONTyped(value?: ObjectsStatsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'by_template': value['byTemplate'],
    };
}

