// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Organization } from './Organization';
import {
    OrganizationFromJSON,
    OrganizationFromJSONTyped,
    OrganizationToJSON,
    OrganizationToJSONTyped,
} from './Organization';

/**
 * 
 * @export
 * @interface OrganizationSwitchOut
 */
export interface OrganizationSwitchOut {
    /**
     * JSON Web Token (JWT) for authenticating subsequent API requests in the context of the switched organization
     */
    accessToken: string;
    /**
     * 
     */
    organization: Organization;
}

/**
 * Check if a given object implements the OrganizationSwitchOut interface.
 */
export function instanceOfOrganizationSwitchOut(value: object): value is OrganizationSwitchOut {
    if ((!('accessToken' in (value as Record<string, any>)) && !('access_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['accessToken'] === undefined && (value as Record<string, any>)['access_token'] === undefined)) return false;
    if (!('organization' in value) || value['organization'] === undefined) return false;
    return true;
}

export function OrganizationSwitchOutFromJSON(json: any): OrganizationSwitchOut {
    return OrganizationSwitchOutFromJSONTyped(json, false);
}

export function OrganizationSwitchOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationSwitchOut {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'organization': OrganizationFromJSON(json['organization']),
    };
}

export function OrganizationSwitchOutToJSON(json: any): OrganizationSwitchOut {
    return OrganizationSwitchOutToJSONTyped(json, false);
}

export function OrganizationSwitchOutToJSONTyped(value?: OrganizationSwitchOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'organization': OrganizationToJSON(value['organization']),
    };
}

