// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
    RoleToJSONTyped,
} from './Role';
import type { Asset } from './Asset';
import {
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
    AssetToJSONTyped,
} from './Asset';
import type { Member } from './Member';
import {
    MemberFromJSON,
    MemberFromJSONTyped,
    MemberToJSON,
    MemberToJSONTyped,
} from './Member';

/**
 * Organization entity representing a business or group structure within the platform
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * Unique identifier for the organization
     * @type {string}
     * @memberof Organization
     */
    id: string;
    /**
     * Fully Qualified Domain Name associated with the organization
     * @type {string}
     * @memberof Organization
     */
    fqdn: string;
    /**
     * Unique identifier for the organization's owner
     * @type {string}
     * @memberof Organization
     */
    ownerId?: string;
    /**
     * Human-readable name of the organization
     * @type {string}
     * @memberof Organization
     */
    name: string;
    /**
     * Organization's logo or profile image
     * @type {Asset}
     * @memberof Organization
     */
    image?: Asset;
    /**
     * List of members belonging to this organization
     * @type {Array<Member>}
     * @memberof Organization
     */
    members?: Array<Member>;
    /**
     * List of roles defined within this organization
     * @type {Array<Role>}
     * @memberof Organization
     */
    roles?: Array<Role>;
    /**
     * Optional detailed description of the organization's purpose and activities
     * @type {string}
     * @memberof Organization
     */
    description?: string;
    /**
     * Timestamp when the organization was created
     * @type {Date}
     * @memberof Organization
     */
    whenCreated: Date;
    /**
     * Timestamp when the organization was last modified
     * @type {Date}
     * @memberof Organization
     */
    whenModified: Date;
}

/**
 * Check if a given object implements the Organization interface.
 */
export function instanceOfOrganization(value: object): value is Organization {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('fqdn' in value) || value['fqdn'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('whenCreated' in value) && !('when_created' in value)) || (value['whenCreated'] === undefined && value['when_created'] === undefined)) return false;
    if ((!('whenModified' in value) && !('when_modified' in value)) || (value['whenModified'] === undefined && value['when_modified'] === undefined)) return false;
    return true;
}

export function OrganizationFromJSON(json: any): Organization {
    return OrganizationFromJSONTyped(json, false);
}

export function OrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Organization {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'fqdn': json['fqdn'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'name': json['name'],
        'image': json['image'] == null ? undefined : AssetFromJSON(json['image']),
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(MemberFromJSON)),
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(RoleFromJSON)),
        'description': json['description'] == null ? undefined : json['description'],
        'whenCreated': (new Date(json['when_created'])),
        'whenModified': (new Date(json['when_modified'])),
    };
}

export function OrganizationToJSON(json: any): Organization {
    return OrganizationToJSONTyped(json, false);
}

export function OrganizationToJSONTyped(value?: Organization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fqdn': value['fqdn'],
        'owner_id': value['ownerId'],
        'name': value['name'],
        'image': AssetToJSON(value['image']),
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(MemberToJSON)),
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(RoleToJSON)),
        'description': value['description'],
        'when_created': value['whenCreated'].toISOString(),
        'when_modified': value['whenModified'].toISOString(),
    };
}

