// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AuthenticatorAssertionResponse from the browser (authentication ceremony).
 * @export
 * @interface PasskeyAssertionResponse
 */
export interface PasskeyAssertionResponse {
    /**
     * base64url-encoded clientDataJSON. The server verifies:
     * type == "webauthn.get", origin matches, challenge matches.
     * 
     */
    clientDataJSON: string;
    /**
     * base64url-encoded authenticatorData. The server verifies:
     * rpIdHash == sha256(rpId), UP flag set, UV flag set.
     * 
     */
    authenticatorData: string;
    /**
     * base64url-encoded DER-encoded P-256 (ES256) signature over
     * sha256(authenticatorData || sha256(clientDataJSON)).
     * 
     */
    signature: string;
    /**
     * base64url-encoded user handle stored by the authenticator (may be absent
     * for non-discoverable credentials).
     * 
     */
    userHandle?: string;
}

/**
 * Check if a given object implements the PasskeyAssertionResponse interface.
 */
export function instanceOfPasskeyAssertionResponse(value: object): value is PasskeyAssertionResponse {
    if (!('clientDataJSON' in value) || value['clientDataJSON'] === undefined) return false;
    if (!('authenticatorData' in value) || value['authenticatorData'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function PasskeyAssertionResponseFromJSON(json: any): PasskeyAssertionResponse {
    return PasskeyAssertionResponseFromJSONTyped(json, false);
}

export function PasskeyAssertionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasskeyAssertionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'clientDataJSON': json['clientDataJSON'],
        'authenticatorData': json['authenticatorData'],
        'signature': json['signature'],
        'userHandle': json['userHandle'] == null ? undefined : json['userHandle'],
    };
}

export function PasskeyAssertionResponseToJSON(json: any): PasskeyAssertionResponse {
    return PasskeyAssertionResponseToJSONTyped(json, false);
}

export function PasskeyAssertionResponseToJSONTyped(value?: PasskeyAssertionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientDataJSON': value['clientDataJSON'],
        'authenticatorData': value['authenticatorData'],
        'signature': value['signature'],
        'userHandle': value['userHandle'],
    };
}

