// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Acceptable credential type and algorithm pair.
 * @export
 * @interface PasskeyPubKeyCredParam
 */
export interface PasskeyPubKeyCredParam {
    /**
     * 
     * @type {PasskeyPubKeyCredParamTypeEnum}
     * @memberof PasskeyPubKeyCredParam
     */
    type: PasskeyPubKeyCredParamTypeEnum;
    /**
     * COSE algorithm identifier.
     * -7 = ES256 (P-256 / WebAuthn passkey, the only supported value).
     * 
     * @type {number}
     * @memberof PasskeyPubKeyCredParam
     */
    alg: number;
}


/**
 * @export
 */
export const PasskeyPubKeyCredParamTypeEnum = {
    PublicKey: 'public-key'
} as const;
export type PasskeyPubKeyCredParamTypeEnum = typeof PasskeyPubKeyCredParamTypeEnum[keyof typeof PasskeyPubKeyCredParamTypeEnum];


/**
 * Check if a given object implements the PasskeyPubKeyCredParam interface.
 */
export function instanceOfPasskeyPubKeyCredParam(value: object): value is PasskeyPubKeyCredParam {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'public-key') return false;
    
    if (!('alg' in value) || value['alg'] === undefined) return false;
    return true;
}

export function PasskeyPubKeyCredParamFromJSON(json: any): PasskeyPubKeyCredParam {
    return PasskeyPubKeyCredParamFromJSONTyped(json, false);
}

export function PasskeyPubKeyCredParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasskeyPubKeyCredParam {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'alg': json['alg'],
    };
}

export function PasskeyPubKeyCredParamToJSON(json: any): PasskeyPubKeyCredParam {
    return PasskeyPubKeyCredParamToJSONTyped(json, false);
}

export function PasskeyPubKeyCredParamToJSONTyped(value?: PasskeyPubKeyCredParam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'alg': value['alg'],
    };
}

