// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PasskeyPubKeyCredParam } from './PasskeyPubKeyCredParam';
import {
    PasskeyPubKeyCredParamFromJSON,
    PasskeyPubKeyCredParamFromJSONTyped,
    PasskeyPubKeyCredParamToJSON,
    PasskeyPubKeyCredParamToJSONTyped,
} from './PasskeyPubKeyCredParam';
import type { PasskeyAuthenticatorSelection } from './PasskeyAuthenticatorSelection';
import {
    PasskeyAuthenticatorSelectionFromJSON,
    PasskeyAuthenticatorSelectionFromJSONTyped,
    PasskeyAuthenticatorSelectionToJSON,
    PasskeyAuthenticatorSelectionToJSONTyped,
} from './PasskeyAuthenticatorSelection';
import type { PasskeyRp } from './PasskeyRp';
import {
    PasskeyRpFromJSON,
    PasskeyRpFromJSONTyped,
    PasskeyRpToJSON,
    PasskeyRpToJSONTyped,
} from './PasskeyRp';
import type { PasskeyUser } from './PasskeyUser';
import {
    PasskeyUserFromJSON,
    PasskeyUserFromJSONTyped,
    PasskeyUserToJSON,
    PasskeyUserToJSONTyped,
} from './PasskeyUser';

/**
 * WebAuthn PublicKeyCredentialCreationOptions. Pass the response body directly to
 * navigator.credentials.create({ publicKey: response }).
 * 
 * @export
 * @interface PasskeyRegisterOptionsOut
 */
export interface PasskeyRegisterOptionsOut {
    /**
     * base64url-encoded 32-byte random challenge (single-use, 60 s TTL).
     */
    challenge: string;
    /**
     * 
     */
    rp: PasskeyRp;
    /**
     * 
     */
    user: PasskeyUser;
    /**
     * Ordered list of acceptable credential types and algorithms.
     */
    pubKeyCredParams: Array<PasskeyPubKeyCredParam>;
    /**
     * 
     */
    authenticatorSelection?: PasskeyAuthenticatorSelection;
    /**
     * Ceremony timeout in milliseconds (browser hint, not enforced server-side).
     */
    timeout?: number;
}

/**
 * Check if a given object implements the PasskeyRegisterOptionsOut interface.
 */
export function instanceOfPasskeyRegisterOptionsOut(value: object): value is PasskeyRegisterOptionsOut {
    if (!('challenge' in value) || value['challenge'] === undefined) return false;
    if (!('rp' in value) || value['rp'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('pubKeyCredParams' in value) || value['pubKeyCredParams'] === undefined) return false;
    return true;
}

export function PasskeyRegisterOptionsOutFromJSON(json: any): PasskeyRegisterOptionsOut {
    return PasskeyRegisterOptionsOutFromJSONTyped(json, false);
}

export function PasskeyRegisterOptionsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasskeyRegisterOptionsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'challenge': json['challenge'],
        'rp': PasskeyRpFromJSON(json['rp']),
        'user': PasskeyUserFromJSON(json['user']),
        'pubKeyCredParams': ((json['pubKeyCredParams'] as Array<any>).map(PasskeyPubKeyCredParamFromJSON)),
        'authenticatorSelection': json['authenticatorSelection'] == null ? undefined : PasskeyAuthenticatorSelectionFromJSON(json['authenticatorSelection']),
        'timeout': json['timeout'] == null ? undefined : json['timeout'],
    };
}

export function PasskeyRegisterOptionsOutToJSON(json: any): PasskeyRegisterOptionsOut {
    return PasskeyRegisterOptionsOutToJSONTyped(json, false);
}

export function PasskeyRegisterOptionsOutToJSONTyped(value?: PasskeyRegisterOptionsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'challenge': value['challenge'],
        'rp': PasskeyRpToJSON(value['rp']),
        'user': PasskeyUserToJSON(value['user']),
        'pubKeyCredParams': ((value['pubKeyCredParams'] as Array<any>).map(PasskeyPubKeyCredParamToJSON)),
        'authenticatorSelection': PasskeyAuthenticatorSelectionToJSON(value['authenticatorSelection']),
        'timeout': value['timeout'],
    };
}

