// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PasskeyAssertionResponse } from './PasskeyAssertionResponse';
import {
    PasskeyAssertionResponseFromJSON,
    PasskeyAssertionResponseFromJSONTyped,
    PasskeyAssertionResponseToJSON,
    PasskeyAssertionResponseToJSONTyped,
} from './PasskeyAssertionResponse';

/**
 * Browser's PublicKeyCredential JSON produced by navigator.credentials.get().
 * Submit the credential object as-is.
 * 
 * @export
 * @interface PasskeyLoginVerifyIn
 */
export interface PasskeyLoginVerifyIn {
    /**
     * base64url-encoded credential ID returned by the browser.
     */
    id: string;
    /**
     * base64url-encoded raw credential ID (identical to id).
     */
    rawId: string;
    /**
     * 
     */
    response: PasskeyAssertionResponse;
    /**
     * Always "public-key".
     */
    type: PasskeyLoginVerifyInTypeEnum;
}


/**
 * @export
 */
export const PasskeyLoginVerifyInTypeEnum = {
    PublicKey: 'public-key',
} as const;
export type PasskeyLoginVerifyInTypeEnum = typeof PasskeyLoginVerifyInTypeEnum[keyof typeof PasskeyLoginVerifyInTypeEnum];


/**
 * Check if a given object implements the PasskeyLoginVerifyIn interface.
 */
export function instanceOfPasskeyLoginVerifyIn(value: object): value is PasskeyLoginVerifyIn {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('rawId' in value) || value['rawId'] === undefined) return false;
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'public-key') return false;
    
    return true;
}

export function PasskeyLoginVerifyInFromJSON(json: any): PasskeyLoginVerifyIn {
    return PasskeyLoginVerifyInFromJSONTyped(json, false);
}

export function PasskeyLoginVerifyInFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasskeyLoginVerifyIn {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'rawId': json['rawId'],
        'response': PasskeyAssertionResponseFromJSON(json['response']),
        'type': json['type'],
    };
}

export function PasskeyLoginVerifyInToJSON(json: any): PasskeyLoginVerifyIn {
    return PasskeyLoginVerifyInToJSONTyped(json, false);
}

export function PasskeyLoginVerifyInToJSONTyped(value?: PasskeyLoginVerifyIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'rawId': value['rawId'],
        'response': PasskeyAssertionResponseToJSON(value['response']),
        'type': value['type'],
    };
}

