// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Credential descriptor restricting which credentials may respond.
 * @export
 * @interface PasskeyAllowCredential
 */
export interface PasskeyAllowCredential {
    /**
     * base64url-encoded credential ID.
     * @type {string}
     * @memberof PasskeyAllowCredential
     */
    id: string;
    /**
     * 
     * @type {PasskeyAllowCredentialTypeEnum}
     * @memberof PasskeyAllowCredential
     */
    type: PasskeyAllowCredentialTypeEnum;
}


/**
 * @export
 */
export const PasskeyAllowCredentialTypeEnum = {
    PublicKey: 'public-key'
} as const;
export type PasskeyAllowCredentialTypeEnum = typeof PasskeyAllowCredentialTypeEnum[keyof typeof PasskeyAllowCredentialTypeEnum];


/**
 * Check if a given object implements the PasskeyAllowCredential interface.
 */
export function instanceOfPasskeyAllowCredential(value: object): value is PasskeyAllowCredential {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'public-key') return false;
    
    return true;
}

export function PasskeyAllowCredentialFromJSON(json: any): PasskeyAllowCredential {
    return PasskeyAllowCredentialFromJSONTyped(json, false);
}

export function PasskeyAllowCredentialFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasskeyAllowCredential {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function PasskeyAllowCredentialToJSON(json: any): PasskeyAllowCredential {
    return PasskeyAllowCredentialToJSONTyped(json, false);
}

export function PasskeyAllowCredentialToJSONTyped(value?: PasskeyAllowCredential | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

