// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Relying party descriptor.
 * @export
 * @interface PasskeyRp
 */
export interface PasskeyRp {
    /**
     * Relying party ID (must match the origin's effective domain).
     */
    id: string;
    /**
     * Human-readable relying party name shown in browser UI.
     */
    name: string;
}

/**
 * Check if a given object implements the PasskeyRp interface.
 */
export function instanceOfPasskeyRp(value: object): value is PasskeyRp {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PasskeyRpFromJSON(json: any): PasskeyRp {
    return PasskeyRpFromJSONTyped(json, false);
}

export function PasskeyRpFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasskeyRp {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function PasskeyRpToJSON(json: any): PasskeyRp {
    return PasskeyRpToJSONTyped(json, false);
}

export function PasskeyRpToJSONTyped(value?: PasskeyRp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

