// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Metadata } from './Metadata';
import {
    MetadataFromJSON,
    MetadataFromJSONTyped,
    MetadataToJSON,
    MetadataToJSONTyped,
} from './Metadata';

/**
 * 
 * @export
 * @interface PublicTemplateObject
 */
export interface PublicTemplateObject {
    /**
     * 
     * @type {Metadata}
     * @memberof PublicTemplateObject
     */
    metadata: Metadata;
    /**
     * Custom properties of the object
     * @type {object}
     * @memberof PublicTemplateObject
     */
    custom?: object;
}

/**
 * Check if a given object implements the PublicTemplateObject interface.
 */
export function instanceOfPublicTemplateObject(value: object): value is PublicTemplateObject {
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function PublicTemplateObjectFromJSON(json: any): PublicTemplateObject {
    return PublicTemplateObjectFromJSONTyped(json, false);
}

export function PublicTemplateObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicTemplateObject {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': MetadataFromJSON(json['metadata']),
        'custom': json['custom'] == null ? undefined : json['custom'],
    };
}

export function PublicTemplateObjectToJSON(json: any): PublicTemplateObject {
    return PublicTemplateObjectToJSONTyped(json, false);
}

export function PublicTemplateObjectToJSONTyped(value?: PublicTemplateObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': MetadataToJSON(value['metadata']),
        'custom': value['custom'],
    };
}

