// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributeContentType } from './AttributeContentType';
import {
    AttributeContentTypeFromJSON,
    AttributeContentTypeFromJSONTyped,
    AttributeContentTypeToJSON,
    AttributeContentTypeToJSONTyped,
} from './AttributeContentType';

/**
 * An owner-managed object attribute explicitly exposed to public consumers.
 * @export
 * @interface PublicObjectAttribute
 */
export interface PublicObjectAttribute {
    /**
     * Normalized, case-insensitive attribute key.
     */
    key: string;
    /**
     * Current arbitrary JSON value.
     */
    value: any | null;
    /**
     * Optional category used to group or classify the attribute.
     */
    category?: string;
    /**
     * Optional format of the attribute value.
     */
    contentType?: AttributeContentType;
}



/**
 * Check if a given object implements the PublicObjectAttribute interface.
 */
export function instanceOfPublicObjectAttribute(value: object): value is PublicObjectAttribute {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function PublicObjectAttributeFromJSON(json: any): PublicObjectAttribute {
    return PublicObjectAttributeFromJSONTyped(json, false);
}

export function PublicObjectAttributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicObjectAttribute {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
        'category': json['category'] == null ? undefined : json['category'],
        'contentType': json['content_type'] == null ? undefined : AttributeContentTypeFromJSON(json['content_type']),
    };
}

export function PublicObjectAttributeToJSON(json: any): PublicObjectAttribute {
    return PublicObjectAttributeToJSONTyped(json, false);
}

export function PublicObjectAttributeToJSONTyped(value?: PublicObjectAttribute | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
        'category': value['category'],
        'content_type': AttributeContentTypeToJSON(value['contentType']),
    };
}

