// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicSmartObjectMetadataAttributesInner } from './PublicSmartObjectMetadataAttributesInner';
import {
    PublicSmartObjectMetadataAttributesInnerFromJSON,
    PublicSmartObjectMetadataAttributesInnerFromJSONTyped,
    PublicSmartObjectMetadataAttributesInnerToJSON,
    PublicSmartObjectMetadataAttributesInnerToJSONTyped,
} from './PublicSmartObjectMetadataAttributesInner';

/**
 * Metadata information for a public smart object
 * @export
 * @interface PublicSmartObjectMetadata
 */
export interface PublicSmartObjectMetadata {
    /**
     * Name of the smart object
     * @type {string}
     * @memberof PublicSmartObjectMetadata
     */
    name: string;
    /**
     * Description of the smart object
     * @type {string}
     * @memberof PublicSmartObjectMetadata
     */
    description: string;
    /**
     * URL to the image representing the smart object
     * @type {string}
     * @memberof PublicSmartObjectMetadata
     */
    image: string;
    /**
     * List of attributes associated with the smart object
     * @type {Array<PublicSmartObjectMetadataAttributesInner>}
     * @memberof PublicSmartObjectMetadata
     */
    attributes: Array<PublicSmartObjectMetadataAttributesInner>;
    /**
     * External URL related to the smart object
     * @type {string}
     * @memberof PublicSmartObjectMetadata
     */
    externalUrl: string;
}

/**
 * Check if a given object implements the PublicSmartObjectMetadata interface.
 */
export function instanceOfPublicSmartObjectMetadata(value: object): value is PublicSmartObjectMetadata {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if ((!('externalUrl' in value) && !('external_url' in value)) || (value['externalUrl'] === undefined && value['external_url'] === undefined)) return false;
    return true;
}

export function PublicSmartObjectMetadataFromJSON(json: any): PublicSmartObjectMetadata {
    return PublicSmartObjectMetadataFromJSONTyped(json, false);
}

export function PublicSmartObjectMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicSmartObjectMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'image': json['image'],
        'attributes': ((json['attributes'] as Array<any>).map(PublicSmartObjectMetadataAttributesInnerFromJSON)),
        'externalUrl': json['external_url'],
    };
}

export function PublicSmartObjectMetadataToJSON(json: any): PublicSmartObjectMetadata {
    return PublicSmartObjectMetadataToJSONTyped(json, false);
}

export function PublicSmartObjectMetadataToJSONTyped(value?: PublicSmartObjectMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'image': value['image'],
        'attributes': ((value['attributes'] as Array<any>).map(PublicSmartObjectMetadataAttributesInnerToJSON)),
        'external_url': value['externalUrl'],
    };
}

