// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestOTPCodeIn
 */
export interface RequestOTPCodeIn {
    /**
     * Email address to receive the one-time password
     */
    email?: string;
    /**
     * Phone number in E.164 format to receive the one-time password
     */
    phoneNumber?: string;
    /**
     * Organization ID is requested (if applicable)
     */
    organizationId?: string;
}

/**
 * Check if a given object implements the RequestOTPCodeIn interface.
 */
export function instanceOfRequestOTPCodeIn(value: object): value is RequestOTPCodeIn {
    return true;
}

export function RequestOTPCodeInFromJSON(json: any): RequestOTPCodeIn {
    return RequestOTPCodeInFromJSONTyped(json, false);
}

export function RequestOTPCodeInFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestOTPCodeIn {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
    };
}

export function RequestOTPCodeInToJSON(json: any): RequestOTPCodeIn {
    return RequestOTPCodeInToJSONTyped(json, false);
}

export function RequestOTPCodeInToJSONTyped(value?: RequestOTPCodeIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'phone_number': value['phoneNumber'],
        'organization_id': value['organizationId'],
    };
}

