// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Permission } from './Permission';
import {
    PermissionFromJSON,
    PermissionFromJSONTyped,
    PermissionToJSON,
    PermissionToJSONTyped,
} from './Permission';

/**
 * 
 * @export
 * @interface RoleCreate
 */
export interface RoleCreate {
    /**
     * Name for the new role
     */
    name: string;
    /**
     * Optional description explaining the purpose of the role
     */
    description?: string;
    /**
     * List of permissions to be assigned to the role
     */
    permissions: Array<Permission>;
}

/**
 * Check if a given object implements the RoleCreate interface.
 */
export function instanceOfRoleCreate(value: object): value is RoleCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function RoleCreateFromJSON(json: any): RoleCreate {
    return RoleCreateFromJSONTyped(json, false);
}

export function RoleCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'permissions': ((json['permissions'] as Array<any>).map(PermissionFromJSON)),
    };
}

export function RoleCreateToJSON(json: any): RoleCreate {
    return RoleCreateToJSONTyped(json, false);
}

export function RoleCreateToJSONTyped(value?: RoleCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'permissions': ((value['permissions'] as Array<any>).map(PermissionToJSON)),
    };
}

