// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributeInput } from './AttributeInput';
import {
    AttributeInputFromJSON,
    AttributeInputFromJSONTyped,
    AttributeInputToJSON,
    AttributeInputToJSONTyped,
} from './AttributeInput';

/**
 * 
 * @export
 * @interface SetAttributes
 */
export interface SetAttributes {
    /**
     * 
     * @type {string}
     * @memberof SetAttributes
     */
    id: string;
    /**
     * Optional optimistic-concurrency precondition for the target object.
     * @type {number}
     * @memberof SetAttributes
     */
    expectedObjectNonce?: number;
    /**
     * 
     * @type {Array<AttributeInput>}
     * @memberof SetAttributes
     */
    attributes: Array<AttributeInput>;
}

/**
 * Check if a given object implements the SetAttributes interface.
 */
export function instanceOfSetAttributes(value: object): value is SetAttributes {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function SetAttributesFromJSON(json: any): SetAttributes {
    return SetAttributesFromJSONTyped(json, false);
}

export function SetAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'expectedObjectNonce': json['expected_object_nonce'] == null ? undefined : json['expected_object_nonce'],
        'attributes': ((json['attributes'] as Array<any>).map(AttributeInputFromJSON)),
    };
}

export function SetAttributesToJSON(json: any): SetAttributes {
    return SetAttributesToJSONTyped(json, false);
}

export function SetAttributesToJSONTyped(value?: SetAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'expected_object_nonce': value['expectedObjectNonce'],
        'attributes': ((value['attributes'] as Array<any>).map(AttributeInputToJSON)),
    };
}

