// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Chain } from './Chain';
import {
    ChainFromJSON,
    ChainFromJSONTyped,
    ChainToJSON,
    ChainToJSONTyped,
} from './Chain';
import type { Metadata } from './Metadata';
import {
    MetadataFromJSON,
    MetadataFromJSONTyped,
    MetadataToJSON,
    MetadataToJSONTyped,
} from './Metadata';
import type { Asset } from './Asset';
import {
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
    AssetToJSONTyped,
} from './Asset';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * Smart object entity representing a blockchain-based digital asset with metadata and state management
 * @export
 * @interface SmartObject
 */
export interface SmartObject {
    /**
     * Unique identifier for the smart object
     */
    id: string;
    /**
     * Organization identifier that owns this smart object
     */
    orgId: string;
    /**
     * Reference to the chain information
     */
    chain?: Chain;
    /**
     * System properties of the object
     */
    system?: object;
    /**
     * Custom properties of the object
     */
    custom?: object;
    /**
     * Custom hash for the object
     */
    customHash?: string;
    /**
     * Metadata information for the object
     */
    metadata: Metadata;
    /**
     * List of assets associated with the object
     */
    assets?: Array<Asset>;
    /**
     * ID of the owner of the object
     */
    owner: string;
    /**
     * Template identifier that defines the structure and behavior of this smart object
     */
    templateId: string;
    /**
     * Location information for the object
     */
    location?: Location;
    /**
     * Nonce value for the object
     */
    nonce: number;
    /**
     * Version of the object
     */
    version: number;
    /**
     * state root of the object
     */
    stateHash: string;
    /**
     * object content hash - metadata, assets, location, custom
     */
    contentHash: string;
    /**
     * Hash of the integrity data
     */
    integrityHash: string;
    /**
     * Hash of the previous integrity hash
     */
    prevIntegrityHash: string;
    /**
     * Timestamp of when the object was created
     */
    whenCreated: Date;
    /**
     * Timestamp of the last modification
     */
    whenModified: Date;
}

/**
 * Check if a given object implements the SmartObject interface.
 */
export function instanceOfSmartObject(value: object): value is SmartObject {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('orgId' in (value as Record<string, any>)) && !('org_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgId'] === undefined && (value as Record<string, any>)['org_id'] === undefined)) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    if ((!('templateId' in (value as Record<string, any>)) && !('template_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['templateId'] === undefined && (value as Record<string, any>)['template_id'] === undefined)) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if ((!('stateHash' in (value as Record<string, any>)) && !('state_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['stateHash'] === undefined && (value as Record<string, any>)['state_hash'] === undefined)) return false;
    if ((!('contentHash' in (value as Record<string, any>)) && !('content_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['contentHash'] === undefined && (value as Record<string, any>)['content_hash'] === undefined)) return false;
    if ((!('integrityHash' in (value as Record<string, any>)) && !('integrity_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['integrityHash'] === undefined && (value as Record<string, any>)['integrity_hash'] === undefined)) return false;
    if ((!('prevIntegrityHash' in (value as Record<string, any>)) && !('prev_integrity_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['prevIntegrityHash'] === undefined && (value as Record<string, any>)['prev_integrity_hash'] === undefined)) return false;
    if ((!('whenCreated' in (value as Record<string, any>)) && !('when_created' in (value as Record<string, any>))) || ((value as Record<string, any>)['whenCreated'] === undefined && (value as Record<string, any>)['when_created'] === undefined)) return false;
    if ((!('whenModified' in (value as Record<string, any>)) && !('when_modified' in (value as Record<string, any>))) || ((value as Record<string, any>)['whenModified'] === undefined && (value as Record<string, any>)['when_modified'] === undefined)) return false;
    return true;
}

export function SmartObjectFromJSON(json: any): SmartObject {
    return SmartObjectFromJSONTyped(json, false);
}

export function SmartObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmartObject {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'orgId': json['org_id'],
        'chain': json['chain'] == null ? undefined : ChainFromJSON(json['chain']),
        'system': json['system'] == null ? undefined : json['system'],
        'custom': json['custom'] == null ? undefined : json['custom'],
        'customHash': json['custom_hash'] == null ? undefined : json['custom_hash'],
        'metadata': MetadataFromJSON(json['metadata']),
        'assets': json['assets'] == null ? undefined : ((json['assets'] as Array<any>).map(AssetFromJSON)),
        'owner': json['owner'],
        'templateId': json['template_id'],
        'location': json['location'] == null ? undefined : LocationFromJSON(json['location']),
        'nonce': json['nonce'],
        'version': json['version'],
        'stateHash': json['state_hash'],
        'contentHash': json['content_hash'],
        'integrityHash': json['integrity_hash'],
        'prevIntegrityHash': json['prev_integrity_hash'],
        'whenCreated': (json['when_created'] == null ? json['when_created'] : new Date(json['when_created'])),
        'whenModified': (json['when_modified'] == null ? json['when_modified'] : new Date(json['when_modified'])),
    };
}

export function SmartObjectToJSON(json: any): SmartObject {
    return SmartObjectToJSONTyped(json, false);
}

export function SmartObjectToJSONTyped(value?: SmartObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'org_id': value['orgId'],
        'chain': ChainToJSON(value['chain']),
        'system': value['system'],
        'custom': value['custom'],
        'custom_hash': value['customHash'],
        'metadata': MetadataToJSON(value['metadata']),
        'assets': value['assets'] == null ? undefined : ((value['assets'] as Array<any>).map(AssetToJSON)),
        'owner': value['owner'],
        'template_id': value['templateId'],
        'location': LocationToJSON(value['location']),
        'nonce': value['nonce'],
        'version': value['version'],
        'state_hash': value['stateHash'],
        'content_hash': value['contentHash'],
        'integrity_hash': value['integrityHash'],
        'prev_integrity_hash': value['prevIntegrityHash'],
        'when_created': value['whenCreated'] == null ? value['whenCreated'] : value['whenCreated'].toISOString(),
        'when_modified': value['whenModified'] == null ? value['whenModified'] : value['whenModified'].toISOString(),
    };
}

