// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SmartAccount
 */
export interface SmartAccount {
    /**
     * Chain on which this Kernel deployment recipe is configured.
     */
    chainId: number;
    /**
     * Kernel factory used by the counterfactual CREATE2 derivation.
     */
    factory: string;
    /**
     * Kernel implementation used by the ERC-1967 proxy.
     */
    implementation: string;
    /**
     * Per-controller Kernel account index.
     */
    index: number;
    /**
     * Root validator installed when the Kernel account is deployed.
     */
    validator: string;
    /**
     * Root signature validator scheme.
     */
    validatorType: SmartAccountValidatorTypeEnum;
    /**
     * Kernel account version used by the deployment recipe.
     */
    version: string;
}


/**
 * @export
 */
export const SmartAccountValidatorTypeEnum = {
    Ecdsa: 'ECDSA',
    Webauthn: 'WEBAUTHN',
} as const;
export type SmartAccountValidatorTypeEnum = typeof SmartAccountValidatorTypeEnum[keyof typeof SmartAccountValidatorTypeEnum];


/**
 * Check if a given object implements the SmartAccount interface.
 */
export function instanceOfSmartAccount(value: object): value is SmartAccount {
    if ((!('chainId' in (value as Record<string, any>)) && !('chain_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['chainId'] === undefined && (value as Record<string, any>)['chain_id'] === undefined)) return false;
    if (!('factory' in value) || value['factory'] === undefined) return false;
    if (!('implementation' in value) || value['implementation'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('validator' in value) || value['validator'] === undefined) return false;
    if ((!('validatorType' in (value as Record<string, any>)) && !('validator_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['validatorType'] === undefined && (value as Record<string, any>)['validator_type'] === undefined)) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function SmartAccountFromJSON(json: any): SmartAccount {
    return SmartAccountFromJSONTyped(json, false);
}

export function SmartAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmartAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'chainId': json['chain_id'],
        'factory': json['factory'],
        'implementation': json['implementation'],
        'index': json['index'],
        'validator': json['validator'],
        'validatorType': json['validator_type'],
        'version': json['version'],
    };
}

export function SmartAccountToJSON(json: any): SmartAccount {
    return SmartAccountToJSONTyped(json, false);
}

export function SmartAccountToJSONTyped(value?: SmartAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain_id': value['chainId'],
        'factory': value['factory'],
        'implementation': value['implementation'],
        'index': value['index'],
        'validator': value['validator'],
        'validator_type': value['validatorType'],
        'version': value['version'],
    };
}

