// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of staking operation.
 * @export
 */
export const StakingOperationType = {
    Stake: 'stake',
    Unstake: 'unstake',
    Reward: 'reward',
    FeeDispatch: 'fee_dispatch',
    Other: 'other'
} as const;
export type StakingOperationType = typeof StakingOperationType[keyof typeof StakingOperationType];


export function instanceOfStakingOperationType(value: any): boolean {
    for (const key in StakingOperationType) {
        if (Object.prototype.hasOwnProperty.call(StakingOperationType, key)) {
            if (StakingOperationType[key as keyof typeof StakingOperationType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StakingOperationTypeFromJSON(json: any): StakingOperationType {
    return StakingOperationTypeFromJSONTyped(json, false);
}

export function StakingOperationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakingOperationType {
    return json as StakingOperationType;
}

export function StakingOperationTypeToJSON(value?: StakingOperationType | null): any {
    return value as any;
}

export function StakingOperationTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): StakingOperationType {
    return value as StakingOperationType;
}

