// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StakingOperationType } from './StakingOperationType';
import {
    StakingOperationTypeFromJSON,
    StakingOperationTypeFromJSONTyped,
    StakingOperationTypeToJSON,
    StakingOperationTypeToJSONTyped,
} from './StakingOperationType';

/**
 * User-specific staking information and rewards.
 * @export
 * @interface StakingOperation
 */
export interface StakingOperation {
    /**
     * Unique identifier for the deposit
     * @type {string}
     * @memberof StakingOperation
     */
    id: string;
    /**
     * Address of the staking user.
     * @type {string}
     * @memberof StakingOperation
     */
    address: string;
    /**
     * Amount of DUAL staked by the user (wei).
     * @type {string}
     * @memberof StakingOperation
     */
    amount: string;
    /**
     * Transaction hash of the staking operation.
     * @type {string}
     * @memberof StakingOperation
     */
    txHash: string;
    /**
     * 
     * @type {StakingOperationType}
     * @memberof StakingOperation
     */
    type: StakingOperationType;
    /**
     * Timestamp of when the deposit was created.
     * @type {Date}
     * @memberof StakingOperation
     */
    whenCreated: Date;
}



/**
 * Check if a given object implements the StakingOperation interface.
 */
export function instanceOfStakingOperation(value: object): value is StakingOperation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if ((!('txHash' in value) && !('tx_hash' in value)) || (value['txHash'] === undefined && value['tx_hash'] === undefined)) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if ((!('whenCreated' in value) && !('when_created' in value)) || (value['whenCreated'] === undefined && value['when_created'] === undefined)) return false;
    return true;
}

export function StakingOperationFromJSON(json: any): StakingOperation {
    return StakingOperationFromJSONTyped(json, false);
}

export function StakingOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakingOperation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'address': json['address'],
        'amount': json['amount'],
        'txHash': json['tx_hash'],
        'type': StakingOperationTypeFromJSON(json['type']),
        'whenCreated': (new Date(json['when_created'])),
    };
}

export function StakingOperationToJSON(json: any): StakingOperation {
    return StakingOperationToJSONTyped(json, false);
}

export function StakingOperationToJSONTyped(value?: StakingOperation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'address': value['address'],
        'amount': value['amount'],
        'tx_hash': value['txHash'],
        'type': StakingOperationTypeToJSON(value['type']),
        'when_created': value['whenCreated'].toISOString(),
    };
}

