// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatsBucket } from './StatsBucket';
import {
    StatsBucketFromJSON,
    StatsBucketFromJSONTyped,
    StatsBucketToJSON,
    StatsBucketToJSONTyped,
} from './StatsBucket';
import type { StatsPoint } from './StatsPoint';
import {
    StatsPointFromJSON,
    StatsPointFromJSONTyped,
    StatsPointToJSON,
    StatsPointToJSONTyped,
} from './StatsPoint';
import type { Interval } from './Interval';
import {
    IntervalFromJSON,
    IntervalFromJSONTyped,
    IntervalToJSON,
    IntervalToJSONTyped,
} from './Interval';

/**
 * A count aggregate. total is always present. breakdown and series are present
 * only when the request asked for them through the include parameter, so a
 * caller that wants the headline number alone does not pay for a grouping pass.
 * 
 * @export
 * @interface StatsOut
 */
export interface StatsOut {
    /**
     * Number of records matching the scope and the from/to window
     */
    total: number;
    /**
     * 
     */
    interval?: Interval;
    /**
     * Counts grouped by the group_by dimension. Present with include=breakdown.
     */
    breakdown?: Array<StatsBucket>;
    /**
     * Counts per time bucket. Present with include=series.
     */
    series?: Array<StatsPoint>;
}



/**
 * Check if a given object implements the StatsOut interface.
 */
export function instanceOfStatsOut(value: object): value is StatsOut {
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function StatsOutFromJSON(json: any): StatsOut {
    return StatsOutFromJSONTyped(json, false);
}

export function StatsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'interval': json['interval'] == null ? undefined : IntervalFromJSON(json['interval']),
        'breakdown': json['breakdown'] == null ? undefined : ((json['breakdown'] as Array<any>).map(StatsBucketFromJSON)),
        'series': json['series'] == null ? undefined : ((json['series'] as Array<any>).map(StatsPointFromJSON)),
    };
}

export function StatsOutToJSON(json: any): StatsOut {
    return StatsOutToJSONTyped(json, false);
}

export function StatsOutToJSONTyped(value?: StatsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'interval': IntervalToJSON(value['interval']),
        'breakdown': value['breakdown'] == null ? undefined : ((value['breakdown'] as Array<any>).map(StatsBucketToJSON)),
        'series': value['series'] == null ? undefined : ((value['series'] as Array<any>).map(StatsPointToJSON)),
    };
}

