// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One time bucket of a series.
 * @export
 * @interface StatsPoint
 */
export interface StatsPoint {
    /**
     * Start of the bucket. Buckets are half-open, [when, when+interval).
     */
    when: Date;
    /**
     * The grouped dimension this bucket belongs to, present only when the
     * request combined include=series with group_by. Without group_by a bucket
     * spans every group and this is absent, so a caller can tell a folded
     * series from a split one by the field alone rather than by remembering
     * what it asked for.
     * 
     */
    key?: string;
    /**
     * Number of records in this bucket
     */
    count: number;
}

/**
 * Check if a given object implements the StatsPoint interface.
 */
export function instanceOfStatsPoint(value: object): value is StatsPoint {
    if (!('when' in value) || value['when'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function StatsPointFromJSON(json: any): StatsPoint {
    return StatsPointFromJSONTyped(json, false);
}

export function StatsPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatsPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'when': (json['when'] == null ? json['when'] : new Date(json['when'])),
        'key': json['key'] == null ? undefined : json['key'],
        'count': json['count'],
    };
}

export function StatsPointToJSON(json: any): StatsPoint {
    return StatsPointToJSONTyped(json, false);
}

export function StatsPointToJSONTyped(value?: StatsPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'when': value['when'] == null ? value['when'] : value['when'].toISOString(),
        'key': value['key'],
        'count': value['count'],
    };
}

