// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChangeType } from './ChangeType';
import {
    ChangeTypeFromJSON,
    ChangeTypeFromJSONTyped,
    ChangeTypeToJSON,
    ChangeTypeToJSONTyped,
} from './ChangeType';

/**
 * 
 * @export
 * @interface StateChange
 */
export interface StateChange {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    walletId?: string;
    /**
     * 
     */
    objectId: string;
    /**
     * 
     */
    actionId: string;
    /**
     * The name of the action
     */
    actionName: string;
    /**
     * 
     */
    changeType: ChangeType;
    /**
     * Canonical signed mutation for attribute actions. Other internal object
     * update payloads may be redacted from API responses.
     * 
     */
    change?: object;
    /**
     * The previous state
     */
    prevStateHash: string;
    /**
     * The new state
     */
    nextStateHash: string;
    /**
     * The previous integrity hash
     */
    prevIntegrityHash: string;
    /**
     * The new integrity hash
     */
    nextIntegrityHash: string;
    /**
     * The previous nonce
     */
    prevNonce: number;
    /**
     * The next nonce
     */
    nextNonce: number;
    /**
     * previous object content hash - metadata, assets, location, custom
     */
    prevContentHash: string;
    /**
     * object content hash - metadata, assets, location, custom
     */
    nextContentHash: string;
    /**
     * The previous owner ID
     */
    prevOwner: string;
    /**
     * The new owner ID
     */
    currentOwner: string;
    /**
     * Merkle proof for the object's data integrity
     */
    merkleProof: Array<string>;
    /**
     * ID of the batch this state change is part of
     */
    batchId: string;
    /**
     * L1 transaction hash associated with this state change
     */
    l1TxHash?: string;
    /**
     * The time the change was created
     */
    whenCreated: Date;
}



/**
 * Check if a given object implements the StateChange interface.
 */
export function instanceOfStateChange(value: object): value is StateChange {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('objectId' in (value as Record<string, any>)) && !('object_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['objectId'] === undefined && (value as Record<string, any>)['object_id'] === undefined)) return false;
    if ((!('actionId' in (value as Record<string, any>)) && !('action_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['actionId'] === undefined && (value as Record<string, any>)['action_id'] === undefined)) return false;
    if ((!('actionName' in (value as Record<string, any>)) && !('action_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['actionName'] === undefined && (value as Record<string, any>)['action_name'] === undefined)) return false;
    if ((!('changeType' in (value as Record<string, any>)) && !('change_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['changeType'] === undefined && (value as Record<string, any>)['change_type'] === undefined)) return false;
    if ((!('prevStateHash' in (value as Record<string, any>)) && !('prev_state_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['prevStateHash'] === undefined && (value as Record<string, any>)['prev_state_hash'] === undefined)) return false;
    if ((!('nextStateHash' in (value as Record<string, any>)) && !('next_state_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextStateHash'] === undefined && (value as Record<string, any>)['next_state_hash'] === undefined)) return false;
    if ((!('prevIntegrityHash' in (value as Record<string, any>)) && !('prev_integrity_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['prevIntegrityHash'] === undefined && (value as Record<string, any>)['prev_integrity_hash'] === undefined)) return false;
    if ((!('nextIntegrityHash' in (value as Record<string, any>)) && !('next_integrity_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextIntegrityHash'] === undefined && (value as Record<string, any>)['next_integrity_hash'] === undefined)) return false;
    if ((!('prevNonce' in (value as Record<string, any>)) && !('prev_nonce' in (value as Record<string, any>))) || ((value as Record<string, any>)['prevNonce'] === undefined && (value as Record<string, any>)['prev_nonce'] === undefined)) return false;
    if ((!('nextNonce' in (value as Record<string, any>)) && !('next_nonce' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextNonce'] === undefined && (value as Record<string, any>)['next_nonce'] === undefined)) return false;
    if ((!('prevContentHash' in (value as Record<string, any>)) && !('prev_content_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['prevContentHash'] === undefined && (value as Record<string, any>)['prev_content_hash'] === undefined)) return false;
    if ((!('nextContentHash' in (value as Record<string, any>)) && !('next_content_hash' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextContentHash'] === undefined && (value as Record<string, any>)['next_content_hash'] === undefined)) return false;
    if ((!('prevOwner' in (value as Record<string, any>)) && !('prev_owner' in (value as Record<string, any>))) || ((value as Record<string, any>)['prevOwner'] === undefined && (value as Record<string, any>)['prev_owner'] === undefined)) return false;
    if ((!('currentOwner' in (value as Record<string, any>)) && !('current_owner' in (value as Record<string, any>))) || ((value as Record<string, any>)['currentOwner'] === undefined && (value as Record<string, any>)['current_owner'] === undefined)) return false;
    if ((!('merkleProof' in (value as Record<string, any>)) && !('merkle_proof' in (value as Record<string, any>))) || ((value as Record<string, any>)['merkleProof'] === undefined && (value as Record<string, any>)['merkle_proof'] === undefined)) return false;
    if ((!('batchId' in (value as Record<string, any>)) && !('batch_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['batchId'] === undefined && (value as Record<string, any>)['batch_id'] === undefined)) return false;
    if ((!('whenCreated' in (value as Record<string, any>)) && !('when_created' in (value as Record<string, any>))) || ((value as Record<string, any>)['whenCreated'] === undefined && (value as Record<string, any>)['when_created'] === undefined)) return false;
    return true;
}

export function StateChangeFromJSON(json: any): StateChange {
    return StateChangeFromJSONTyped(json, false);
}

export function StateChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateChange {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'walletId': json['wallet_id'] == null ? undefined : json['wallet_id'],
        'objectId': json['object_id'],
        'actionId': json['action_id'],
        'actionName': json['action_name'],
        'changeType': ChangeTypeFromJSON(json['change_type']),
        'change': json['change'] == null ? undefined : json['change'],
        'prevStateHash': json['prev_state_hash'],
        'nextStateHash': json['next_state_hash'],
        'prevIntegrityHash': json['prev_integrity_hash'],
        'nextIntegrityHash': json['next_integrity_hash'],
        'prevNonce': json['prev_nonce'],
        'nextNonce': json['next_nonce'],
        'prevContentHash': json['prev_content_hash'],
        'nextContentHash': json['next_content_hash'],
        'prevOwner': json['prev_owner'],
        'currentOwner': json['current_owner'],
        'merkleProof': json['merkle_proof'],
        'batchId': json['batch_id'],
        'l1TxHash': json['l1_tx_hash'] == null ? undefined : json['l1_tx_hash'],
        'whenCreated': (json['when_created'] == null ? json['when_created'] : new Date(json['when_created'])),
    };
}

export function StateChangeToJSON(json: any): StateChange {
    return StateChangeToJSONTyped(json, false);
}

export function StateChangeToJSONTyped(value?: StateChange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'wallet_id': value['walletId'],
        'object_id': value['objectId'],
        'action_id': value['actionId'],
        'action_name': value['actionName'],
        'change_type': ChangeTypeToJSON(value['changeType']),
        'change': value['change'],
        'prev_state_hash': value['prevStateHash'],
        'next_state_hash': value['nextStateHash'],
        'prev_integrity_hash': value['prevIntegrityHash'],
        'next_integrity_hash': value['nextIntegrityHash'],
        'prev_nonce': value['prevNonce'],
        'next_nonce': value['nextNonce'],
        'prev_content_hash': value['prevContentHash'],
        'next_content_hash': value['nextContentHash'],
        'prev_owner': value['prevOwner'],
        'current_owner': value['currentOwner'],
        'merkle_proof': value['merkleProof'],
        'batch_id': value['batchId'],
        'l1_tx_hash': value['l1TxHash'],
        'when_created': value['whenCreated'] == null ? value['whenCreated'] : value['whenCreated'].toISOString(),
    };
}

