// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Asset } from './Asset';
import {
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
    AssetToJSONTyped,
} from './Asset';

/**
 * Support message entity containing user inquiries and support requests
 * @export
 * @interface SupportMessage
 */
export interface SupportMessage {
    /**
     * Unique identifier for the support message
     */
    id: string;
    /**
     * Identifier of the wallet/user who created the support message
     */
    walletId: string;
    /**
     * Main content body of the support message
     */
    content: string;
    /**
     * Optional attachments or assets associated with the support message
     */
    assets?: Array<Asset>;
    /**
     * Timestamp when the support message was last modified
     */
    whenModified: Date;
    /**
     * Timestamp when the support message was created
     */
    whenCreated: Date;
}

/**
 * Check if a given object implements the SupportMessage interface.
 */
export function instanceOfSupportMessage(value: object): value is SupportMessage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('walletId' in (value as Record<string, any>)) && !('wallet_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['walletId'] === undefined && (value as Record<string, any>)['wallet_id'] === undefined)) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if ((!('whenModified' in (value as Record<string, any>)) && !('when_modified' in (value as Record<string, any>))) || ((value as Record<string, any>)['whenModified'] === undefined && (value as Record<string, any>)['when_modified'] === undefined)) return false;
    if ((!('whenCreated' in (value as Record<string, any>)) && !('when_created' in (value as Record<string, any>))) || ((value as Record<string, any>)['whenCreated'] === undefined && (value as Record<string, any>)['when_created'] === undefined)) return false;
    return true;
}

export function SupportMessageFromJSON(json: any): SupportMessage {
    return SupportMessageFromJSONTyped(json, false);
}

export function SupportMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupportMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'walletId': json['wallet_id'],
        'content': json['content'],
        'assets': json['assets'] == null ? undefined : ((json['assets'] as Array<any>).map(AssetFromJSON)),
        'whenModified': (json['when_modified'] == null ? json['when_modified'] : new Date(json['when_modified'])),
        'whenCreated': (json['when_created'] == null ? json['when_created'] : new Date(json['when_created'])),
    };
}

export function SupportMessageToJSON(json: any): SupportMessage {
    return SupportMessageToJSONTyped(json, false);
}

export function SupportMessageToJSONTyped(value?: SupportMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'wallet_id': value['walletId'],
        'content': value['content'],
        'assets': value['assets'] == null ? undefined : ((value['assets'] as Array<any>).map(AssetToJSON)),
        'when_modified': value['whenModified'] == null ? value['whenModified'] : value['whenModified'].toISOString(),
        'when_created': value['whenCreated'] == null ? value['whenCreated'] : value['whenCreated'].toISOString(),
    };
}

