// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const System = {
    Email: 'email',
    Sms: 'sms',
    Push: 'push',
} as const;
export type System = typeof System[keyof typeof System];


export function instanceOfSystem(value: any): boolean {
    for (const key in System) {
        if (Object.prototype.hasOwnProperty.call(System, key)) {
            if (System[key as keyof typeof System] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SystemFromJSON(json: any): System {
    return SystemFromJSONTyped(json, false);
}

export function SystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): System {
    return json as System;
}

export function SystemToJSON(value?: System | null): any {
    return value as any;
}

export function SystemToJSONTyped(value: any, ignoreDiscriminator: boolean): System {
    return value as System;
}

