// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemplateAction } from './TemplateAction';
import {
    TemplateActionFromJSON,
    TemplateActionFromJSONTyped,
    TemplateActionToJSON,
    TemplateActionToJSONTyped,
} from './TemplateAction';
import type { Factory } from './Factory';
import {
    FactoryFromJSON,
    FactoryFromJSONTyped,
    FactoryToJSON,
    FactoryToJSONTyped,
} from './Factory';
import type { PublicAccess } from './PublicAccess';
import {
    PublicAccessFromJSON,
    PublicAccessFromJSONTyped,
    PublicAccessToJSON,
    PublicAccessToJSONTyped,
} from './PublicAccess';
import type { TemplateObject } from './TemplateObject';
import {
    TemplateObjectFromJSON,
    TemplateObjectFromJSONTyped,
    TemplateObjectToJSON,
    TemplateObjectToJSONTyped,
} from './TemplateObject';

/**
 * Template entity defining the structure and behavior for creating smart objects
 * @export
 * @interface Template
 */
export interface Template {
    /**
     * Unique identifier for the template
     */
    id: string;
    /**
     * ID of the owner of the object
     */
    owner?: string;
    /**
     * Name of the object
     */
    name: string;
    /**
     * Fully Qualified Domain Name (FQDN) of the object
     */
    fqdn: string;
    /**
     * Reference to the object schema
     */
    object: TemplateObject;
    /**
     * Reference to the factory schema
     */
    factory?: Factory;
    /**
     * 
     */
    publicAccess?: PublicAccess;
    /**
     * Available actions that can be performed on objects created from this template
     */
    actions: Array<TemplateAction>;
    /**
     * Face identifier for the visual representation of objects created from this template
     */
    faceId?: string;
    /**
     * Timestamp of when the object was created
     */
    whenCreated: Date;
    /**
     * Timestamp of when the object was last modified
     */
    whenModified: Date;
}

/**
 * Check if a given object implements the Template interface.
 */
export function instanceOfTemplate(value: object): value is Template {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('fqdn' in value) || value['fqdn'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('actions' in value) || value['actions'] === undefined) return false;
    if ((!('whenCreated' in (value as Record<string, any>)) && !('when_created' in (value as Record<string, any>))) || ((value as Record<string, any>)['whenCreated'] === undefined && (value as Record<string, any>)['when_created'] === undefined)) return false;
    if ((!('whenModified' in (value as Record<string, any>)) && !('when_modified' in (value as Record<string, any>))) || ((value as Record<string, any>)['whenModified'] === undefined && (value as Record<string, any>)['when_modified'] === undefined)) return false;
    return true;
}

export function TemplateFromJSON(json: any): Template {
    return TemplateFromJSONTyped(json, false);
}

export function TemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Template {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'name': json['name'],
        'fqdn': json['fqdn'],
        'object': TemplateObjectFromJSON(json['object']),
        'factory': json['factory'] == null ? undefined : FactoryFromJSON(json['factory']),
        'publicAccess': json['public_access'] == null ? undefined : PublicAccessFromJSON(json['public_access']),
        'actions': ((json['actions'] as Array<any>).map(TemplateActionFromJSON)),
        'faceId': json['face_id'] == null ? undefined : json['face_id'],
        'whenCreated': (json['when_created'] == null ? json['when_created'] : new Date(json['when_created'])),
        'whenModified': (json['when_modified'] == null ? json['when_modified'] : new Date(json['when_modified'])),
    };
}

export function TemplateToJSON(json: any): Template {
    return TemplateToJSONTyped(json, false);
}

export function TemplateToJSONTyped(value?: Template | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'owner': value['owner'],
        'name': value['name'],
        'fqdn': value['fqdn'],
        'object': TemplateObjectToJSON(value['object']),
        'factory': FactoryToJSON(value['factory']),
        'public_access': PublicAccessToJSON(value['publicAccess']),
        'actions': ((value['actions'] as Array<any>).map(TemplateActionToJSON)),
        'face_id': value['faceId'],
        'when_created': value['whenCreated'] == null ? value['whenCreated'] : value['whenCreated'].toISOString(),
        'when_modified': value['whenModified'] == null ? value['whenModified'] : value['whenModified'].toISOString(),
    };
}

