// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Access control for the action
 * @export
 * @interface TemplateActionAccess
 */
export interface TemplateActionAccess {
    /**
     * Type of access
     */
    type: TemplateActionAccessTypeEnum;
    /**
     * 
     */
    tokens?: { [key: string]: number; };
}


/**
 * @export
 */
export const TemplateActionAccessTypeEnum = {
    Public: 'public',
    Private: 'private',
    Whitelist: 'whitelist',
    Token: 'token',
} as const;
export type TemplateActionAccessTypeEnum = typeof TemplateActionAccessTypeEnum[keyof typeof TemplateActionAccessTypeEnum];


/**
 * Check if a given object implements the TemplateActionAccess interface.
 */
export function instanceOfTemplateActionAccess(value: object): value is TemplateActionAccess {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TemplateActionAccessFromJSON(json: any): TemplateActionAccess {
    return TemplateActionAccessFromJSONTyped(json, false);
}

export function TemplateActionAccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateActionAccess {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'tokens': json['tokens'] == null ? undefined : json['tokens'],
    };
}

export function TemplateActionAccessToJSON(json: any): TemplateActionAccess {
    return TemplateActionAccessToJSONTyped(json, false);
}

export function TemplateActionAccessToJSONTyped(value?: TemplateActionAccess | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'tokens': value['tokens'],
    };
}

