// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeSeriesDataPoint
 */
export interface TimeSeriesDataPoint {
    /**
     * 
     */
    id?: string;
    /**
     * Key for this data point
     */
    key?: string;
    /**
     * Timestamp for this data point
     */
    when?: Date;
    /**
     * Count value for this data point
     */
    count?: number;
    /**
     * 
     */
    amount?: string;
}

/**
 * Check if a given object implements the TimeSeriesDataPoint interface.
 */
export function instanceOfTimeSeriesDataPoint(value: object): value is TimeSeriesDataPoint {
    return true;
}

export function TimeSeriesDataPointFromJSON(json: any): TimeSeriesDataPoint {
    return TimeSeriesDataPointFromJSONTyped(json, false);
}

export function TimeSeriesDataPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSeriesDataPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'when': json['when'] == null ? undefined : (new Date(json['when'])),
        'count': json['count'] == null ? undefined : json['count'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function TimeSeriesDataPointToJSON(json: any): TimeSeriesDataPoint {
    return TimeSeriesDataPointToJSONTyped(json, false);
}

export function TimeSeriesDataPointToJSONTyped(value?: TimeSeriesDataPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'when': value['when'] == null ? value['when'] : value['when'].toISOString(),
        'count': value['count'],
        'amount': value['amount'],
    };
}

