// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenCirculatingSupplyInfo
 */
export interface TokenCirculatingSupplyInfo {
    /**
     * The amount of tokens currently in circulation.
     */
    circulatingSupply: string;
    /**
     * The total supply of tokens, including those not yet in circulation.
     */
    totalSupply: string;
}

/**
 * Check if a given object implements the TokenCirculatingSupplyInfo interface.
 */
export function instanceOfTokenCirculatingSupplyInfo(value: object): value is TokenCirculatingSupplyInfo {
    if ((!('circulatingSupply' in (value as Record<string, any>)) && !('circulating_supply' in (value as Record<string, any>))) || ((value as Record<string, any>)['circulatingSupply'] === undefined && (value as Record<string, any>)['circulating_supply'] === undefined)) return false;
    if ((!('totalSupply' in (value as Record<string, any>)) && !('total_supply' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalSupply'] === undefined && (value as Record<string, any>)['total_supply'] === undefined)) return false;
    return true;
}

export function TokenCirculatingSupplyInfoFromJSON(json: any): TokenCirculatingSupplyInfo {
    return TokenCirculatingSupplyInfoFromJSONTyped(json, false);
}

export function TokenCirculatingSupplyInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenCirculatingSupplyInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'circulatingSupply': json['circulating_supply'],
        'totalSupply': json['total_supply'],
    };
}

export function TokenCirculatingSupplyInfoToJSON(json: any): TokenCirculatingSupplyInfo {
    return TokenCirculatingSupplyInfoToJSONTyped(json, false);
}

export function TokenCirculatingSupplyInfoToJSONTyped(value?: TokenCirculatingSupplyInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'circulating_supply': value['circulatingSupply'],
        'total_supply': value['totalSupply'],
    };
}

