// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Update
 */
export interface Update {
    /**
     * 
     * @type {string}
     * @memberof Update
     */
    id: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Update
     */
    data?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof Update
     */
    secret?: string;
}

/**
 * Check if a given object implements the Update interface.
 */
export function instanceOfUpdate(value: object): value is Update {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UpdateFromJSON(json: any): Update {
    return UpdateFromJSONTyped(json, false);
}

export function UpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Update {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'data': json['data'] == null ? undefined : json['data'],
        'secret': json['secret'] == null ? undefined : json['secret'],
    };
}

export function UpdateToJSON(json: any): Update {
    return UpdateToJSONTyped(json, false);
}

export function UpdateToJSONTyped(value?: Update | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'data': value['data'],
        'secret': value['secret'],
    };
}

