// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Access validator
 * @export
 * @interface Validators
 */
export interface Validators {
    /**
     * Type of validator
     */
    type: ValidatorsTypeEnum;
    /**
     * URL of the validator
     */
    url?: string;
}


/**
 * @export
 */
export const ValidatorsTypeEnum = {
    Http: 'http',
} as const;
export type ValidatorsTypeEnum = typeof ValidatorsTypeEnum[keyof typeof ValidatorsTypeEnum];


/**
 * Check if a given object implements the Validators interface.
 */
export function instanceOfValidators(value: object): value is Validators {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'http') return false;
    
    return true;
}

export function ValidatorsFromJSON(json: any): Validators {
    return ValidatorsFromJSONTyped(json, false);
}

export function ValidatorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Validators {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ValidatorsToJSON(json: any): Validators {
    return ValidatorsToJSONTyped(json, false);
}

export function ValidatorsToJSONTyped(value?: Validators | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'url': value['url'],
    };
}

