// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyIn
 */
export interface VerifyIn {
    /**
     * Email address associated with the account being verified
     * @type {string}
     * @memberof VerifyIn
     */
    email?: string;
    /**
     * Phone number in E.164 format associated with the account being verified
     * @type {string}
     * @memberof VerifyIn
     */
    phoneNumber?: string;
    /**
     * Verification code sent to the user's email or phone
     * @type {string}
     * @memberof VerifyIn
     */
    code: string;
}

/**
 * Check if a given object implements the VerifyIn interface.
 */
export function instanceOfVerifyIn(value: object): value is VerifyIn {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function VerifyInFromJSON(json: any): VerifyIn {
    return VerifyInFromJSONTyped(json, false);
}

export function VerifyInFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyIn {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'code': json['code'],
    };
}

export function VerifyInToJSON(json: any): VerifyIn {
    return VerifyInToJSONTyped(json, false);
}

export function VerifyInToJSONTyped(value?: VerifyIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'phone_number': value['phoneNumber'],
        'code': value['code'],
    };
}

