// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletsStatsOut
 */
export interface WalletsStatsOut {
    /**
     * Total number of users
     */
    total: number;
    /**
     * Number of active users in the specified time range
     */
    active: number;
}

/**
 * Check if a given object implements the WalletsStatsOut interface.
 */
export function instanceOfWalletsStatsOut(value: object): value is WalletsStatsOut {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    return true;
}

export function WalletsStatsOutFromJSON(json: any): WalletsStatsOut {
    return WalletsStatsOutFromJSONTyped(json, false);
}

export function WalletsStatsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletsStatsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'active': json['active'],
    };
}

export function WalletsStatsOutToJSON(json: any): WalletsStatsOut {
    return WalletsStatsOutToJSONTyped(json, false);
}

export function WalletsStatsOutToJSONTyped(value?: WalletsStatsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'active': value['active'],
    };
}

