// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';
import type { PasskeyCredential } from './PasskeyCredential';
import {
    PasskeyCredentialFromJSON,
    PasskeyCredentialFromJSONTyped,
    PasskeyCredentialToJSON,
    PasskeyCredentialToJSONTyped,
} from './PasskeyCredential';
import type { Language } from './Language';
import {
    LanguageFromJSON,
    LanguageFromJSONTyped,
    LanguageToJSON,
    LanguageToJSONTyped,
} from './Language';
import type { Asset } from './Asset';
import {
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
    AssetToJSONTyped,
} from './Asset';
import type { Session } from './Session';
import {
    SessionFromJSON,
    SessionFromJSONTyped,
    SessionToJSON,
    SessionToJSONTyped,
} from './Session';

/**
 * 
 * @export
 * @interface Wallet
 */
export interface Wallet {
    /**
     * Unique identifier for the user/account
     */
    id: string;
    /**
     * User's preferred display name or alias
     */
    nickname?: string;
    /**
     * User's email address for communications and account recovery
     */
    email?: string;
    /**
     * User's contact phone number, may be used for SMS verification or notifications
     */
    phoneNumber?: string;
    /**
     * 
     */
    avatar?: Asset;
    /**
     * User's preferred language for the interface and communications
     */
    language: Language;
    /**
     * Fully Qualified Domain Name associated with the user account
     */
    fqdn: string;
    /**
     * Indicates whether the user has completed the activation process
     */
    activated: boolean;
    /**
     * Indicates whether the account has been disabled by an administrator or automated process
     */
    disabled: boolean;
    /**
     * Reference to the user's account wallet information
     */
    account: Account;
    /**
     * WebAuthn credential bound to this wallet. Absent if the wallet was not registered via passkey.
     */
    passkey?: PasskeyCredential;
    /**
     * Active ERC-7579 session keys authorized by this wallet's passkey.
     */
    sessions?: Array<Session>;
    /**
     * Indicates whether the user is in the onboarding process
     */
    onboarding?: boolean;
    /**
     * Timestamp of when the user account was initially created
     */
    whenCreated: Date;
    /**
     * Timestamp of when the user account was last modified
     */
    whenModified: Date;
}



/**
 * Check if a given object implements the Wallet interface.
 */
export function instanceOfWallet(value: object): value is Wallet {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('fqdn' in value) || value['fqdn'] === undefined) return false;
    if (!('activated' in value) || value['activated'] === undefined) return false;
    if (!('disabled' in value) || value['disabled'] === undefined) return false;
    if (!('account' in value) || value['account'] === undefined) return false;
    if ((!('whenCreated' in (value as Record<string, any>)) && !('when_created' in (value as Record<string, any>))) || ((value as Record<string, any>)['whenCreated'] === undefined && (value as Record<string, any>)['when_created'] === undefined)) return false;
    if ((!('whenModified' in (value as Record<string, any>)) && !('when_modified' in (value as Record<string, any>))) || ((value as Record<string, any>)['whenModified'] === undefined && (value as Record<string, any>)['when_modified'] === undefined)) return false;
    return true;
}

export function WalletFromJSON(json: any): Wallet {
    return WalletFromJSONTyped(json, false);
}

export function WalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): Wallet {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'avatar': json['avatar'] == null ? undefined : AssetFromJSON(json['avatar']),
        'language': LanguageFromJSON(json['language']),
        'fqdn': json['fqdn'],
        'activated': json['activated'],
        'disabled': json['disabled'],
        'account': AccountFromJSON(json['account']),
        'passkey': json['passkey'] == null ? undefined : PasskeyCredentialFromJSON(json['passkey']),
        'sessions': json['sessions'] == null ? undefined : ((json['sessions'] as Array<any>).map(SessionFromJSON)),
        'onboarding': json['onboarding'] == null ? undefined : json['onboarding'],
        'whenCreated': (json['when_created'] == null ? json['when_created'] : new Date(json['when_created'])),
        'whenModified': (json['when_modified'] == null ? json['when_modified'] : new Date(json['when_modified'])),
    };
}

export function WalletToJSON(json: any): Wallet {
    return WalletToJSONTyped(json, false);
}

export function WalletToJSONTyped(value?: Wallet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nickname': value['nickname'],
        'email': value['email'],
        'phone_number': value['phoneNumber'],
        'avatar': AssetToJSON(value['avatar']),
        'language': LanguageToJSON(value['language']),
        'fqdn': value['fqdn'],
        'activated': value['activated'],
        'disabled': value['disabled'],
        'account': AccountToJSON(value['account']),
        'passkey': PasskeyCredentialToJSON(value['passkey']),
        'sessions': value['sessions'] == null ? undefined : ((value['sessions'] as Array<any>).map(SessionToJSON)),
        'onboarding': value['onboarding'],
        'when_created': value['whenCreated'] == null ? value['whenCreated'] : value['whenCreated'].toISOString(),
        'when_modified': value['whenModified'] == null ? value['whenModified'] : value['whenModified'].toISOString(),
    };
}

