// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Language } from './Language';
import {
    LanguageFromJSON,
    LanguageFromJSONTyped,
    LanguageToJSON,
    LanguageToJSONTyped,
} from './Language';
import type { Asset } from './Asset';
import {
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
    AssetToJSONTyped,
} from './Asset';

/**
 * 
 * @export
 * @interface WalletUpdate
 */
export interface WalletUpdate {
    /**
     * User's preferred display name or alias
     */
    nickname?: string;
    /**
     * User's email address for authentication and communications
     */
    email?: string;
    /**
     * User's phone number in E.164 international format for verification or notifications
     */
    phoneNumber?: string;
    /**
     * User's preferred language setting for the interface and communications
     */
    language?: Language;
    /**
     * New account password. Sending it requires current_password, and it ends every other session on the wallet.
     */
    password?: string;
    /**
     * The password in force now. Required only when password is sent, to prove the caller owns the account rather than merely holding a token for it.
     */
    currentPassword?: string;
    /**
     * 
     */
    avatar?: Asset;
    /**
     * Indicates whether the user is in the onboarding process
     */
    onboarding?: boolean;
}



/**
 * Check if a given object implements the WalletUpdate interface.
 */
export function instanceOfWalletUpdate(value: object): value is WalletUpdate {
    return true;
}

export function WalletUpdateFromJSON(json: any): WalletUpdate {
    return WalletUpdateFromJSONTyped(json, false);
}

export function WalletUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'language': json['language'] == null ? undefined : LanguageFromJSON(json['language']),
        'password': json['password'] == null ? undefined : json['password'],
        'currentPassword': json['current_password'] == null ? undefined : json['current_password'],
        'avatar': json['avatar'] == null ? undefined : AssetFromJSON(json['avatar']),
        'onboarding': json['onboarding'] == null ? undefined : json['onboarding'],
    };
}

export function WalletUpdateToJSON(json: any): WalletUpdate {
    return WalletUpdateToJSONTyped(json, false);
}

export function WalletUpdateToJSONTyped(value?: WalletUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nickname': value['nickname'],
        'email': value['email'],
        'phone_number': value['phoneNumber'],
        'language': LanguageToJSON(value['language']),
        'password': value['password'],
        'current_password': value['currentPassword'],
        'avatar': AssetToJSON(value['avatar']),
        'onboarding': value['onboarding'],
    };
}

