// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookCreateOut
 */
export interface WebhookCreateOut {
    /**
     * Unique identifier for the newly created webhook.
     */
    id: string;
    /**
     * Secret key used to verify webhook payloads via signatures. It is
     * returned by this operation only: no read endpoint echoes it back
     * and rotation is not available, so store it when it arrives.
     * 
     */
    signingKey: string;
}

/**
 * Check if a given object implements the WebhookCreateOut interface.
 */
export function instanceOfWebhookCreateOut(value: object): value is WebhookCreateOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('signingKey' in (value as Record<string, any>)) && !('signing_key' in (value as Record<string, any>))) || ((value as Record<string, any>)['signingKey'] === undefined && (value as Record<string, any>)['signing_key'] === undefined)) return false;
    return true;
}

export function WebhookCreateOutFromJSON(json: any): WebhookCreateOut {
    return WebhookCreateOutFromJSONTyped(json, false);
}

export function WebhookCreateOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookCreateOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'signingKey': json['signing_key'],
    };
}

export function WebhookCreateOutToJSON(json: any): WebhookCreateOut {
    return WebhookCreateOutToJSONTyped(json, false);
}

export function WebhookCreateOutToJSONTyped(value?: WebhookCreateOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'signing_key': value['signingKey'],
    };
}

