// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Face,
    FaceFromJSON,
    FaceToJSON,
} from '../models/Face';
import {
    type FaceCreate,
    FaceCreateFromJSON,
    FaceCreateToJSON,
} from '../models/FaceCreate';
import {
    type FaceUpdate,
    FaceUpdateFromJSON,
    FaceUpdateToJSON,
} from '../models/FaceUpdate';
import {
    type InlineObject,
    InlineObjectFromJSON,
    InlineObjectToJSON,
} from '../models/InlineObject';
import {
    type ListFacesOut,
    ListFacesOutFromJSON,
    ListFacesOutToJSON,
} from '../models/ListFacesOut';
import {
    type ModelError,
    ModelErrorFromJSON,
    ModelErrorToJSON,
} from '../models/ModelError';

export interface CreateFaceRequest {
    faceCreate: FaceCreate;
}

export interface DeleteFaceRequest {
    faceId: string;
}

export interface GetFaceRequest {
    faceId: string;
}

export interface GetFacePreviewRequest {
    faceId: string;
}

export interface ListFacesRequest {
    id?: string;
    orgId?: string;
    name?: string;
    autocomplete?: string;
    limit?: number;
    next?: string;
    order?: ListFacesOrderEnum;
    sortBy?: string;
    whenCreated$gt?: Date;
    whenCreated$lt?: Date;
    whenCreated$gte?: Date;
    whenCreated$lte?: Date;
}

export interface UpdateFaceRequest {
    faceId: string;
    faceUpdate: FaceUpdate;
}

/**
 * 
 */
export class FacesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createFace without sending the request
     */
    async createFaceRequestOpts(requestParameters: CreateFaceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['faceCreate'] == null) {
            throw new runtime.RequiredError(
                'faceCreate',
                'Required parameter "faceCreate" was null or undefined when calling createFace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/faces`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FaceCreateToJSON(requestParameters['faceCreate']),
        };
    }

    /**
     * Create a new face definition by providing necessary configuration details.
     * Create a new face
     */
    async createFaceRaw(requestParameters: CreateFaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        const requestOptions = await this.createFaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * Create a new face definition by providing necessary configuration details.
     * Create a new face
     */
    async createFace(requestParameters: CreateFaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.createFaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteFace without sending the request
     */
    async deleteFaceRequestOpts(requestParameters: DeleteFaceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['faceId'] == null) {
            throw new runtime.RequiredError(
                'faceId',
                'Required parameter "faceId" was null or undefined when calling deleteFace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/faces/{faceId}`;
        urlPath = urlPath.replace('{faceId}', encodeURIComponent(String(requestParameters['faceId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permanently remove a face from the system by providing its unique ID.
     * Delete a face
     */
    async deleteFaceRaw(requestParameters: DeleteFaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.deleteFaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Permanently remove a face from the system by providing its unique ID.
     * Delete a face
     */
    async deleteFace(requestParameters: DeleteFaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.deleteFaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFace without sending the request
     */
    async getFaceRequestOpts(requestParameters: GetFaceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['faceId'] == null) {
            throw new runtime.RequiredError(
                'faceId',
                'Required parameter "faceId" was null or undefined when calling getFace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/faces/{faceId}`;
        urlPath = urlPath.replace('{faceId}', encodeURIComponent(String(requestParameters['faceId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve detailed information for a specific face by providing its unique ID.
     * Retrieve a specific face
     */
    async getFaceRaw(requestParameters: GetFaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Face>> {
        const requestOptions = await this.getFaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FaceFromJSON(jsonValue));
    }

    /**
     * Retrieve detailed information for a specific face by providing its unique ID.
     * Retrieve a specific face
     */
    async getFace(requestParameters: GetFaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Face> {
        const response = await this.getFaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFacePreview without sending the request
     */
    async getFacePreviewRequestOpts(requestParameters: GetFacePreviewRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['faceId'] == null) {
            throw new runtime.RequiredError(
                'faceId',
                'Required parameter "faceId" was null or undefined when calling getFacePreview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/faces/{faceId}/preview`;
        urlPath = urlPath.replace('{faceId}', encodeURIComponent(String(requestParameters['faceId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a preview of a specific face as a page.
     * Preview a face
     */
    async getFacePreviewRaw(requestParameters: GetFacePreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.getFacePreviewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Retrieve a preview of a specific face as a page.
     * Preview a face
     */
    async getFacePreview(requestParameters: GetFacePreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getFacePreviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listFaces without sending the request
     */
    async listFacesRequestOpts(requestParameters: ListFacesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['orgId'] != null) {
            queryParameters['org_id'] = requestParameters['orgId'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['autocomplete'] != null) {
            queryParameters['autocomplete'] = requestParameters['autocomplete'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['next'] != null) {
            queryParameters['next'] = requestParameters['next'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['whenCreated$gt'] != null) {
            queryParameters['when_created[$gt]'] = (requestParameters['whenCreated$gt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lt'] != null) {
            queryParameters['when_created[$lt]'] = (requestParameters['whenCreated$lt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$gte'] != null) {
            queryParameters['when_created[$gte]'] = (requestParameters['whenCreated$gte'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lte'] != null) {
            queryParameters['when_created[$lte]'] = (requestParameters['whenCreated$lte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/faces`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a list of face definitions, with optional filters for template type, language, limit, and pagination.
     * Retrieve a list of faces
     */
    async listFacesRaw(requestParameters: ListFacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFacesOut>> {
        const requestOptions = await this.listFacesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListFacesOutFromJSON(jsonValue));
    }

    /**
     * Retrieve a list of face definitions, with optional filters for template type, language, limit, and pagination.
     * Retrieve a list of faces
     */
    async listFaces(requestParameters: ListFacesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFacesOut> {
        const response = await this.listFacesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateFace without sending the request
     */
    async updateFaceRequestOpts(requestParameters: UpdateFaceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['faceId'] == null) {
            throw new runtime.RequiredError(
                'faceId',
                'Required parameter "faceId" was null or undefined when calling updateFace().'
            );
        }

        if (requestParameters['faceUpdate'] == null) {
            throw new runtime.RequiredError(
                'faceUpdate',
                'Required parameter "faceUpdate" was null or undefined when calling updateFace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/faces/{faceId}`;
        urlPath = urlPath.replace('{faceId}', encodeURIComponent(String(requestParameters['faceId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: FaceUpdateToJSON(requestParameters['faceUpdate']),
        };
    }

    /**
     * Update the attributes of an existing face by specifying its unique ID along with the updated data.
     * Update face details
     */
    async updateFaceRaw(requestParameters: UpdateFaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.updateFaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Update the attributes of an existing face by specifying its unique ID along with the updated data.
     * Update face details
     */
    async updateFace(requestParameters: UpdateFaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.updateFaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListFacesOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListFacesOrderEnum = typeof ListFacesOrderEnum[keyof typeof ListFacesOrderEnum];
