// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ListStakingOperationsOut,
    ListStakingOperationsOutFromJSON,
    ListStakingOperationsOutToJSON,
} from '../models/ListStakingOperationsOut';
import {
    type ModelError,
    ModelErrorFromJSON,
    ModelErrorToJSON,
} from '../models/ModelError';
import {
    type NetworkConfig,
    NetworkConfigFromJSON,
    NetworkConfigToJSON,
} from '../models/NetworkConfig';
import {
    type NetworkInfo,
    NetworkInfoFromJSON,
    NetworkInfoToJSON,
} from '../models/NetworkInfo';
import {
    type NetworkStaking,
    NetworkStakingFromJSON,
    NetworkStakingToJSON,
} from '../models/NetworkStaking';
import {
    type NetworkTokenMarketData,
    NetworkTokenMarketDataFromJSON,
    NetworkTokenMarketDataToJSON,
} from '../models/NetworkTokenMarketData';
import {
    type NetworkTokenPriceHistory,
    NetworkTokenPriceHistoryFromJSON,
    NetworkTokenPriceHistoryToJSON,
} from '../models/NetworkTokenPriceHistory';
import {
    type StakingOperationType,
    StakingOperationTypeFromJSON,
    StakingOperationTypeToJSON,
} from '../models/StakingOperationType';
import {
    type StakingOperationsStats,
    StakingOperationsStatsFromJSON,
    StakingOperationsStatsToJSON,
} from '../models/StakingOperationsStats';
import {
    type TokenCirculatingSupplyInfo,
    TokenCirculatingSupplyInfoFromJSON,
    TokenCirculatingSupplyInfoToJSON,
} from '../models/TokenCirculatingSupplyInfo';

export interface GetNetworkStakingInfoRequest {
    address?: string;
}

export interface GetNetworkTokenPriceHistoryRequest {
    timeRange?: GetNetworkTokenPriceHistoryTimeRangeEnum;
}

export interface GetStakingOperationsStatsRequest {
    interval?: GetStakingOperationsStatsIntervalEnum;
    timeRange?: GetStakingOperationsStatsTimeRangeEnum;
    limit?: number;
    whenCreated$gt?: Date;
    whenCreated$lt?: Date;
    whenCreated$gte?: Date;
    whenCreated$lte?: Date;
}

export interface GetStakingOperationsTotalRequest {
    interval?: GetStakingOperationsTotalIntervalEnum;
    limit?: number;
    type?: StakingOperationType;
    whenCreated$gt?: Date;
    whenCreated$lt?: Date;
    whenCreated$gte?: Date;
    whenCreated$lte?: Date;
}

export interface ListStakingOperationsRequest {
    id?: string;
    autocomplete?: string;
    limit?: number;
    next?: string;
    order?: ListStakingOperationsOrderEnum;
    sortBy?: string;
    address?: string;
    txHash?: string;
    type?: StakingOperationType;
    whenCreated$gt?: Date;
    whenCreated$gte?: Date;
    whenCreated$lt?: Date;
    whenCreated$lte?: Date;
}

/**
 * 
 */
export class IndexerApi extends runtime.BaseAPI {

    /**
     * Creates request options for getNetworkConfig without sending the request
     */
    async getNetworkConfigRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/network/config`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve the network configuration associated with the eBus network, including their types, statuses, and other relevant information. 
     * Get network configuration
     */
    async getNetworkConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NetworkConfig>> {
        const requestOptions = await this.getNetworkConfigRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NetworkConfigFromJSON(jsonValue));
    }

    /**
     * Retrieve the network configuration associated with the eBus network, including their types, statuses, and other relevant information. 
     * Get network configuration
     */
    async getNetworkConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NetworkConfig> {
        const response = await this.getNetworkConfigRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNetworkInfo without sending the request
     */
    async getNetworkInfoRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/network`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve detailed information about the eBus network, including current fees, network status, and other relevant metrics. 
     * Get network information
     */
    async getNetworkInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NetworkInfo>> {
        const requestOptions = await this.getNetworkInfoRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NetworkInfoFromJSON(jsonValue));
    }

    /**
     * Retrieve detailed information about the eBus network, including current fees, network status, and other relevant metrics. 
     * Get network information
     */
    async getNetworkInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NetworkInfo> {
        const response = await this.getNetworkInfoRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNetworkStakingInfo without sending the request
     */
    async getNetworkStakingInfoRequestOpts(requestParameters: GetNetworkStakingInfoRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/network/staking`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve detailed information about the eBus network staking, including current fees, network status, and other relevant metrics. 
     * Get network staking information
     */
    async getNetworkStakingInfoRaw(requestParameters: GetNetworkStakingInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NetworkStaking>> {
        const requestOptions = await this.getNetworkStakingInfoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NetworkStakingFromJSON(jsonValue));
    }

    /**
     * Retrieve detailed information about the eBus network staking, including current fees, network status, and other relevant metrics. 
     * Get network staking information
     */
    async getNetworkStakingInfo(requestParameters: GetNetworkStakingInfoRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NetworkStaking> {
        const response = await this.getNetworkStakingInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNetworkTokenCirculatingSupply without sending the request
     */
    async getNetworkTokenCirculatingSupplyRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/network/token/circulating-supply`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve detailed information about the eBus network\'s token circulating supply, including current fees, network status, and other relevant metrics. 
     * Get network token circulating supply
     */
    async getNetworkTokenCirculatingSupplyRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenCirculatingSupplyInfo>> {
        const requestOptions = await this.getNetworkTokenCirculatingSupplyRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenCirculatingSupplyInfoFromJSON(jsonValue));
    }

    /**
     * Retrieve detailed information about the eBus network\'s token circulating supply, including current fees, network status, and other relevant metrics. 
     * Get network token circulating supply
     */
    async getNetworkTokenCirculatingSupply(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenCirculatingSupplyInfo> {
        const response = await this.getNetworkTokenCirculatingSupplyRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNetworkTokenMarketData without sending the request
     */
    async getNetworkTokenMarketDataRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/network/token/market-data`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve detailed information about the network token, including current fees, network status, and other relevant metrics. 
     * Get network token market data
     */
    async getNetworkTokenMarketDataRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NetworkTokenMarketData>> {
        const requestOptions = await this.getNetworkTokenMarketDataRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NetworkTokenMarketDataFromJSON(jsonValue));
    }

    /**
     * Retrieve detailed information about the network token, including current fees, network status, and other relevant metrics. 
     * Get network token market data
     */
    async getNetworkTokenMarketData(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NetworkTokenMarketData> {
        const response = await this.getNetworkTokenMarketDataRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNetworkTokenPriceHistory without sending the request
     */
    async getNetworkTokenPriceHistoryRequestOpts(requestParameters: GetNetworkTokenPriceHistoryRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['timeRange'] != null) {
            queryParameters['time_range'] = requestParameters['timeRange'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/network/token/price-history`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve detailed information about the eBus network token, including current fees, network status, and other relevant metrics. 
     * Get network token price history
     */
    async getNetworkTokenPriceHistoryRaw(requestParameters: GetNetworkTokenPriceHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NetworkTokenPriceHistory>> {
        const requestOptions = await this.getNetworkTokenPriceHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NetworkTokenPriceHistoryFromJSON(jsonValue));
    }

    /**
     * Retrieve detailed information about the eBus network token, including current fees, network status, and other relevant metrics. 
     * Get network token price history
     */
    async getNetworkTokenPriceHistory(requestParameters: GetNetworkTokenPriceHistoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NetworkTokenPriceHistory> {
        const response = await this.getNetworkTokenPriceHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getStakingOperationsStats without sending the request
     */
    async getStakingOperationsStatsRequestOpts(requestParameters: GetStakingOperationsStatsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['interval'] != null) {
            queryParameters['interval'] = requestParameters['interval'];
        }

        if (requestParameters['timeRange'] != null) {
            queryParameters['time_range'] = requestParameters['timeRange'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['whenCreated$gt'] != null) {
            queryParameters['when_created[$gt]'] = (requestParameters['whenCreated$gt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lt'] != null) {
            queryParameters['when_created[$lt]'] = (requestParameters['whenCreated$lt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$gte'] != null) {
            queryParameters['when_created[$gte]'] = (requestParameters['whenCreated$gte'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lte'] != null) {
            queryParameters['when_created[$lte]'] = (requestParameters['whenCreated$lte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/network/staking/operations/stats`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve statistics about staking operations, including total counts, trends over time, and other relevant metrics to analyze staking activity on the eBus network. 
     * Get staking operations statistics
     */
    async getStakingOperationsStatsRaw(requestParameters: GetStakingOperationsStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StakingOperationsStats>> {
        const requestOptions = await this.getStakingOperationsStatsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StakingOperationsStatsFromJSON(jsonValue));
    }

    /**
     * Retrieve statistics about staking operations, including total counts, trends over time, and other relevant metrics to analyze staking activity on the eBus network. 
     * Get staking operations statistics
     */
    async getStakingOperationsStats(requestParameters: GetStakingOperationsStatsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StakingOperationsStats> {
        const response = await this.getStakingOperationsStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getStakingOperationsTotal without sending the request
     */
    async getStakingOperationsTotalRequestOpts(requestParameters: GetStakingOperationsTotalRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['interval'] != null) {
            queryParameters['interval'] = requestParameters['interval'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['whenCreated$gt'] != null) {
            queryParameters['when_created[$gt]'] = (requestParameters['whenCreated$gt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lt'] != null) {
            queryParameters['when_created[$lt]'] = (requestParameters['whenCreated$lt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$gte'] != null) {
            queryParameters['when_created[$gte]'] = (requestParameters['whenCreated$gte'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lte'] != null) {
            queryParameters['when_created[$lte]'] = (requestParameters['whenCreated$lte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/network/staking/operations/total`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve cumulative (running total) amounts per staking operation type over time, suitable for rendering \"total staked over time\" charts. 
     * Get cumulative staking operations totals over time
     */
    async getStakingOperationsTotalRaw(requestParameters: GetStakingOperationsTotalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StakingOperationsStats>> {
        const requestOptions = await this.getStakingOperationsTotalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StakingOperationsStatsFromJSON(jsonValue));
    }

    /**
     * Retrieve cumulative (running total) amounts per staking operation type over time, suitable for rendering \"total staked over time\" charts. 
     * Get cumulative staking operations totals over time
     */
    async getStakingOperationsTotal(requestParameters: GetStakingOperationsTotalRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StakingOperationsStats> {
        const response = await this.getStakingOperationsTotalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listStakingOperations without sending the request
     */
    async listStakingOperationsRequestOpts(requestParameters: ListStakingOperationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['autocomplete'] != null) {
            queryParameters['autocomplete'] = requestParameters['autocomplete'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['next'] != null) {
            queryParameters['next'] = requestParameters['next'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['txHash'] != null) {
            queryParameters['tx_hash'] = requestParameters['txHash'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['whenCreated$gt'] != null) {
            queryParameters['when_created[$gt]'] = (requestParameters['whenCreated$gt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$gte'] != null) {
            queryParameters['when_created[$gte]'] = (requestParameters['whenCreated$gte'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lt'] != null) {
            queryParameters['when_created[$lt]'] = (requestParameters['whenCreated$lt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lte'] != null) {
            queryParameters['when_created[$lte]'] = (requestParameters['whenCreated$lte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/network/staking/operations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch a list of all staking operations.
     * List all staking operations
     */
    async listStakingOperationsRaw(requestParameters: ListStakingOperationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListStakingOperationsOut>> {
        const requestOptions = await this.listStakingOperationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListStakingOperationsOutFromJSON(jsonValue));
    }

    /**
     * Fetch a list of all staking operations.
     * List all staking operations
     */
    async listStakingOperations(requestParameters: ListStakingOperationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListStakingOperationsOut> {
        const response = await this.listStakingOperationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetNetworkTokenPriceHistoryTimeRangeEnum = {
    All: 'all',
    Today: 'today',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type GetNetworkTokenPriceHistoryTimeRangeEnum = typeof GetNetworkTokenPriceHistoryTimeRangeEnum[keyof typeof GetNetworkTokenPriceHistoryTimeRangeEnum];
/**
 * @export
 */
export const GetStakingOperationsStatsIntervalEnum = {
    Hour: 'hour',
    Day: 'day',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type GetStakingOperationsStatsIntervalEnum = typeof GetStakingOperationsStatsIntervalEnum[keyof typeof GetStakingOperationsStatsIntervalEnum];
/**
 * @export
 */
export const GetStakingOperationsStatsTimeRangeEnum = {
    All: 'all',
    Today: 'today',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type GetStakingOperationsStatsTimeRangeEnum = typeof GetStakingOperationsStatsTimeRangeEnum[keyof typeof GetStakingOperationsStatsTimeRangeEnum];
/**
 * @export
 */
export const GetStakingOperationsTotalIntervalEnum = {
    Hour: 'hour',
    Day: 'day',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type GetStakingOperationsTotalIntervalEnum = typeof GetStakingOperationsTotalIntervalEnum[keyof typeof GetStakingOperationsTotalIntervalEnum];
/**
 * @export
 */
export const ListStakingOperationsOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListStakingOperationsOrderEnum = typeof ListStakingOperationsOrderEnum[keyof typeof ListStakingOperationsOrderEnum];
