// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type InlineObject,
    InlineObjectFromJSON,
    InlineObjectToJSON,
} from '../models/InlineObject';
import {
    type Language,
    LanguageFromJSON,
    LanguageToJSON,
} from '../models/Language';
import {
    type ListNotificationMessagesOut,
    ListNotificationMessagesOutFromJSON,
    ListNotificationMessagesOutToJSON,
} from '../models/ListNotificationMessagesOut';
import {
    type ListNotificationTemplatesOut,
    ListNotificationTemplatesOutFromJSON,
    ListNotificationTemplatesOutToJSON,
} from '../models/ListNotificationTemplatesOut';
import {
    type MessageCreate,
    MessageCreateFromJSON,
    MessageCreateToJSON,
} from '../models/MessageCreate';
import {
    type MessageStatus,
    MessageStatusFromJSON,
    MessageStatusToJSON,
} from '../models/MessageStatus';
import {
    type ModelError,
    ModelErrorFromJSON,
    ModelErrorToJSON,
} from '../models/ModelError';
import {
    type System,
    SystemFromJSON,
    SystemToJSON,
} from '../models/System';
import {
    type TemplateMessage,
    TemplateMessageFromJSON,
    TemplateMessageToJSON,
} from '../models/TemplateMessage';
import {
    type TemplateMessageCreate,
    TemplateMessageCreateFromJSON,
    TemplateMessageCreateToJSON,
} from '../models/TemplateMessageCreate';
import {
    type TemplateMessageUpdate,
    TemplateMessageUpdateFromJSON,
    TemplateMessageUpdateToJSON,
} from '../models/TemplateMessageUpdate';

export interface CreateNotificationTemplateRequest {
    templateMessageCreate: TemplateMessageCreate;
}

export interface DeleteNotificationTemplateRequest {
    templateId: string;
}

export interface GetNotificationTemplateRequest {
    templateId: string;
}

export interface ListMessagesRequest {
    id?: string;
    limit?: number;
    autocomplete?: string;
    next?: string;
    order?: ListMessagesOrderEnum;
    sortBy?: string;
    templateId?: string;
    to?: string;
    language?: Language;
    system?: System;
    actionType?: string;
    status?: MessageStatus;
    whenCreated$gt?: Date;
    whenCreated$lt?: Date;
    whenCreated$gte?: Date;
    whenCreated$lte?: Date;
}

export interface ListNotificationTemplatesRequest {
    id?: string;
    limit?: number;
    next?: string;
    autocomplete?: string;
    order?: ListNotificationTemplatesOrderEnum;
    sortBy?: string;
    language?: Language;
    system?: System;
    type?: string;
    whenCreated$gt?: Date;
    whenCreated$lt?: Date;
    whenCreated$gte?: Date;
    whenCreated$lte?: Date;
}

export interface SendMessageRequest {
    messageCreate: MessageCreate;
}

export interface UpdateNotificationTemplateRequest {
    templateId: string;
    templateMessageUpdate: TemplateMessageUpdate;
}

/**
 * 
 */
export class NotificationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createNotificationTemplate without sending the request
     */
    async createNotificationTemplateRequestOpts(requestParameters: CreateNotificationTemplateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateMessageCreate'] == null) {
            throw new runtime.RequiredError(
                'templateMessageCreate',
                'Required parameter "templateMessageCreate" was null or undefined when calling createNotificationTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/messages/templates`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TemplateMessageCreateToJSON(requestParameters['templateMessageCreate']),
        };
    }

    /**
     * Create and configure a new template by providing the necessary details in the request body.
     * Create a new template
     */
    async createNotificationTemplateRaw(requestParameters: CreateNotificationTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        const requestOptions = await this.createNotificationTemplateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * Create and configure a new template by providing the necessary details in the request body.
     * Create a new template
     */
    async createNotificationTemplate(requestParameters: CreateNotificationTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.createNotificationTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteNotificationTemplate without sending the request
     */
    async deleteNotificationTemplateRequestOpts(requestParameters: DeleteNotificationTemplateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling deleteNotificationTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/messages/templates/{templateId}`;
        urlPath = urlPath.replace('{templateId}', encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a template from the system by providing its unique ID.
     * Delete a template
     */
    async deleteNotificationTemplateRaw(requestParameters: DeleteNotificationTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.deleteNotificationTemplateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Remove a template from the system by providing its unique ID.
     * Delete a template
     */
    async deleteNotificationTemplate(requestParameters: DeleteNotificationTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.deleteNotificationTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNotificationTemplate without sending the request
     */
    async getNotificationTemplateRequestOpts(requestParameters: GetNotificationTemplateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling getNotificationTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/messages/templates/{templateId}`;
        urlPath = urlPath.replace('{templateId}', encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch the details of a specific template by providing its unique ID.
     * Retrieve a specific template
     */
    async getNotificationTemplateRaw(requestParameters: GetNotificationTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplateMessage>> {
        const requestOptions = await this.getNotificationTemplateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplateMessageFromJSON(jsonValue));
    }

    /**
     * Fetch the details of a specific template by providing its unique ID.
     * Retrieve a specific template
     */
    async getNotificationTemplate(requestParameters: GetNotificationTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplateMessage> {
        const response = await this.getNotificationTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMessages without sending the request
     */
    async listMessagesRequestOpts(requestParameters: ListMessagesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['autocomplete'] != null) {
            queryParameters['autocomplete'] = requestParameters['autocomplete'];
        }

        if (requestParameters['next'] != null) {
            queryParameters['next'] = requestParameters['next'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['templateId'] != null) {
            queryParameters['template_id'] = requestParameters['templateId'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        if (requestParameters['system'] != null) {
            queryParameters['system'] = requestParameters['system'];
        }

        if (requestParameters['actionType'] != null) {
            queryParameters['action_type'] = requestParameters['actionType'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['whenCreated$gt'] != null) {
            queryParameters['when_created[$gt]'] = (requestParameters['whenCreated$gt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lt'] != null) {
            queryParameters['when_created[$lt]'] = (requestParameters['whenCreated$lt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$gte'] != null) {
            queryParameters['when_created[$gte]'] = (requestParameters['whenCreated$gte'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lte'] != null) {
            queryParameters['when_created[$lte]'] = (requestParameters['whenCreated$lte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/messages`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch a list of messages with optional filters like prefix, public, unpublished, and pagination using limit and next token.
     * Retrieve a list of message
     */
    async listMessagesRaw(requestParameters: ListMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListNotificationMessagesOut>> {
        const requestOptions = await this.listMessagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListNotificationMessagesOutFromJSON(jsonValue));
    }

    /**
     * Fetch a list of messages with optional filters like prefix, public, unpublished, and pagination using limit and next token.
     * Retrieve a list of message
     */
    async listMessages(requestParameters: ListMessagesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListNotificationMessagesOut> {
        const response = await this.listMessagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listNotificationTemplates without sending the request
     */
    async listNotificationTemplatesRequestOpts(requestParameters: ListNotificationTemplatesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['next'] != null) {
            queryParameters['next'] = requestParameters['next'];
        }

        if (requestParameters['autocomplete'] != null) {
            queryParameters['autocomplete'] = requestParameters['autocomplete'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        if (requestParameters['system'] != null) {
            queryParameters['system'] = requestParameters['system'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['whenCreated$gt'] != null) {
            queryParameters['when_created[$gt]'] = (requestParameters['whenCreated$gt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lt'] != null) {
            queryParameters['when_created[$lt]'] = (requestParameters['whenCreated$lt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$gte'] != null) {
            queryParameters['when_created[$gte]'] = (requestParameters['whenCreated$gte'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lte'] != null) {
            queryParameters['when_created[$lte]'] = (requestParameters['whenCreated$lte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/messages/templates`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch a list of templates with optional filters like prefix, public, unpublished, and pagination using limit and next token.
     * Retrieve a list of templates
     */
    async listNotificationTemplatesRaw(requestParameters: ListNotificationTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListNotificationTemplatesOut>> {
        const requestOptions = await this.listNotificationTemplatesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListNotificationTemplatesOutFromJSON(jsonValue));
    }

    /**
     * Fetch a list of templates with optional filters like prefix, public, unpublished, and pagination using limit and next token.
     * Retrieve a list of templates
     */
    async listNotificationTemplates(requestParameters: ListNotificationTemplatesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListNotificationTemplatesOut> {
        const response = await this.listNotificationTemplatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendMessage without sending the request
     */
    async sendMessageRequestOpts(requestParameters: SendMessageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['messageCreate'] == null) {
            throw new runtime.RequiredError(
                'messageCreate',
                'Required parameter "messageCreate" was null or undefined when calling sendMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/messages/send`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MessageCreateToJSON(requestParameters['messageCreate']),
        };
    }

    /**
     * Send a new message by providing the necessary details in the request body.
     * Send a new message
     */
    async sendMessageRaw(requestParameters: SendMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        const requestOptions = await this.sendMessageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * Send a new message by providing the necessary details in the request body.
     * Send a new message
     */
    async sendMessage(requestParameters: SendMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.sendMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateNotificationTemplate without sending the request
     */
    async updateNotificationTemplateRequestOpts(requestParameters: UpdateNotificationTemplateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling updateNotificationTemplate().'
            );
        }

        if (requestParameters['templateMessageUpdate'] == null) {
            throw new runtime.RequiredError(
                'templateMessageUpdate',
                'Required parameter "templateMessageUpdate" was null or undefined when calling updateNotificationTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/messages/templates/{templateId}`;
        urlPath = urlPath.replace('{templateId}', encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TemplateMessageUpdateToJSON(requestParameters['templateMessageUpdate']),
        };
    }

    /**
     * Modify the properties of an existing template by providing its unique ID and updated details.
     * Update an existing template
     */
    async updateNotificationTemplateRaw(requestParameters: UpdateNotificationTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.updateNotificationTemplateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Modify the properties of an existing template by providing its unique ID and updated details.
     * Update an existing template
     */
    async updateNotificationTemplate(requestParameters: UpdateNotificationTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.updateNotificationTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListMessagesOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListMessagesOrderEnum = typeof ListMessagesOrderEnum[keyof typeof ListMessagesOrderEnum];
/**
 * @export
 */
export const ListNotificationTemplatesOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListNotificationTemplatesOrderEnum = typeof ListNotificationTemplatesOrderEnum[keyof typeof ListNotificationTemplatesOrderEnum];
