// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DisplayVariant,
    DisplayVariantFromJSON,
    DisplayVariantToJSON,
} from '../models/DisplayVariant';
import {
    type ListObjectAttributesOut,
    ListObjectAttributesOutFromJSON,
    ListObjectAttributesOutToJSON,
} from '../models/ListObjectAttributesOut';
import {
    type ListPublicSmartObjectsOut,
    ListPublicSmartObjectsOutFromJSON,
    ListPublicSmartObjectsOutToJSON,
} from '../models/ListPublicSmartObjectsOut';
import {
    type ListSmartObjectsOut,
    ListSmartObjectsOutFromJSON,
    ListSmartObjectsOutToJSON,
} from '../models/ListSmartObjectsOut';
import {
    type ListStateChangesOut,
    ListStateChangesOutFromJSON,
    ListStateChangesOutToJSON,
} from '../models/ListStateChangesOut';
import {
    type ModelError,
    ModelErrorFromJSON,
    ModelErrorToJSON,
} from '../models/ModelError';
import {
    type ObjectsCreationStatsOut,
    ObjectsCreationStatsOutFromJSON,
    ObjectsCreationStatsOutToJSON,
} from '../models/ObjectsCreationStatsOut';
import {
    type ObjectsStatsOut,
    ObjectsStatsOutFromJSON,
    ObjectsStatsOutToJSON,
} from '../models/ObjectsStatsOut';
import {
    type PublicSmartObject,
    PublicSmartObjectFromJSON,
    PublicSmartObjectToJSON,
} from '../models/PublicSmartObject';
import {
    type PublicSmartObjectMetadata,
    PublicSmartObjectMetadataFromJSON,
    PublicSmartObjectMetadataToJSON,
} from '../models/PublicSmartObjectMetadata';
import {
    type SmartObject,
    SmartObjectFromJSON,
    SmartObjectToJSON,
} from '../models/SmartObject';

export interface GetObjectByIdRequest {
    objectId: string;
}

export interface GetObjectByIdPublicRequest {
    objectId: string;
}

export interface GetObjectCreationStatsRequest {
    orgId?: string;
    interval?: GetObjectCreationStatsIntervalEnum;
    timeRange?: GetObjectCreationStatsTimeRangeEnum;
    limit?: number;
    whenCreated$gt?: Date;
    whenCreated$lt?: Date;
    whenCreated$gte?: Date;
    whenCreated$lte?: Date;
    templateId?: string;
    signer?: string;
}

export interface GetObjectMetadataByIdPublicRequest {
    objectId: string;
}

export interface GetObjectStatsRequest {
    orgId?: string;
    timeRange?: GetObjectStatsTimeRangeEnum;
    whenCreated$gt?: Date;
    whenCreated$lt?: Date;
    whenCreated$gte?: Date;
    whenCreated$lte?: Date;
    templateId?: string;
    walletId?: string;
}

export interface ListObjectAttributesRequest {
    objectId: string;
}

export interface ListObjectsRequest {
    id?: string;
    orgId?: string;
    autocomplete?: string;
    limit?: number;
    next?: string;
    order?: ListObjectsOrderEnum;
    sortBy?: string;
    faces?: boolean;
    include?: Array<ListObjectsIncludeEnum>;
    displayVariant?: ListObjectsDisplayVariantEnum;
    actions?: boolean;
    owner?: string;
    fqdn?: string;
    dropped?: boolean;
    geoHash?: string;
    templateId?: string;
    whenCreated$gt?: Date;
    whenCreated$gte?: Date;
    whenCreated$lt?: Date;
    whenCreated$lte?: Date;
    whenModified$gt?: Date;
    whenModified$lt?: Date;
    whenModified$gte?: Date;
    whenModified$lte?: Date;
}

export interface ListObjectsPublicRequest {
    id?: string;
    limit?: number;
    autocomplete?: string;
    next?: string;
    order?: ListObjectsPublicOrderEnum;
    sortBy?: string;
    faces?: boolean;
    include?: Array<ListObjectsPublicIncludeEnum>;
    displayVariant?: ListObjectsPublicDisplayVariantEnum;
    actions?: boolean;
    owner?: string;
    dropped?: boolean;
    geoHash?: string;
    templateId?: string;
    whenCreated$gt?: Date;
    whenCreated$lt?: Date;
    whenCreated$gte?: Date;
    whenCreated$lte?: Date;
    whenModified$gt?: Date;
    whenModified$lt?: Date;
    whenModified$gte?: Date;
    whenModified$lte?: Date;
}

export interface ListStateChangesRequest {
    objectId: string;
    id?: string;
    orgId?: string;
    autocomplete?: string;
    limit?: number;
    next?: string;
    order?: ListStateChangesOrderEnum;
    sortBy?: string;
    walletId?: string;
    actionId?: string;
    batchId?: string;
    changeType?: string;
    actionType?: string;
    nonce$gt?: number;
    nonce$lt?: number;
    prevStateRoot?: string;
    nextStateRoot?: string;
    whenCreated$gt?: Date;
    whenCreated$lt?: Date;
    whenCreated$gte?: Date;
    whenCreated$lte?: Date;
}

export interface RenderObjectDisplayByIdPublicRequest {
    objectId: string;
    variant: DisplayVariant;
}

export interface RenderObjectViewByIdPublicRequest {
    objectId: string;
}

/**
 *
 */
export class ObjectsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getObjectById without sending the request
     */
    async getObjectByIdRequestOpts(requestParameters: GetObjectByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['objectId'] == null) {
            throw new runtime.RequiredError(
                'objectId',
                'Required parameter "objectId" was null or undefined when calling getObjectById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/objects/{objectId}`;
        urlPath = urlPath.replace('{objectId}', encodeURIComponent(String(requestParameters['objectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve detailed information about a specific smart object by its unique identifier. This endpoint returns comprehensive object data including faces, actions, metadata, and current state information.
     * Get object
     */
    async getObjectByIdRaw(requestParameters: GetObjectByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmartObject>> {
        const requestOptions = await this.getObjectByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SmartObjectFromJSON(jsonValue));
    }

    /**
     * Retrieve detailed information about a specific smart object by its unique identifier. This endpoint returns comprehensive object data including faces, actions, metadata, and current state information.
     * Get object
     */
    async getObjectById(requestParameters: GetObjectByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmartObject> {
        const response = await this.getObjectByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getObjectByIdPublic without sending the request
     */
    async getObjectByIdPublicRequestOpts(requestParameters: GetObjectByIdPublicRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['objectId'] == null) {
            throw new runtime.RequiredError(
                'objectId',
                'Required parameter "objectId" was null or undefined when calling getObjectByIdPublic().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/objects/{objectId}`;
        urlPath = urlPath.replace('{objectId}', encodeURIComponent(String(requestParameters['objectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve detailed information about a specific smart object by its unique identifier. This endpoint returns comprehensive object data including faces, actions, metadata, and current state information.
     * Get Object by ID Public
     */
    async getObjectByIdPublicRaw(requestParameters: GetObjectByIdPublicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicSmartObject>> {
        const requestOptions = await this.getObjectByIdPublicRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicSmartObjectFromJSON(jsonValue));
    }

    /**
     * Retrieve detailed information about a specific smart object by its unique identifier. This endpoint returns comprehensive object data including faces, actions, metadata, and current state information.
     * Get Object by ID Public
     */
    async getObjectByIdPublic(requestParameters: GetObjectByIdPublicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicSmartObject> {
        const response = await this.getObjectByIdPublicRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getObjectCreationStats without sending the request
     */
    async getObjectCreationStatsRequestOpts(requestParameters: GetObjectCreationStatsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['org_id'] = requestParameters['orgId'];
        }

        if (requestParameters['interval'] != null) {
            queryParameters['interval'] = requestParameters['interval'];
        }

        if (requestParameters['timeRange'] != null) {
            queryParameters['time_range'] = requestParameters['timeRange'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['whenCreated$gt'] != null) {
            queryParameters['when_created[$gt]'] = (requestParameters['whenCreated$gt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lt'] != null) {
            queryParameters['when_created[$lt]'] = (requestParameters['whenCreated$lt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$gte'] != null) {
            queryParameters['when_created[$gte]'] = (requestParameters['whenCreated$gte'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lte'] != null) {
            queryParameters['when_created[$lte]'] = (requestParameters['whenCreated$lte'] as any).toISOString();
        }

        if (requestParameters['templateId'] != null) {
            queryParameters['template_id'] = requestParameters['templateId'];
        }

        if (requestParameters['signer'] != null) {
            queryParameters['signer'] = requestParameters['signer'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/stats/objects/creation`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve time-series data about smart object creation patterns and trends. This endpoint provides detailed analytics on object instantiation over time, including creation velocity, template popularity, and temporal distribution of new object generation.
     * Get object creation statistics over time
     */
    async getObjectCreationStatsRaw(requestParameters: GetObjectCreationStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectsCreationStatsOut>> {
        const requestOptions = await this.getObjectCreationStatsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectsCreationStatsOutFromJSON(jsonValue));
    }

    /**
     * Retrieve time-series data about smart object creation patterns and trends. This endpoint provides detailed analytics on object instantiation over time, including creation velocity, template popularity, and temporal distribution of new object generation.
     * Get object creation statistics over time
     */
    async getObjectCreationStats(requestParameters: GetObjectCreationStatsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectsCreationStatsOut> {
        const response = await this.getObjectCreationStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getObjectMetadataByIdPublic without sending the request
     */
    async getObjectMetadataByIdPublicRequestOpts(requestParameters: GetObjectMetadataByIdPublicRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['objectId'] == null) {
            throw new runtime.RequiredError(
                'objectId',
                'Required parameter "objectId" was null or undefined when calling getObjectMetadataByIdPublic().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/objects/{objectId}/metadata`;
        urlPath = urlPath.replace('{objectId}', encodeURIComponent(String(requestParameters['objectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve metadata information about a specific smart object by its unique identifier. This endpoint returns metadata details including creation timestamps, versioning, and other relevant metadata attributes.
     * Get public object metadata
     */
    async getObjectMetadataByIdPublicRaw(requestParameters: GetObjectMetadataByIdPublicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicSmartObjectMetadata>> {
        const requestOptions = await this.getObjectMetadataByIdPublicRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicSmartObjectMetadataFromJSON(jsonValue));
    }

    /**
     * Retrieve metadata information about a specific smart object by its unique identifier. This endpoint returns metadata details including creation timestamps, versioning, and other relevant metadata attributes.
     * Get public object metadata
     */
    async getObjectMetadataByIdPublic(requestParameters: GetObjectMetadataByIdPublicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicSmartObjectMetadata> {
        const response = await this.getObjectMetadataByIdPublicRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getObjectStats without sending the request
     */
    async getObjectStatsRequestOpts(requestParameters: GetObjectStatsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['org_id'] = requestParameters['orgId'];
        }

        if (requestParameters['timeRange'] != null) {
            queryParameters['time_range'] = requestParameters['timeRange'];
        }

        if (requestParameters['whenCreated$gt'] != null) {
            queryParameters['when_created[$gt]'] = (requestParameters['whenCreated$gt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lt'] != null) {
            queryParameters['when_created[$lt]'] = (requestParameters['whenCreated$lt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$gte'] != null) {
            queryParameters['when_created[$gte]'] = (requestParameters['whenCreated$gte'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lte'] != null) {
            queryParameters['when_created[$lte]'] = (requestParameters['whenCreated$lte'] as any).toISOString();
        }

        if (requestParameters['templateId'] != null) {
            queryParameters['template_id'] = requestParameters['templateId'];
        }

        if (requestParameters['walletId'] != null) {
            queryParameters['wallet_id'] = requestParameters['walletId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/stats/objects`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve comprehensive statistics about smart objects and their usage patterns. This endpoint provides aggregate data including total object counts, creation trends, template distribution, and ownership analytics over specified time ranges for platform insights and reporting.
     * Get object statistics
     */
    async getObjectStatsRaw(requestParameters: GetObjectStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectsStatsOut>> {
        const requestOptions = await this.getObjectStatsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectsStatsOutFromJSON(jsonValue));
    }

    /**
     * Retrieve comprehensive statistics about smart objects and their usage patterns. This endpoint provides aggregate data including total object counts, creation trends, template distribution, and ownership analytics over specified time ranges for platform insights and reporting.
     * Get object statistics
     */
    async getObjectStats(requestParameters: GetObjectStatsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectsStatsOut> {
        const response = await this.getObjectStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listObjectAttributes without sending the request
     */
    async listObjectAttributesRequestOpts(requestParameters: ListObjectAttributesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['objectId'] == null) {
            throw new runtime.RequiredError(
                'objectId',
                'Required parameter "objectId" was null or undefined when calling listObjectAttributes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/objects/{objectId}/attributes`;
        urlPath = urlPath.replace('{objectId}', encodeURIComponent(String(requestParameters['objectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve the current attribute projection for a smart object.
     * List object attributes
     */
    async listObjectAttributesRaw(requestParameters: ListObjectAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListObjectAttributesOut>> {
        const requestOptions = await this.listObjectAttributesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListObjectAttributesOutFromJSON(jsonValue));
    }

    /**
     * Retrieve the current attribute projection for a smart object.
     * List object attributes
     */
    async listObjectAttributes(requestParameters: ListObjectAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListObjectAttributesOut> {
        const response = await this.listObjectAttributesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listObjects without sending the request
     */
    async listObjectsRequestOpts(requestParameters: ListObjectsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['orgId'] != null) {
            queryParameters['org_id'] = requestParameters['orgId'];
        }

        if (requestParameters['autocomplete'] != null) {
            queryParameters['autocomplete'] = requestParameters['autocomplete'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['next'] != null) {
            queryParameters['next'] = requestParameters['next'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['faces'] != null) {
            queryParameters['faces'] = requestParameters['faces'];
        }

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['displayVariant'] != null) {
            queryParameters['display_variant'] = requestParameters['displayVariant'];
        }

        if (requestParameters['actions'] != null) {
            queryParameters['actions'] = requestParameters['actions'];
        }

        if (requestParameters['owner'] != null) {
            queryParameters['owner'] = requestParameters['owner'];
        }

        if (requestParameters['fqdn'] != null) {
            queryParameters['fqdn'] = requestParameters['fqdn'];
        }

        if (requestParameters['dropped'] != null) {
            queryParameters['dropped'] = requestParameters['dropped'];
        }

        if (requestParameters['geoHash'] != null) {
            queryParameters['geo_hash'] = requestParameters['geoHash'];
        }

        if (requestParameters['templateId'] != null) {
            queryParameters['template_id'] = requestParameters['templateId'];
        }

        if (requestParameters['whenCreated$gt'] != null) {
            queryParameters['when_created[$gt]'] = (requestParameters['whenCreated$gt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$gte'] != null) {
            queryParameters['when_created[$gte]'] = (requestParameters['whenCreated$gte'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lt'] != null) {
            queryParameters['when_created[$lt]'] = (requestParameters['whenCreated$lt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lte'] != null) {
            queryParameters['when_created[$lte]'] = (requestParameters['whenCreated$lte'] as any).toISOString();
        }

        if (requestParameters['whenModified$gt'] != null) {
            queryParameters['when_modified[$gt]'] = (requestParameters['whenModified$gt'] as any).toISOString();
        }

        if (requestParameters['whenModified$lt'] != null) {
            queryParameters['when_modified[$lt]'] = (requestParameters['whenModified$lt'] as any).toISOString();
        }

        if (requestParameters['whenModified$gte'] != null) {
            queryParameters['when_modified[$gte]'] = (requestParameters['whenModified$gte'] as any).toISOString();
        }

        if (requestParameters['whenModified$lte'] != null) {
            queryParameters['when_modified[$lte]'] = (requestParameters['whenModified$lte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/objects`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a paginated list of smart objects accessible to the authenticated user. This endpoint supports comprehensive filtering by various criteria including object type, ownership, location, template associations, and temporal ranges. Objects can be filtered by faces, actions, ownership, geographical location, and creation/modification timestamps.
     * List objects
     */
    async listObjectsRaw(requestParameters: ListObjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSmartObjectsOut>> {
        const requestOptions = await this.listObjectsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListSmartObjectsOutFromJSON(jsonValue));
    }

    /**
     * Retrieve a paginated list of smart objects accessible to the authenticated user. This endpoint supports comprehensive filtering by various criteria including object type, ownership, location, template associations, and temporal ranges. Objects can be filtered by faces, actions, ownership, geographical location, and creation/modification timestamps.
     * List objects
     */
    async listObjects(requestParameters: ListObjectsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSmartObjectsOut> {
        const response = await this.listObjectsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listObjectsPublic without sending the request
     */
    async listObjectsPublicRequestOpts(requestParameters: ListObjectsPublicRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['autocomplete'] != null) {
            queryParameters['autocomplete'] = requestParameters['autocomplete'];
        }

        if (requestParameters['next'] != null) {
            queryParameters['next'] = requestParameters['next'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['faces'] != null) {
            queryParameters['faces'] = requestParameters['faces'];
        }

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['displayVariant'] != null) {
            queryParameters['display_variant'] = requestParameters['displayVariant'];
        }

        if (requestParameters['actions'] != null) {
            queryParameters['actions'] = requestParameters['actions'];
        }

        if (requestParameters['owner'] != null) {
            queryParameters['owner'] = requestParameters['owner'];
        }

        if (requestParameters['dropped'] != null) {
            queryParameters['dropped'] = requestParameters['dropped'];
        }

        if (requestParameters['geoHash'] != null) {
            queryParameters['geo_hash'] = requestParameters['geoHash'];
        }

        if (requestParameters['templateId'] != null) {
            queryParameters['template_id'] = requestParameters['templateId'];
        }

        if (requestParameters['whenCreated$gt'] != null) {
            queryParameters['when_created[$gt]'] = (requestParameters['whenCreated$gt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lt'] != null) {
            queryParameters['when_created[$lt]'] = (requestParameters['whenCreated$lt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$gte'] != null) {
            queryParameters['when_created[$gte]'] = (requestParameters['whenCreated$gte'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lte'] != null) {
            queryParameters['when_created[$lte]'] = (requestParameters['whenCreated$lte'] as any).toISOString();
        }

        if (requestParameters['whenModified$gt'] != null) {
            queryParameters['when_modified[$gt]'] = (requestParameters['whenModified$gt'] as any).toISOString();
        }

        if (requestParameters['whenModified$lt'] != null) {
            queryParameters['when_modified[$lt]'] = (requestParameters['whenModified$lt'] as any).toISOString();
        }

        if (requestParameters['whenModified$gte'] != null) {
            queryParameters['when_modified[$gte]'] = (requestParameters['whenModified$gte'] as any).toISOString();
        }

        if (requestParameters['whenModified$lte'] != null) {
            queryParameters['when_modified[$lte]'] = (requestParameters['whenModified$lte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/objects`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a paginated list of smart objects accessible to the public. This endpoint supports comprehensive filtering by various criteria including object type, ownership, location, template associations, and temporal ranges. Objects can be filtered by faces, actions, ownership, geographical location, and creation/modification timestamps.
     * List Objects Public
     */
    async listObjectsPublicRaw(requestParameters: ListObjectsPublicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPublicSmartObjectsOut>> {
        const requestOptions = await this.listObjectsPublicRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPublicSmartObjectsOutFromJSON(jsonValue));
    }

    /**
     * Retrieve a paginated list of smart objects accessible to the public. This endpoint supports comprehensive filtering by various criteria including object type, ownership, location, template associations, and temporal ranges. Objects can be filtered by faces, actions, ownership, geographical location, and creation/modification timestamps.
     * List Objects Public
     */
    async listObjectsPublic(requestParameters: ListObjectsPublicRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPublicSmartObjectsOut> {
        const response = await this.listObjectsPublicRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listStateChanges without sending the request
     */
    async listStateChangesRequestOpts(requestParameters: ListStateChangesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['objectId'] == null) {
            throw new runtime.RequiredError(
                'objectId',
                'Required parameter "objectId" was null or undefined when calling listStateChanges().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['orgId'] != null) {
            queryParameters['org_id'] = requestParameters['orgId'];
        }

        if (requestParameters['autocomplete'] != null) {
            queryParameters['autocomplete'] = requestParameters['autocomplete'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['next'] != null) {
            queryParameters['next'] = requestParameters['next'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['walletId'] != null) {
            queryParameters['wallet_id'] = requestParameters['walletId'];
        }

        if (requestParameters['actionId'] != null) {
            queryParameters['action_id'] = requestParameters['actionId'];
        }

        if (requestParameters['batchId'] != null) {
            queryParameters['batch_id'] = requestParameters['batchId'];
        }

        if (requestParameters['changeType'] != null) {
            queryParameters['change_type'] = requestParameters['changeType'];
        }

        if (requestParameters['actionType'] != null) {
            queryParameters['action_type'] = requestParameters['actionType'];
        }

        if (requestParameters['nonce$gt'] != null) {
            queryParameters['nonce[$gt]'] = requestParameters['nonce$gt'];
        }

        if (requestParameters['nonce$lt'] != null) {
            queryParameters['nonce[$lt]'] = requestParameters['nonce$lt'];
        }

        if (requestParameters['prevStateRoot'] != null) {
            queryParameters['prev_state_root'] = requestParameters['prevStateRoot'];
        }

        if (requestParameters['nextStateRoot'] != null) {
            queryParameters['next_state_root'] = requestParameters['nextStateRoot'];
        }

        if (requestParameters['whenCreated$gt'] != null) {
            queryParameters['when_created[$gt]'] = (requestParameters['whenCreated$gt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lt'] != null) {
            queryParameters['when_created[$lt]'] = (requestParameters['whenCreated$lt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$gte'] != null) {
            queryParameters['when_created[$gte]'] = (requestParameters['whenCreated$gte'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lte'] != null) {
            queryParameters['when_created[$lte]'] = (requestParameters['whenCreated$lte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/objects/{objectId}/state-changes`;
        urlPath = urlPath.replace('{objectId}', encodeURIComponent(String(requestParameters['objectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a paginated list of state changes for a specific smart object. This endpoint provides access to the complete history of state modifications including action types, wallet interactions, nonce values, and state root transitions. State changes can be filtered by various criteria including wallet ID, action ID, change type, and temporal ranges.
     * List state changes
     */
    async listStateChangesRaw(requestParameters: ListStateChangesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListStateChangesOut>> {
        const requestOptions = await this.listStateChangesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListStateChangesOutFromJSON(jsonValue));
    }

    /**
     * Retrieve a paginated list of state changes for a specific smart object. This endpoint provides access to the complete history of state modifications including action types, wallet interactions, nonce values, and state root transitions. State changes can be filtered by various criteria including wallet ID, action ID, change type, and temporal ranges.
     * List state changes
     */
    async listStateChanges(requestParameters: ListStateChangesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListStateChangesOut> {
        const response = await this.listStateChangesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for renderObjectDisplayByIdPublic without sending the request
     */
    async renderObjectDisplayByIdPublicRequestOpts(requestParameters: RenderObjectDisplayByIdPublicRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['objectId'] == null) {
            throw new runtime.RequiredError(
                'objectId',
                'Required parameter "objectId" was null or undefined when calling renderObjectDisplayByIdPublic().'
            );
        }

        if (requestParameters['variant'] == null) {
            throw new runtime.RequiredError(
                'variant',
                'Required parameter "variant" was null or undefined when calling renderObjectDisplayByIdPublic().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/objects/{objectId}/display/{variant}`;
        urlPath = urlPath.replace('{objectId}', encodeURIComponent(String(requestParameters['objectId'])));
        urlPath = urlPath.replace('{variant}', encodeURIComponent(String(requestParameters['variant'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Render a smart object\'s assigned face using its public data projection. Variant lookup falls back to the face\'s default view and then legacy v1 content.
     * Render a public object display variant
     */
    async renderObjectDisplayByIdPublicRaw(requestParameters: RenderObjectDisplayByIdPublicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.renderObjectDisplayByIdPublicRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Render a smart object\'s assigned face using its public data projection. Variant lookup falls back to the face\'s default view and then legacy v1 content.
     * Render a public object display variant
     */
    async renderObjectDisplayByIdPublic(requestParameters: RenderObjectDisplayByIdPublicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.renderObjectDisplayByIdPublicRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for renderObjectViewByIdPublic without sending the request
     * @deprecated
     */
    async renderObjectViewByIdPublicRequestOpts(requestParameters: RenderObjectViewByIdPublicRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['objectId'] == null) {
            throw new runtime.RequiredError(
                'objectId',
                'Required parameter "objectId" was null or undefined when calling renderObjectViewByIdPublic().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/objects/{objectId}/render`;
        urlPath = urlPath.replace('{objectId}', encodeURIComponent(String(requestParameters['objectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Legacy v1 alias for /public/objects/{objectId}/display/detail.
     * Render a public object
     * @deprecated
     */
    async renderObjectViewByIdPublicRaw(requestParameters: RenderObjectViewByIdPublicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.renderObjectViewByIdPublicRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Legacy v1 alias for /public/objects/{objectId}/display/detail.
     * Render a public object
     * @deprecated
     */
    async renderObjectViewByIdPublic(requestParameters: RenderObjectViewByIdPublicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.renderObjectViewByIdPublicRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetObjectCreationStatsIntervalEnum = {
    Hour: 'hour',
    Day: 'day',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type GetObjectCreationStatsIntervalEnum = typeof GetObjectCreationStatsIntervalEnum[keyof typeof GetObjectCreationStatsIntervalEnum];
/**
 * @export
 */
export const GetObjectCreationStatsTimeRangeEnum = {
    All: 'all',
    Today: 'today',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type GetObjectCreationStatsTimeRangeEnum = typeof GetObjectCreationStatsTimeRangeEnum[keyof typeof GetObjectCreationStatsTimeRangeEnum];
/**
 * @export
 */
export const GetObjectStatsTimeRangeEnum = {
    All: 'all',
    Today: 'today',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type GetObjectStatsTimeRangeEnum = typeof GetObjectStatsTimeRangeEnum[keyof typeof GetObjectStatsTimeRangeEnum];
/**
 * @export
 */
export const ListObjectsOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListObjectsOrderEnum = typeof ListObjectsOrderEnum[keyof typeof ListObjectsOrderEnum];
/**
 * @export
 */
export const ListObjectsIncludeEnum = {
    Display: 'display'
} as const;
export type ListObjectsIncludeEnum = typeof ListObjectsIncludeEnum[keyof typeof ListObjectsIncludeEnum];
/**
 * @export
 */
export const ListObjectsDisplayVariantEnum = {
    Card: 'card',
    Detail: 'detail',
    Share: 'share'
} as const;
export type ListObjectsDisplayVariantEnum = typeof ListObjectsDisplayVariantEnum[keyof typeof ListObjectsDisplayVariantEnum];
/**
 * @export
 */
export const ListObjectsPublicOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListObjectsPublicOrderEnum = typeof ListObjectsPublicOrderEnum[keyof typeof ListObjectsPublicOrderEnum];
/**
 * @export
 */
export const ListObjectsPublicIncludeEnum = {
    Display: 'display'
} as const;
export type ListObjectsPublicIncludeEnum = typeof ListObjectsPublicIncludeEnum[keyof typeof ListObjectsPublicIncludeEnum];
/**
 * @export
 */
export const ListObjectsPublicDisplayVariantEnum = {
    Card: 'card',
    Detail: 'detail',
    Share: 'share'
} as const;
export type ListObjectsPublicDisplayVariantEnum = typeof ListObjectsPublicDisplayVariantEnum[keyof typeof ListObjectsPublicDisplayVariantEnum];
/**
 * @export
 */
export const ListStateChangesOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListStateChangesOrderEnum = typeof ListStateChangesOrderEnum[keyof typeof ListStateChangesOrderEnum];
