// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * DualOrg API
 * DualOrg API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AuthChallenge,
    AuthChallengeFromJSON,
    AuthChallengeToJSON,
} from '../models/AuthChallenge';
import {
    type EoaIn,
    EoaInFromJSON,
    EoaInToJSON,
} from '../models/EoaIn';
import {
    type LoginIn,
    LoginInFromJSON,
    LoginInToJSON,
} from '../models/LoginIn';
import {
    type LoginOut,
    LoginOutFromJSON,
    LoginOutToJSON,
} from '../models/LoginOut';
import {
    type ModelError,
    ModelErrorFromJSON,
    ModelErrorToJSON,
} from '../models/ModelError';
import {
    type PasskeyLoginOptionsOut,
    PasskeyLoginOptionsOutFromJSON,
    PasskeyLoginOptionsOutToJSON,
} from '../models/PasskeyLoginOptionsOut';
import {
    type PasskeyLoginVerifyIn,
    PasskeyLoginVerifyInFromJSON,
    PasskeyLoginVerifyInToJSON,
} from '../models/PasskeyLoginVerifyIn';
import {
    type PasskeyRegisterOptionsOut,
    PasskeyRegisterOptionsOutFromJSON,
    PasskeyRegisterOptionsOutToJSON,
} from '../models/PasskeyRegisterOptionsOut';
import {
    type PasskeyRegisterVerifyIn,
    PasskeyRegisterVerifyInFromJSON,
    PasskeyRegisterVerifyInToJSON,
} from '../models/PasskeyRegisterVerifyIn';
import {
    type RefreshTokenOut,
    RefreshTokenOutFromJSON,
    RefreshTokenOutToJSON,
} from '../models/RefreshTokenOut';
import {
    type RequestOTPCodeIn,
    RequestOTPCodeInFromJSON,
    RequestOTPCodeInToJSON,
} from '../models/RequestOTPCodeIn';
import {
    type ResetCodeIn,
    ResetCodeInFromJSON,
    ResetCodeInToJSON,
} from '../models/ResetCodeIn';
import {
    type ResetPasswordIn,
    ResetPasswordInFromJSON,
    ResetPasswordInToJSON,
} from '../models/ResetPasswordIn';
import {
    type SetNewPasswordIn,
    SetNewPasswordInFromJSON,
    SetNewPasswordInToJSON,
} from '../models/SetNewPasswordIn';
import {
    type VerifyIn,
    VerifyInFromJSON,
    VerifyInToJSON,
} from '../models/VerifyIn';
import {
    type Wallet,
    WalletFromJSON,
    WalletToJSON,
} from '../models/Wallet';
import {
    type WalletCreate,
    WalletCreateFromJSON,
    WalletCreateToJSON,
} from '../models/WalletCreate';
import {
    type WalletUpdate,
    WalletUpdateFromJSON,
    WalletUpdateToJSON,
} from '../models/WalletUpdate';
import {
    type WalletsRegistrationStatsOut,
    WalletsRegistrationStatsOutFromJSON,
    WalletsRegistrationStatsOutToJSON,
} from '../models/WalletsRegistrationStatsOut';
import {
    type WalletsStatsOut,
    WalletsStatsOutFromJSON,
    WalletsStatsOutToJSON,
} from '../models/WalletsStatsOut';
import {
    type WalletsTotalStatsOut,
    WalletsTotalStatsOutFromJSON,
    WalletsTotalStatsOutToJSON,
} from '../models/WalletsTotalStatsOut';

export interface ConnectEoaRequest {
    eoaIn: EoaIn;
}

export interface GetWalletsRegistrationStatsRequest {
    orgId?: string;
    interval?: GetWalletsRegistrationStatsIntervalEnum;
    timeRange?: GetWalletsRegistrationStatsTimeRangeEnum;
    limit?: number;
    activated?: boolean;
    whenCreated$gt?: Date;
    whenCreated$lt?: Date;
    whenCreated$gte?: Date;
    whenCreated$lte?: Date;
}

export interface GetWalletsStatsRequest {
    orgId?: string;
    timeRange?: GetWalletsStatsTimeRangeEnum;
    whenCreated$gt?: Date;
    whenCreated$lt?: Date;
    whenCreated$gte?: Date;
    whenCreated$lte?: Date;
}

export interface GetWalletsTotalStatsRequest {
    orgId?: string;
    interval?: GetWalletsTotalStatsIntervalEnum;
    timeRange?: GetWalletsTotalStatsTimeRangeEnum;
    limit?: number;
    whenCreated$gt?: Date;
    whenCreated$lt?: Date;
    whenCreated$gte?: Date;
    whenCreated$lte?: Date;
}

export interface LoginWalletRequest {
    loginIn: LoginIn;
}

export interface PasskeyLoginOptionsRequest {
    body?: object;
}

export interface PasskeyLoginVerifyRequest {
    passkeyLoginVerifyIn: PasskeyLoginVerifyIn;
}

export interface PasskeyRegisterVerifyRequest {
    passkeyRegisterVerifyIn: PasskeyRegisterVerifyIn;
}

export interface RegisterWalletRequest {
    walletCreate: WalletCreate;
}

export interface RequestOTPCodeRequest {
    requestOTPCodeIn: RequestOTPCodeIn;
}

export interface RequestVerificationCodeRequest {
    resetCodeIn: ResetCodeIn;
}

export interface ResetPasswordRequest {
    resetPasswordIn: ResetPasswordIn;
}

export interface SetNewPasswordRequest {
    setNewPasswordIn: SetNewPasswordIn;
}

export interface UpdateWalletRequest {
    walletUpdate: WalletUpdate;
}

export interface VerifyWalletRequest {
    verifyIn: VerifyIn;
}

/**
 * 
 */
export class WalletsApi extends runtime.BaseAPI {

    /**
     * Creates request options for connectEoa without sending the request
     */
    async connectEoaRequestOpts(requestParameters: ConnectEoaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eoaIn'] == null) {
            throw new runtime.RequiredError(
                'eoaIn',
                'Required parameter "eoaIn" was null or undefined when calling connectEoa().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/wallets/connect/eoa`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EoaInToJSON(requestParameters['eoaIn']),
        };
    }

    /**
     * Authenticates (and if necessary registers) an externally-owned account (EOA) wallet via `eth_personal_sign`. Handles both first-time registration and returning users transparently.  **Flow:** 1. `GET /auth/challenge` — obtain a short-lived challenge string 2. `eth_personal_sign(challenge, privateKey)` — sign with the EOA key 3. POST here — the server runs `ecrecover` to derive the signer\'s address  On first connect the wallet record is created automatically. On subsequent connects the existing wallet is looked up by address and a new session is issued. 
     * Connect an EOA wallet
     */
    async connectEoaRaw(requestParameters: ConnectEoaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginOut>> {
        const requestOptions = await this.connectEoaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginOutFromJSON(jsonValue));
    }

    /**
     * Authenticates (and if necessary registers) an externally-owned account (EOA) wallet via `eth_personal_sign`. Handles both first-time registration and returning users transparently.  **Flow:** 1. `GET /auth/challenge` — obtain a short-lived challenge string 2. `eth_personal_sign(challenge, privateKey)` — sign with the EOA key 3. POST here — the server runs `ecrecover` to derive the signer\'s address  On first connect the wallet record is created automatically. On subsequent connects the existing wallet is looked up by address and a new session is issued. 
     * Connect an EOA wallet
     */
    async connectEoa(requestParameters: ConnectEoaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginOut> {
        const response = await this.connectEoaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteWallet without sending the request
     */
    async deleteWalletRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wallets/me`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete the current wallet
     * Delete current wallet
     */
    async deleteWalletRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.deleteWalletRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Delete the current wallet
     * Delete current wallet
     */
    async deleteWallet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.deleteWalletRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAuthChallenge without sending the request
     */
    async getAuthChallengeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/challenge`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a short-lived 32-byte random challenge (base64url-encoded, 60s TTL). Must be fetched immediately before the wallet operation — challenges are single-use and expire after 60 seconds.  Usage by auth type: - type=passkey (login): pass as the `challenge` in navigator.credentials.get() - type=eoa (connect/login): sign with eth_personal_sign, submit with the request - type=passkey (register): NOT required — the P-256 pubkey is self-proving 
     * Issue an authentication challenge
     */
    async getAuthChallengeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthChallenge>> {
        const requestOptions = await this.getAuthChallengeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthChallengeFromJSON(jsonValue));
    }

    /**
     * Returns a short-lived 32-byte random challenge (base64url-encoded, 60s TTL). Must be fetched immediately before the wallet operation — challenges are single-use and expire after 60 seconds.  Usage by auth type: - type=passkey (login): pass as the `challenge` in navigator.credentials.get() - type=eoa (connect/login): sign with eth_personal_sign, submit with the request - type=passkey (register): NOT required — the P-256 pubkey is self-proving 
     * Issue an authentication challenge
     */
    async getAuthChallenge(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthChallenge> {
        const response = await this.getAuthChallengeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWallet without sending the request
     */
    async getWalletRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wallets/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve the current authenticated user\'s wallet information. This endpoint returns detailed wallet data including profile information, account status, and associated metadata. Authentication is required via bearer token or API key. 
     * Get current wallet
     */
    async getWalletRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wallet>> {
        const requestOptions = await this.getWalletRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletFromJSON(jsonValue));
    }

    /**
     * Retrieve the current authenticated user\'s wallet information. This endpoint returns detailed wallet data including profile information, account status, and associated metadata. Authentication is required via bearer token or API key. 
     * Get current wallet
     */
    async getWallet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wallet> {
        const response = await this.getWalletRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWalletsRegistrationStats without sending the request
     */
    async getWalletsRegistrationStatsRequestOpts(requestParameters: GetWalletsRegistrationStatsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['org_id'] = requestParameters['orgId'];
        }

        if (requestParameters['interval'] != null) {
            queryParameters['interval'] = requestParameters['interval'];
        }

        if (requestParameters['timeRange'] != null) {
            queryParameters['time_range'] = requestParameters['timeRange'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['activated'] != null) {
            queryParameters['activated'] = requestParameters['activated'];
        }

        if (requestParameters['whenCreated$gt'] != null) {
            queryParameters['when_created[$gt]'] = (requestParameters['whenCreated$gt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lt'] != null) {
            queryParameters['when_created[$lt]'] = (requestParameters['whenCreated$lt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$gte'] != null) {
            queryParameters['when_created[$gte]'] = (requestParameters['whenCreated$gte'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lte'] != null) {
            queryParameters['when_created[$lte]'] = (requestParameters['whenCreated$lte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/stats/wallets/registration`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve time-series data about user registration patterns and trends. This endpoint provides detailed analytics on user sign-ups over time, including activation rates, registration velocity, and temporal distribution of new account creation. 
     * Get users registration statistics over time
     */
    async getWalletsRegistrationStatsRaw(requestParameters: GetWalletsRegistrationStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletsRegistrationStatsOut>> {
        const requestOptions = await this.getWalletsRegistrationStatsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletsRegistrationStatsOutFromJSON(jsonValue));
    }

    /**
     * Retrieve time-series data about user registration patterns and trends. This endpoint provides detailed analytics on user sign-ups over time, including activation rates, registration velocity, and temporal distribution of new account creation. 
     * Get users registration statistics over time
     */
    async getWalletsRegistrationStats(requestParameters: GetWalletsRegistrationStatsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletsRegistrationStatsOut> {
        const response = await this.getWalletsRegistrationStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWalletsStats without sending the request
     */
    async getWalletsStatsRequestOpts(requestParameters: GetWalletsStatsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['org_id'] = requestParameters['orgId'];
        }

        if (requestParameters['timeRange'] != null) {
            queryParameters['time_range'] = requestParameters['timeRange'];
        }

        if (requestParameters['whenCreated$gt'] != null) {
            queryParameters['when_created[$gt]'] = (requestParameters['whenCreated$gt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lt'] != null) {
            queryParameters['when_created[$lt]'] = (requestParameters['whenCreated$lt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$gte'] != null) {
            queryParameters['when_created[$gte]'] = (requestParameters['whenCreated$gte'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lte'] != null) {
            queryParameters['when_created[$lte]'] = (requestParameters['whenCreated$lte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/stats/wallets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve comprehensive statistics about user wallets and account activity. This endpoint provides aggregate data including total user counts, registration trends, and activity metrics over specified time ranges for analytics and reporting purposes. 
     * Get users statistics
     */
    async getWalletsStatsRaw(requestParameters: GetWalletsStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletsStatsOut>> {
        const requestOptions = await this.getWalletsStatsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletsStatsOutFromJSON(jsonValue));
    }

    /**
     * Retrieve comprehensive statistics about user wallets and account activity. This endpoint provides aggregate data including total user counts, registration trends, and activity metrics over specified time ranges for analytics and reporting purposes. 
     * Get users statistics
     */
    async getWalletsStats(requestParameters: GetWalletsStatsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletsStatsOut> {
        const response = await this.getWalletsStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWalletsTotalStats without sending the request
     */
    async getWalletsTotalStatsRequestOpts(requestParameters: GetWalletsTotalStatsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['org_id'] = requestParameters['orgId'];
        }

        if (requestParameters['interval'] != null) {
            queryParameters['interval'] = requestParameters['interval'];
        }

        if (requestParameters['timeRange'] != null) {
            queryParameters['time_range'] = requestParameters['timeRange'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['whenCreated$gt'] != null) {
            queryParameters['when_created[$gt]'] = (requestParameters['whenCreated$gt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lt'] != null) {
            queryParameters['when_created[$lt]'] = (requestParameters['whenCreated$lt'] as any).toISOString();
        }

        if (requestParameters['whenCreated$gte'] != null) {
            queryParameters['when_created[$gte]'] = (requestParameters['whenCreated$gte'] as any).toISOString();
        }

        if (requestParameters['whenCreated$lte'] != null) {
            queryParameters['when_created[$lte]'] = (requestParameters['whenCreated$lte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/stats/wallets/total`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve comprehensive statistics about user wallets and account activity over time. This endpoint provides aggregate data including total user counts, registration trends, and activity metrics over specified time ranges for analytics and reporting purposes. 
     * Get users statistics over time
     */
    async getWalletsTotalStatsRaw(requestParameters: GetWalletsTotalStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletsTotalStatsOut>> {
        const requestOptions = await this.getWalletsTotalStatsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletsTotalStatsOutFromJSON(jsonValue));
    }

    /**
     * Retrieve comprehensive statistics about user wallets and account activity over time. This endpoint provides aggregate data including total user counts, registration trends, and activity metrics over specified time ranges for analytics and reporting purposes. 
     * Get users statistics over time
     */
    async getWalletsTotalStats(requestParameters: GetWalletsTotalStatsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletsTotalStatsOut> {
        const response = await this.getWalletsTotalStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for loginWallet without sending the request
     */
    async loginWalletRequestOpts(requestParameters: LoginWalletRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['loginIn'] == null) {
            throw new runtime.RequiredError(
                'loginIn',
                'Required parameter "loginIn" was null or undefined when calling loginWallet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginInToJSON(requestParameters['loginIn']),
        };
    }

    /**
     * Authenticate a user with their credentials and return access tokens. This endpoint accepts email/phone and password combinations to verify user identity. Upon successful authentication, the system returns both access and refresh tokens for secure API access. 
     * Login
     */
    async loginWalletRaw(requestParameters: LoginWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginOut>> {
        const requestOptions = await this.loginWalletRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginOutFromJSON(jsonValue));
    }

    /**
     * Authenticate a user with their credentials and return access tokens. This endpoint accepts email/phone and password combinations to verify user identity. Upon successful authentication, the system returns both access and refresh tokens for secure API access. 
     * Login
     */
    async loginWallet(requestParameters: LoginWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginOut> {
        const response = await this.loginWalletRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for passkeyLoginOptions without sending the request
     */
    async passkeyLoginOptionsRequestOpts(requestParameters: PasskeyLoginOptionsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/wallets/connect/passkey/login/options`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Issues a challenge and returns `PublicKeyCredentialRequestOptions`. Pass the response body directly to `navigator.credentials.get({ publicKey: response })`.  **Flow:** 1. POST here (no body required) 2. Call `navigator.credentials.get({ publicKey: <response> })` in the browser 3. POST the resulting assertion to `POST /wallets/passkey/login/verify` 
     * Get WebAuthn login options
     */
    async passkeyLoginOptionsRaw(requestParameters: PasskeyLoginOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PasskeyLoginOptionsOut>> {
        const requestOptions = await this.passkeyLoginOptionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PasskeyLoginOptionsOutFromJSON(jsonValue));
    }

    /**
     * Issues a challenge and returns `PublicKeyCredentialRequestOptions`. Pass the response body directly to `navigator.credentials.get({ publicKey: response })`.  **Flow:** 1. POST here (no body required) 2. Call `navigator.credentials.get({ publicKey: <response> })` in the browser 3. POST the resulting assertion to `POST /wallets/passkey/login/verify` 
     * Get WebAuthn login options
     */
    async passkeyLoginOptions(requestParameters: PasskeyLoginOptionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PasskeyLoginOptionsOut> {
        const response = await this.passkeyLoginOptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for passkeyLoginVerify without sending the request
     */
    async passkeyLoginVerifyRequestOpts(requestParameters: PasskeyLoginVerifyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['passkeyLoginVerifyIn'] == null) {
            throw new runtime.RequiredError(
                'passkeyLoginVerifyIn',
                'Required parameter "passkeyLoginVerifyIn" was null or undefined when calling passkeyLoginVerify().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/wallets/connect/passkey/login/verify`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PasskeyLoginVerifyInToJSON(requestParameters['passkeyLoginVerifyIn']),
        };
    }

    /**
     * Verifies the WebAuthn assertion produced by `navigator.credentials.get()` and, on success, returns a session for the wallet identified by the credential.  **Server-side steps:** 1. Look up the wallet by credential ID to retrieve `(pubkey_x, pubkey_y)` 2. Decode the DER-encoded signature into `(r, s)` scalars 3. Compute `messageHash = sha256(authenticatorData || sha256(clientDataJSON))` 4. Verify P-256 signature `(r, s)` over `messageHash` against the stored public key 5. Verify `clientDataJSON.challenge` matches the issued challenge (consumed after use) 6. Verify `clientDataJSON.origin`, `rpIdHash`, and WebAuthn flags (UP, UV) 7. Issue JWT tokens 
     * Verify WebAuthn login assertion
     */
    async passkeyLoginVerifyRaw(requestParameters: PasskeyLoginVerifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginOut>> {
        const requestOptions = await this.passkeyLoginVerifyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginOutFromJSON(jsonValue));
    }

    /**
     * Verifies the WebAuthn assertion produced by `navigator.credentials.get()` and, on success, returns a session for the wallet identified by the credential.  **Server-side steps:** 1. Look up the wallet by credential ID to retrieve `(pubkey_x, pubkey_y)` 2. Decode the DER-encoded signature into `(r, s)` scalars 3. Compute `messageHash = sha256(authenticatorData || sha256(clientDataJSON))` 4. Verify P-256 signature `(r, s)` over `messageHash` against the stored public key 5. Verify `clientDataJSON.challenge` matches the issued challenge (consumed after use) 6. Verify `clientDataJSON.origin`, `rpIdHash`, and WebAuthn flags (UP, UV) 7. Issue JWT tokens 
     * Verify WebAuthn login assertion
     */
    async passkeyLoginVerify(requestParameters: PasskeyLoginVerifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginOut> {
        const response = await this.passkeyLoginVerifyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for passkeyRegisterOptions without sending the request
     */
    async passkeyRegisterOptionsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/wallets/connect/passkey/register/options`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Issues a challenge and returns `PublicKeyCredentialCreationOptions`. Pass the response body directly to `navigator.credentials.create({ publicKey: response })`.  **Flow:** 1. GET here to receive a challenge and creation options 2. Call `navigator.credentials.create({ publicKey: <response> })` in the browser 3. POST the resulting credential to `POST /wallets/passkey/register/verify` 
     * Get WebAuthn registration options
     */
    async passkeyRegisterOptionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PasskeyRegisterOptionsOut>> {
        const requestOptions = await this.passkeyRegisterOptionsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PasskeyRegisterOptionsOutFromJSON(jsonValue));
    }

    /**
     * Issues a challenge and returns `PublicKeyCredentialCreationOptions`. Pass the response body directly to `navigator.credentials.create({ publicKey: response })`.  **Flow:** 1. GET here to receive a challenge and creation options 2. Call `navigator.credentials.create({ publicKey: <response> })` in the browser 3. POST the resulting credential to `POST /wallets/passkey/register/verify` 
     * Get WebAuthn registration options
     */
    async passkeyRegisterOptions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PasskeyRegisterOptionsOut> {
        const response = await this.passkeyRegisterOptionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for passkeyRegisterVerify without sending the request
     */
    async passkeyRegisterVerifyRequestOpts(requestParameters: PasskeyRegisterVerifyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['passkeyRegisterVerifyIn'] == null) {
            throw new runtime.RequiredError(
                'passkeyRegisterVerifyIn',
                'Required parameter "passkeyRegisterVerifyIn" was null or undefined when calling passkeyRegisterVerify().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/wallets/connect/passkey/register/verify`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PasskeyRegisterVerifyInToJSON(requestParameters['passkeyRegisterVerifyIn']),
        };
    }

    /**
     * Verifies the WebAuthn attestation produced by `navigator.credentials.create()` and, on success, creates a new wallet and returns a session.  **Server-side steps:** 1. Decode the `attestationObject` (CBOR) and extract the credential\'s P-256 public key 2. Verify `clientDataJSON.challenge` matches the issued challenge (consumed after use) 3. Verify `clientDataJSON.origin` and `rpIdHash` 4. Derive the smart wallet address from `(pubkey_x, pubkey_y)` via the factory 5. Store the credential and issue JWT tokens 
     * Verify WebAuthn registration and create wallet
     */
    async passkeyRegisterVerifyRaw(requestParameters: PasskeyRegisterVerifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginOut>> {
        const requestOptions = await this.passkeyRegisterVerifyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginOutFromJSON(jsonValue));
    }

    /**
     * Verifies the WebAuthn attestation produced by `navigator.credentials.create()` and, on success, creates a new wallet and returns a session.  **Server-side steps:** 1. Decode the `attestationObject` (CBOR) and extract the credential\'s P-256 public key 2. Verify `clientDataJSON.challenge` matches the issued challenge (consumed after use) 3. Verify `clientDataJSON.origin` and `rpIdHash` 4. Derive the smart wallet address from `(pubkey_x, pubkey_y)` via the factory 5. Store the credential and issue JWT tokens 
     * Verify WebAuthn registration and create wallet
     */
    async passkeyRegisterVerify(requestParameters: PasskeyRegisterVerifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginOut> {
        const response = await this.passkeyRegisterVerifyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for refreshToken without sending the request
     */
    async refreshTokenRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/refresh-token`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * refresh access token
     * Refresh access token
     */
    async refreshTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RefreshTokenOut>> {
        const requestOptions = await this.refreshTokenRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RefreshTokenOutFromJSON(jsonValue));
    }

    /**
     * refresh access token
     * Refresh access token
     */
    async refreshToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RefreshTokenOut> {
        const response = await this.refreshTokenRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerWallet without sending the request
     */
    async registerWalletRequestOpts(requestParameters: RegisterWalletRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['walletCreate'] == null) {
            throw new runtime.RequiredError(
                'walletCreate',
                'Required parameter "walletCreate" was null or undefined when calling registerWallet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/wallets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WalletCreateToJSON(requestParameters['walletCreate']),
        };
    }

    /**
     * Register a new wallet in the system. This endpoint allows users to create a new wallet account with basic information such as email, phone number, and password. Upon successful registration, the system returns authentication tokens for immediate access to the platform. 
     * Register a new wallet
     */
    async registerWalletRaw(requestParameters: RegisterWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginOut>> {
        const requestOptions = await this.registerWalletRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginOutFromJSON(jsonValue));
    }

    /**
     * Register a new wallet in the system. This endpoint allows users to create a new wallet account with basic information such as email, phone number, and password. Upon successful registration, the system returns authentication tokens for immediate access to the platform. 
     * Register a new wallet
     */
    async registerWallet(requestParameters: RegisterWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginOut> {
        const response = await this.registerWalletRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for requestOTPCode without sending the request
     */
    async requestOTPCodeRequestOpts(requestParameters: RequestOTPCodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['requestOTPCodeIn'] == null) {
            throw new runtime.RequiredError(
                'requestOTPCodeIn',
                'Required parameter "requestOTPCodeIn" was null or undefined when calling requestOTPCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/otp`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestOTPCodeInToJSON(requestParameters['requestOTPCodeIn']),
        };
    }

    /**
     * Request a one-time password (OTP) code to be sent to the user\'s email or phone number. This endpoint is used for multi-factor authentication and account security verification. 
     * Request OTP code
     */
    async requestOTPCodeRaw(requestParameters: RequestOTPCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.requestOTPCodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Request a one-time password (OTP) code to be sent to the user\'s email or phone number. This endpoint is used for multi-factor authentication and account security verification. 
     * Request OTP code
     */
    async requestOTPCode(requestParameters: RequestOTPCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.requestOTPCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for requestVerificationCode without sending the request
     */
    async requestVerificationCodeRequestOpts(requestParameters: RequestVerificationCodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resetCodeIn'] == null) {
            throw new runtime.RequiredError(
                'resetCodeIn',
                'Required parameter "resetCodeIn" was null or undefined when calling requestVerificationCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/verification-code`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetCodeInToJSON(requestParameters['resetCodeIn']),
        };
    }

    /**
     * Request a verification code to be sent to the user\'s email or phone number. This endpoint initiates the account verification process by generating and delivering a secure code for wallet activation. 
     * Request verification code
     */
    async requestVerificationCodeRaw(requestParameters: RequestVerificationCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.requestVerificationCodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Request a verification code to be sent to the user\'s email or phone number. This endpoint initiates the account verification process by generating and delivering a secure code for wallet activation. 
     * Request verification code
     */
    async requestVerificationCode(requestParameters: RequestVerificationCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.requestVerificationCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resetPassword without sending the request
     */
    async resetPasswordRequestOpts(requestParameters: ResetPasswordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resetPasswordIn'] == null) {
            throw new runtime.RequiredError(
                'resetPasswordIn',
                'Required parameter "resetPasswordIn" was null or undefined when calling resetPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetPasswordInToJSON(requestParameters['resetPasswordIn']),
        };
    }

    /**
     * request password reset
     * Request password reset
     */
    async resetPasswordRaw(requestParameters: ResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.resetPasswordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * request password reset
     * Request password reset
     */
    async resetPassword(requestParameters: ResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.resetPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setNewPassword without sending the request
     */
    async setNewPasswordRequestOpts(requestParameters: SetNewPasswordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['setNewPasswordIn'] == null) {
            throw new runtime.RequiredError(
                'setNewPasswordIn',
                'Required parameter "setNewPasswordIn" was null or undefined when calling setNewPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/set-password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetNewPasswordInToJSON(requestParameters['setNewPasswordIn']),
        };
    }

    /**
     * Set a new password for the user account using a security token. This endpoint allows users to reset their password when they have forgotten it, using a token received via email or SMS. 
     * Set new password
     */
    async setNewPasswordRaw(requestParameters: SetNewPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.setNewPasswordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Set a new password for the user account using a security token. This endpoint allows users to reset their password when they have forgotten it, using a token received via email or SMS. 
     * Set new password
     */
    async setNewPassword(requestParameters: SetNewPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.setNewPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateWallet without sending the request
     */
    async updateWalletRequestOpts(requestParameters: UpdateWalletRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['walletUpdate'] == null) {
            throw new runtime.RequiredError(
                'walletUpdate',
                'Required parameter "walletUpdate" was null or undefined when calling updateWallet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // api-key-auth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wallets/me`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: WalletUpdateToJSON(requestParameters['walletUpdate']),
        };
    }

    /**
     * Update the current authenticated user\'s wallet information. This endpoint allows users to modify their profile details, contact information, and account preferences. Only the authenticated user can update their own wallet data. 
     * Update wallet
     */
    async updateWalletRaw(requestParameters: UpdateWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.updateWalletRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Update the current authenticated user\'s wallet information. This endpoint allows users to modify their profile details, contact information, and account preferences. Only the authenticated user can update their own wallet data. 
     * Update wallet
     */
    async updateWallet(requestParameters: UpdateWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.updateWalletRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for verifyWallet without sending the request
     */
    async verifyWalletRequestOpts(requestParameters: VerifyWalletRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['verifyIn'] == null) {
            throw new runtime.RequiredError(
                'verifyIn',
                'Required parameter "verifyIn" was null or undefined when calling verifyWallet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/verify`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyInToJSON(requestParameters['verifyIn']),
        };
    }

    /**
     * Verify a wallet account using a verification code sent to the user\'s email or phone number. This endpoint is used to confirm account ownership and activate the wallet for full platform access. 
     * Verify wallet
     */
    async verifyWalletRaw(requestParameters: VerifyWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.verifyWalletRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Verify a wallet account using a verification code sent to the user\'s email or phone number. This endpoint is used to confirm account ownership and activate the wallet for full platform access. 
     * Verify wallet
     */
    async verifyWallet(requestParameters: VerifyWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.verifyWalletRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetWalletsRegistrationStatsIntervalEnum = {
    Hour: 'hour',
    Day: 'day',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type GetWalletsRegistrationStatsIntervalEnum = typeof GetWalletsRegistrationStatsIntervalEnum[keyof typeof GetWalletsRegistrationStatsIntervalEnum];
/**
 * @export
 */
export const GetWalletsRegistrationStatsTimeRangeEnum = {
    All: 'all',
    Today: 'today',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type GetWalletsRegistrationStatsTimeRangeEnum = typeof GetWalletsRegistrationStatsTimeRangeEnum[keyof typeof GetWalletsRegistrationStatsTimeRangeEnum];
/**
 * @export
 */
export const GetWalletsStatsTimeRangeEnum = {
    All: 'all',
    Today: 'today',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type GetWalletsStatsTimeRangeEnum = typeof GetWalletsStatsTimeRangeEnum[keyof typeof GetWalletsStatsTimeRangeEnum];
/**
 * @export
 */
export const GetWalletsTotalStatsIntervalEnum = {
    Hour: 'hour',
    Day: 'day',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type GetWalletsTotalStatsIntervalEnum = typeof GetWalletsTotalStatsIntervalEnum[keyof typeof GetWalletsTotalStatsIntervalEnum];
/**
 * @export
 */
export const GetWalletsTotalStatsTimeRangeEnum = {
    All: 'all',
    Today: 'today',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type GetWalletsTotalStatsTimeRangeEnum = typeof GetWalletsTotalStatsTimeRangeEnum[keyof typeof GetWalletsTotalStatsTimeRangeEnum];
